(function(){
  'use strict';

  const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
  const ui={
    base:$('baseView'),expedition:$('expeditionView'),scene:document.querySelector('.workshopScene'),
    bank:$('bankScrap'),cores:$('coreCount'),best:$('bestDepth'),settingsButton:$('settingsButton'),
    chassisLevel:$('chassisLevel'),weaponLevel:$('weaponLevel'),salvageLevel:$('salvageLevel'),
    maxHp:$('maxHpStat'),damage:$('damageStat'),magnet:$('magnetStat'),
    chassisCost:$('chassisCost'),weaponCost:$('weaponCost'),salvageCost:$('salvageCost'),
    upgradeChassis:$('upgradeChassis'),upgradeWeapon:$('upgradeWeapon'),upgradeSalvage:$('upgradeSalvage'),
    start:$('startButton'),notice:$('baseNotice'),blueprintButton:$('blueprintButton'),starterIcon:$('starterIcon'),starterName:$('starterName'),
    blueprintOverlay:$('blueprintOverlay'),closeBlueprints:$('closeBlueprints'),starterReadout:$('starterReadout'),wardenTechGrid:$('wardenTechGrid'),blueprintGrid:$('blueprintGrid'),careerStats:$('careerStats'),
    briefingOverlay:$('briefingOverlay'),briefingStart:$('briefingStart'),contractTracker:$('contractTracker'),contractTitle:$('contractTitle'),contractReadout:$('contractReadout'),contractFill:$('contractFill'),contractOverlay:$('contractOverlay'),closeContract:$('closeContract'),
    resultOverlay:$('resultOverlay'),resultPanel:document.querySelector('.resultPanel'),resultTitle:$('resultTitle'),resultScrap:$('resultScrap'),resultDepth:$('resultDepth'),resultTime:$('resultTime'),resultKills:$('resultKills'),resultDamage:$('resultDamage'),resultRisk:$('resultRisk'),resultItems:$('resultItems'),resultRecord:$('resultRecord'),resultLoot:$('resultLoot'),resultModules:$('resultModules'),closeResult:$('closeResult'),
    healthText:$('healthText'),healthFill:$('healthFill'),runScrap:$('runScrap'),lootMetric:$('lootMetric'),lootBest:$('lootBest'),depth:$('depthText'),risk:$('riskText'),extract:$('extractButton'),
    depthRoute:$('depthRoute'),routeLabel:$('routeLabel'),routeTicks:$('routeTicks'),routeProgress:$('routeProgressFill'),runNotice:$('runNotice'),lootToast:$('lootToast'),lootToastIcon:$('lootToastIcon'),lootToastRarity:$('lootToastRarity'),lootToastName:$('lootToastName'),lootToastValue:$('lootToastValue'),cargoHud:$('cargoHud'),cargoSlots:$('cargoSlots'),zoneHud:$('zoneHud'),zoneDepth:$('zoneDepth'),zoneName:$('zoneName'),buildHud:$('buildHud'),buildName:$('buildName'),bossHud:$('bossHud'),bossName:$('bossName'),bossHealthFill:$('bossHealthFill'),bossPhase:$('bossPhaseText'),
    extractOverlay:$('extractOverlay'),extractCount:$('extractCount'),cancelExtract:$('cancelExtract'),
    riskOverlay:$('riskOverlay'),riskScrap:$('riskScrap'),riskBest:$('riskBest'),nextMultiplier:$('nextMultiplier'),riskExtract:$('riskExtract'),riskPush:$('riskPush'),routeOverlay:$('routeOverlay'),routeFurnace:$('routeFurnace'),routeDynamo:$('routeDynamo'),
    moduleOverlay:$('moduleOverlay'),moduleEyebrow:$('moduleEyebrow'),moduleTitle:$('moduleTitle'),moduleChoices:$('moduleChoices'),moduleSkip:$('moduleSkip'),
    joystick:$('joystick'),knob:$('joystickKnob'),dash:$('dashButton'),
    settingsOverlay:$('settingsOverlay'),settingsPanel:document.querySelector('.settingsPanel'),closeSettings:$('closeSettings'),soundToggle:$('soundToggle'),shakeToggle:$('shakeToggle'),particlesToggle:$('particlesToggle'),resume:$('resumeButton'),abandon:$('abandonButton'),
    devButton:$('devButton'),devPanel:$('devPanel'),devScrap:$('devScrap'),devRig:$('devRig'),devHeal:$('devHeal'),devCache:$('devCache'),devLoot:$('devLoot'),devWarden:$('devWarden'),devTyrant:$('devTyrant'),devSchematic:$('devSchematic'),devReset:$('devReset')
  };

  const SAVE_KEY='scrapbound_prototype_v1',SAVE_VERSION=7,WORLD={w:2400,h:1600},DEPTH_THRESHOLDS=[0,55,120,195,280];
  const LIMITS={enemies:72,bullets:220,enemyBullets:260,loot:180,particles:320};
  const COMMON_ZONES=[
    {name:'FOUNDRY APPROACH',threat:'SCRAP HOUNDS',top:'#253033',bottom:'#111719',grid:'#88939714',accent:'#d7863b',pool:['rusher','rusher','rusher','shooter']},
    {name:'CONVEYOR SPINE',threat:'RIVET SENTRIES',top:'#1d3033',bottom:'#0d1719',grid:'#47c5b61b',accent:'#47c5b6',pool:['rusher','shooter','shooter','shooter']}
  ];
  const ROUTES={
    furnace:{name:'FURNACE ROUTE',short:'FURNACE',scrap:1.16,relicRare:0,lootRare:0,boss:'tyrant',zones:[
      {name:'CINDER WORKS',threat:'PRESSURE VENTS',top:'#39251c',bottom:'#180d09',grid:'#ef8f3c20',accent:'#ef8f3c',pool:['rusher','brute','brute','shooter']},
      {name:'BOILER ASCENT',threat:'FIRE ZONES',top:'#321a16',bottom:'#110807',grid:'#ff6b3520',accent:'#ff7a3d',pool:['brute','brute','shooter','rusher']},
      {name:'TYRANT FORGE',threat:'FURNACE TYRANT',top:'#2d1510',bottom:'#0d0706',grid:'#ff6b3524',accent:'#ff7a3d',pool:['brute','shooter','rusher']}
    ]},
    dynamo:{name:'DYNAMO ROUTE',short:'DYNAMO',scrap:1,relicRare:.04,lootRare:.08,boss:'warden',zones:[
      {name:'DYNAMO CONDUIT',threat:'ARC SENTRIES',top:'#202a3c',bottom:'#0c111e',grid:'#7c8cff1d',accent:'#8f9dff',pool:['shooter','shooter','rusher','rusher']},
      {name:'STORM VAULT',threat:'ARC LANCERS',top:'#171f35',bottom:'#080d19',grid:'#7c8cff22',accent:'#9da8ff',pool:['shooter','lancer','lancer','brute']},
      {name:'WARDEN CORE',threat:'SCRAP WARDEN',top:'#281b1d',bottom:'#0d090a',grid:'#ef535019',accent:'#ef5350',pool:['lancer','brute','shooter']}
    ]}
  };
  const BOSSES={
    warden:{name:'SCRAP WARDEN',kind:'warden',accent:'#ef5350',phase:['PHASE I \u00B7 ACQUISITION','PHASE II \u00B7 MAGNETIC STORM','PHASE III \u00B7 OVERCLOCK']},
    tyrant:{name:'FURNACE TYRANT',kind:'tyrant',accent:'#ff7a3d',phase:['PHASE I \u00B7 PRESSURE BUILD','PHASE II \u00B7 BOILER BREACH','PHASE III \u00B7 MELTDOWN']}
  };
  const MODULES={
    burst:{name:'Burst Capacitor',icon:'\u2726',desc:'Adds another projectile to every volley.'},
    magnet:{name:'Magnetic Core',icon:'\u25CE',desc:'Pulls loot and relic caches from farther away.'},
    plating:{name:'Reactive Plating',icon:'\u25C6',desc:'Blocks incoming hits before armor takes damage.'},
    overdrive:{name:'Overdrive Coil',icon:'\u00BB',desc:'Boosts movement speed and cannon fire rate.'},
    volatile:{name:'Volatile Reactor',icon:'!',desc:'Raises damage, but lowers maximum health.'}
  };
  const MODULE_IDS=Object.keys(MODULES),BLUEPRINT_THRESHOLDS=[0,1,3,7];
  const BOSS_SCHEMATICS={
    aegis:{name:'Aegis Lattice',icon:'\u25C6',desc:'Begin every expedition with another shield charge.',max:3},
    thrusters:{name:'Phase Bearings',icon:'\u00BB',desc:'Reduces dash recharge time for every expedition.',max:5},
    recycler:{name:'Reclaimer Matrix',icon:'\u2B22',desc:'Raises the sale value of all loot recovered in the field.',max:5},
    thermal:{name:'Thermal Capacitor',icon:'\u2739',desc:'Dashing charges explosive cannon volleys for every expedition.',max:3}
  };
  const WARDEN_SCHEMATIC_IDS=['aegis','thrusters','recycler'],TYRANT_SCHEMATIC_IDS=['thermal'],SCHEMATIC_IDS=[...WARDEN_SCHEMATIC_IDS,...TYRANT_SCHEMATIC_IDS],CORE_DIVIDEND=300;
  const LOOT_RARITIES={
    common:{name:'COMMON',rank:0,color:'#aeb8bb',glow:'#7d898d'},
    rare:{name:'RARE',rank:1,color:'#47c5b6',glow:'#7ff4e6'},
    epic:{name:'EPIC',rank:2,color:'#8f9dff',glow:'#c8ceff'},
    mythic:{name:'MYTHIC',rank:3,color:'#ff7a3d',glow:'#ffc28e'},
    legendary:{name:'LEGENDARY',rank:4,color:'#f2c14f',glow:'#fff0a8'}
  };
  const LOOT_ITEMS=[
    {id:'bentCog',name:'Bent Cog',rarity:'common',value:1,form:'gear'},
    {id:'copperWire',name:'Copper Wire',rarity:'common',value:1,form:'coil'},
    {id:'rustedBolt',name:'Rusted Bolt',rarity:'common',value:1,form:'bolt'},
    {id:'brassWasher',name:'Brass Washer',rarity:'common',value:1,form:'ring'},
    {id:'crackedGauge',name:'Cracked Gauge',rarity:'common',value:2,form:'gauge'},
    {id:'valveHandle',name:'Valve Handle',rarity:'common',value:2,form:'gear'},
    {id:'tinPlate',name:'Tin Plate',rarity:'common',value:2,form:'plate'},
    {id:'emptyCanister',name:'Empty Canister',rarity:'common',value:2,form:'canister'},
    {id:'wornSpring',name:'Worn Spring',rarity:'common',value:2,form:'coil'},
    {id:'gearTooth',name:'Gear Tooth',rarity:'common',value:2,form:'bolt'},
    {id:'rivetBundle',name:'Rivet Bundle',rarity:'common',value:3,form:'bolt'},
    {id:'frayedBelt',name:'Frayed Belt',rarity:'common',value:3,form:'ring'},
    {id:'sootFilter',name:'Soot Filter',rarity:'common',value:3,form:'plate'},
    {id:'ironBracket',name:'Iron Bracket',rarity:'common',value:3,form:'plate'},
    {id:'pipeCoupling',name:'Pipe Coupling',rarity:'common',value:3,form:'ring'},
    {id:'fuseShell',name:'Fuse Shell',rarity:'common',value:3,form:'canister'},
    {id:'boilerSeal',name:'Boiler Seal',rarity:'common',value:4,form:'ring'},
    {id:'chainLink',name:'Chain Link',rarity:'common',value:4,form:'coil'},
    {id:'scrapLens',name:'Scrap Lens',rarity:'common',value:4,form:'lens'},
    {id:'motorBrush',name:'Motor Brush',rarity:'common',value:4,form:'coil'},
    {id:'pressureRegulator',name:'Pressure Regulator',rarity:'rare',value:6,form:'gauge'},
    {id:'dynamoCoil',name:'Dynamo Coil',rarity:'rare',value:6,form:'coil'},
    {id:'brassGyroscope',name:'Brass Gyroscope',rarity:'rare',value:7,form:'ring'},
    {id:'hardenedPiston',name:'Hardened Piston',rarity:'rare',value:7,form:'canister'},
    {id:'arcRelay',name:'Arc Relay',rarity:'rare',value:8,form:'plate'},
    {id:'steamInjector',name:'Steam Injector',rarity:'rare',value:8,form:'canister'},
    {id:'precisionBearing',name:'Precision Bearing',rarity:'rare',value:9,form:'gear'},
    {id:'insulatedConduit',name:'Insulated Conduit',rarity:'rare',value:9,form:'coil'},
    {id:'wardenOptic',name:'Warden Optic',rarity:'rare',value:10,form:'lens'},
    {id:'cinderCarburetor',name:'Cinder Carburetor',rarity:'rare',value:10,form:'gear'},
    {id:'aetherCondenser',name:'Aether Condenser',rarity:'epic',value:16,form:'canister'},
    {id:'voidCompass',name:'Void Compass',rarity:'epic',value:18,form:'gauge'},
    {id:'royalFlywheel',name:'Royal Flywheel',rarity:'epic',value:20,form:'gear'},
    {id:'stormglassCell',name:'Stormglass Cell',rarity:'epic',value:22,form:'lens'},
    {id:'furnaceHeart',name:'Furnace Heart',rarity:'epic',value:24,form:'core'},
    {id:'crownGear',name:'Crown Gear',rarity:'mythic',value:40,form:'gear'},
    {id:'phantomLantern',name:'Phantom Lantern',rarity:'mythic',value:50,form:'canister'},
    {id:'chronoEscapement',name:'Chrono Escapement',rarity:'mythic',value:60,form:'gauge'},
    {id:'tyrantEmbercore',name:'Tyrant Embercore',rarity:'legendary',value:140,form:'core'},
    {id:'wardenSingularity',name:'Warden Singularity',rarity:'legendary',value:180,form:'core'}
  ];
  const LOOT_BY_RARITY=Object.keys(LOOT_RARITIES).reduce((groups,rarity)=>{groups[rarity]=LOOT_ITEMS.filter(item=>item.rarity===rarity);return groups},{}),LOOT_BY_ID=Object.fromEntries(LOOT_ITEMS.map(item=>[item.id,item])),RELIC_POWER_CAP=4;
  const SYNERGIES=[
    {id:'shrapnel',name:'SHRAPNEL ARRAY',needs:['burst','volatile'],desc:'Every third volley detonates on impact.'},
    {id:'flux',name:'FLUX DRIVE',needs:['magnet','overdrive'],desc:'Faster dashes that recharge while salvaging.'},
    {id:'kinetic',name:'KINETIC GUARD',needs:['plating','overdrive'],desc:'Dashing becomes a shielded ramming attack.'},
    {id:'counter',name:'COUNTER BATTERY',needs:['burst','plating'],desc:'Blocking a hit fires a defensive volley.'},
    {id:'singularity',name:'SINGULARITY REACTOR',needs:['magnet','volatile'],desc:'Recovered loot is worth 18% more.'}
  ];
  const keys={},stick={active:false,id:null,x:0,y:0},audio={ctx:null,timer:null,mode:'base',step:0};
  let save=loadSave(),mode='base',paused=false,settingsWasRun=false,abandonArmed=false,devResetArmed=false;
  let W=960,H=540,dpr=1,last=0,elapsed=0,runTime=0,spawnClock=0,hazardClock=0,shake=0,flash=0,depthPulse=0,extracting=0,runScrap=0,depth=1,riskTier=0,decision=false,routeDecision=false,route=null,zoneEventTriggered=false;
  let player,enemies=[],bullets=[],enemyBullets=[],lootDrops=[],particles=[],effects=[],hazards=[],decor=[],caches=[],cargo=[],lootBag={};
  let moduleDecision=false,moduleStage='offer',moduleOffer=[],pendingModule=null,activeCache=null,pendingWardenReward=null,bossActive=false,bossDefeated=false,bossEntity=null,runStats=null;

  function clampNumber(value,min,max){value=Number(value);return Number.isFinite(value)?Math.max(min,Math.min(max,value)):min}
  function defaultBlueprint(){return {copies:0,rare:0,tune:0}}
  function defaultSave(){return {version:SAVE_VERSION,scrap:0,best:0,bestRisk:0,cores:0,contractComplete:false,contractSeen:false,chassis:0,weapon:0,salvage:0,starter:null,seenIntro:false,blueprints:{},schematics:{aegis:0,thrusters:0,recycler:0,thermal:0},lootFound:{},stats:{runs:0,extractions:0,losses:0,bosses:0,totalScrap:0,totalTime:0,totalKills:0,totalDamage:0,totalRisks:0,itemsRecovered:0,legendaryRecovered:0},playtest:{runs:[],modulePicks:{}},settings:{sound:true,shake:true,particles:true}}}
  function loadSave(){
    let raw={};try{raw=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')||{}}catch(e){}
    let data=defaultSave(),legacy=Math.max(0,Number(raw.rig)||0);data.scrap=clampNumber(raw.scrap,0,1e15);data.best=Math.floor(clampNumber(raw.best,0,999));data.bestRisk=Math.floor(clampNumber(raw.bestRisk,0,99));data.cores=Math.floor(clampNumber(raw.cores,0,9999));data.contractComplete=!!raw.contractComplete;data.contractSeen=!!raw.contractSeen;data.chassis=Math.floor(clampNumber(raw.chassis==null?legacy:raw.chassis,0,200));data.weapon=Math.floor(clampNumber(raw.weapon==null?legacy:raw.weapon,0,200));data.salvage=Math.floor(clampNumber(raw.salvage,0,200));
    data.seenIntro=!!raw.seenIntro;data.settings=Object.assign(data.settings,raw.settings||{});for(const key of Object.keys(data.settings))data.settings[key]=data.settings[key]!==false;
    data.stats=Object.assign(data.stats,raw.stats||{});for(const key of Object.keys(data.stats))data.stats[key]=Math.floor(clampNumber(data.stats[key],0,1e12));
    let oldPlaytest=raw.playtest&&typeof raw.playtest==='object'?raw.playtest:{};data.playtest.runs=Array.isArray(oldPlaytest.runs)?oldPlaytest.runs.slice(-12).map(run=>({outcome:run&&run.outcome==='secured'?'secured':'lost',depth:Math.floor(clampNumber(run&&run.depth,1,5)),time:Math.floor(clampNumber(run&&run.time,0,3600)),scrap:Math.floor(clampNumber(run&&run.scrap,0,1e9)),kills:Math.floor(clampNumber(run&&run.kills,0,9999)),damage:Math.floor(clampNumber(run&&run.damage,0,1e9)),risks:Math.floor(clampNumber(run&&run.risks,0,9)),items:Math.floor(clampNumber(run&&run.items,0,9999)),legendary:Math.floor(clampNumber(run&&run.legendary,0,999)),route:run&&(run.route==='furnace'||run.route==='dynamo')?run.route:null,warden:run&&(BOSS_SCHEMATICS[run.warden]||run.warden==='dividend')?run.warden:null})):[];
    for(const id of SCHEMATIC_IDS)data.schematics[id]=Math.floor(clampNumber(raw.schematics&&raw.schematics[id],0,BOSS_SCHEMATICS[id].max));
    for(const id of MODULE_IDS){let old=raw.blueprints&&raw.blueprints[id],record=defaultBlueprint();if(old&&typeof old==='object'){record.copies=Math.floor(clampNumber(old.copies,0,9999));record.rare=Math.floor(clampNumber(old.rare,0,9999));record.tune=Math.floor(clampNumber(old.tune,0,2))}else{record.copies=Math.floor(clampNumber(old,0,9999));record.rare=Math.floor(clampNumber(raw.blueprints&&raw.blueprints[id+'Rare'],0,9999))}data.blueprints[id]=record;data.playtest.modulePicks[id]=Math.floor(clampNumber(oldPlaytest.modulePicks&&oldPlaytest.modulePicks[id],0,1e9))}
    for(const item of LOOT_ITEMS)data.lootFound[item.id]=Math.floor(clampNumber(raw.lootFound&&raw.lootFound[item.id],0,999999));
    data.starter=MODULES[raw.starter]&&data.blueprints[raw.starter].copies>0?raw.starter:null;data.version=SAVE_VERSION;return data;
  }
  function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save))}catch(e){}}

  function upgradePrice(type){let base=type==='chassis'?70:type==='weapon'?80:65;return Math.floor(base*Math.pow(1.6,save[type]||0))}
  function maxHp(){return 100+save.chassis*14}
  function shotDamage(){return Math.round((8+save.weapon*1.45)*10)/10}
  function magnetRange(){return 85+save.salvage*10}
  function schematicLevel(id){return Math.floor(clampNumber(save.schematics&&save.schematics[id],0,BOSS_SCHEMATICS[id].max))}
  function baseShields(){return schematicLevel('aegis')}
  function thermalBlast(level){return {charges:level>=3?2:level?1:0,damage:level?1+Math.max(0,level-1)*.25:1}}
  function schematicEffect(id,level){level=level==null?schematicLevel(id):level;if(id==='aegis')return '+'+level+' START SHIELD'+(level===1?'':'S');if(id==='thrusters')return '-'+level*6+'% DASH RECHARGE';if(id==='thermal')return level>=3?'DASH CHARGES 2 BLASTS  \u00B7  +50% DAMAGE':level===2?'DASH BLAST  \u00B7  +25% DAMAGE':'DASH CHARGES 1 BLAST';return '+'+level*5+'% LOOT VALUE'}
  function routeConfig(){return route?ROUTES[route]:null}
  function zoneAt(level){if(level<=2)return COMMON_ZONES[Math.max(0,level-1)];let config=routeConfig()||ROUTES.dynamo;return config.zones[Math.max(0,Math.min(2,level-3))]}
  function currentBoss(){let config=routeConfig()||ROUTES.dynamo;return BOSSES[config.boss]}
  function bossRewardOptions(){let ids=currentBoss().kind==='tyrant'?TYRANT_SCHEMATIC_IDS:WARDEN_SCHEMATIC_IDS,choices=ids.filter(id=>schematicLevel(id)<BOSS_SCHEMATICS[id].max);return choices.length?choices:['dividend']}
  function lootMultiplier(nextTier){let singularity=hasSynergy('singularity')?1.18:1,salvage=1+Math.min(.6,save.salvage*.035),recycler=1+schematicLevel('recycler')*.05,routeBonus=routeConfig()?routeConfig().scrap:1;return (1+(depth-1)*.11)*(1+(nextTier==null?riskTier:nextTier)*.32)*salvage*singularity*recycler*routeBonus}
  function lootGlyph(item){return item.form==='gear'?'\u2699':item.form==='coil'?'\u223F':item.form==='bolt'?'\u2020':item.form==='ring'?'\u25CE':item.form==='gauge'?'\u25D4':item.form==='lens'?'\u25C9':item.form==='core'?'\u2726':item.form==='canister'?'\u25A3':'\u25C6'}
  function lootRarityRoll(elite,minimum){
    let routeBonus=routeConfig()?routeConfig().lootRare:0,r=Math.random(),legendary=.0008+(depth-1)*.00008+riskTier*.00018+(elite?.0012:0)+routeBonus*.004,mythic=.008+(depth-1)*.0015+riskTier*.002+(elite?.02:0)+routeBonus*.04,epic=.045+(depth-1)*.008+riskTier*.012+(elite?.05:0)+routeBonus*.15,rare=.19+(depth-1)*.018+riskTier*.03+(elite?.1:0)+routeBonus,rarity=r<legendary?'legendary':r<legendary+mythic?'mythic':r<legendary+mythic+epic?'epic':r<legendary+mythic+epic+rare?'rare':'common';
    if(minimum&&LOOT_RARITIES[rarity].rank<LOOT_RARITIES[minimum].rank)rarity=minimum;return rarity
  }
  function rollLootItem(elite,minimum,forcedId){if(forcedId&&LOOT_BY_ID[forcedId])return LOOT_BY_ID[forcedId];let rarity=lootRarityRoll(elite,minimum),pool=LOOT_BY_RARITY[rarity];return pool[Math.floor(Math.random()*pool.length)]}
  function lootManifest(){return Object.values(lootBag).sort((a,b)=>LOOT_RARITIES[LOOT_BY_ID[b.id].rarity].rank-LOOT_RARITIES[LOOT_BY_ID[a.id].rarity].rank||b.value-a.value)}
  function bestLootEntry(){return lootManifest()[0]||null}
  function formatTime(seconds){seconds=Math.max(0,Math.floor(seconds||0));return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')}
  function depthForElapsed(time){let value=1;for(let i=1;i<DEPTH_THRESHOLDS.length;i++)if(time>=DEPTH_THRESHOLDS[i])value=i+1;return Math.min(5,value)}
  function zoneProgress(){if(depth>=5)return 1;let start=DEPTH_THRESHOLDS[depth-1],end=DEPTH_THRESHOLDS[depth];return Math.max(0,Math.min(1,(elapsed-start)/(end-start)))}
  function blueprintTier(id){let copies=save.blueprints[id].copies;return copies>=BLUEPRINT_THRESHOLDS[3]?3:copies>=BLUEPRINT_THRESHOLDS[2]?2:copies>=BLUEPRINT_THRESHOLDS[1]?1:0}
  function blueprintMark(tier){return tier===3?'MK III':tier===2?'MK II':tier===1?'MK I':'LOCKED'}
  function starterPowerAt(tier,tune){return tier?1+(tier-1)*.15+(tune||0)*.1:0}
  function starterPower(id){return starterPowerAt(blueprintTier(id),save.blueprints[id].tune)}
  function platingProtection(power){let shields=Math.floor(power+.0001);return {shields,armor:Math.min(.2,Math.max(0,power-shields)*.4)}}
  function starterEffect(id,power){
    if(!power)return 'RECOVER TO UNLOCK AS STARTER';
    if(id==='burst'){let shots=Math.floor(power+.0001),echo=Math.round((power-shots)*100);return '+'+shots+' VOLLEY SHOT'+(shots===1?'':'S')+(echo?'  \u00B7  '+echo+'% ECHO SHOT':'')}
    if(id==='magnet')return '+'+Math.round(power*48)+' MAGNET RANGE';
    if(id==='plating'){let protection=platingProtection(power),armor=Math.round(protection.armor*100);return '+'+protection.shields+' SHIELD'+(protection.shields===1?'':'S')+(armor?'  \u00B7  '+armor+'% ARMOR':'')}
    if(id==='overdrive')return '+'+Math.round(power*12)+'% MOVE  \u00B7  -'+Math.round(power*11)+'% FIRE DELAY';
    return '+'+Math.round(power*34)+'% DAMAGE  \u00B7  -'+Math.round(power*11)+'% MAX HP';
  }
  function blueprintGoal(tier){return BLUEPRINT_THRESHOLDS[Math.min(3,tier+1)]}
  function blueprintRecoveryText(record,tier){let shown=Math.min(record.copies,BLUEPRINT_THRESHOLDS[3]);if(tier===3)return shown+' / '+BLUEPRINT_THRESHOLDS[3]+' RECOVERED  \u00B7  COPY MASTERY COMPLETE';return shown+' / '+blueprintGoal(tier)+' RECOVERED  \u00B7  NEXT '+blueprintMark(tier+1)}
  function blueprintProgress(record,tier){let goal=blueprintGoal(tier);return tier===3?100:Math.min(100,record.copies/goal*100)}
  function tuneCost(id){let record=save.blueprints[id],tier=blueprintTier(id);return Math.floor(80*(record.tune+1)*(1+tier*.45))}
  function modulePower(id){return cargo.reduce((sum,m)=>sum+(m.id===id?(m.power||(m.rare?2:1)):0),0)}
  function activeSynergies(){return SYNERGIES.filter(s=>s.needs.every(id=>modulePower(id)>0))}
  function hasSynergy(id){return activeSynergies().some(s=>s.id===id)}
  function cargoStats(){let over=modulePower('overdrive'),volatile=modulePower('volatile'),plating=platingProtection(modulePower('plating')),flux=hasSynergy('flux'),kinetic=hasSynergy('kinetic'),dashBase=flux?1.55:2.2,dashTech=1-schematicLevel('thrusters')*.06;return {burst:Math.min(3,modulePower('burst')),magnet:modulePower('magnet')*48,shields:baseShields()+plating.shields,armor:plating.armor,speed:1+over*.12+(flux ? .07 : 0),fire:Math.max(.55,1-over*.11),damage:1+volatile*.34,hp:Math.max(.58,1-volatile*.11),dashCd:dashBase*dashTech,ram:kinetic?34+shotDamage()*1.2:0,shrapnel:hasSynergy('shrapnel'),counter:hasSynergy('counter'),flux}}
  function blueprintCount(){return MODULE_IDS.reduce((sum,id)=>sum+save.blueprints[id].copies,0)}
  function contractReady(){return save.cores>=3&&blueprintCount()>=12}
  function synergyForPickup(id){return SYNERGIES.find(s=>s.needs.includes(id)&&s.needs.some(other=>other!==id&&modulePower(other)>0))}

  function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(2,window.devicePixelRatio||1);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function setView(next){mode=next;ui.base.classList.toggle('active',next==='base');ui.expedition.classList.toggle('active',next==='run');setMusicMode(next);if(next==='run')requestAnimationFrame(()=>{resize();last=performance.now()})}
  function notice(text,tone){ui.notice.textContent=text;ui.notice.style.borderColor=tone||'';ui.notice.classList.add('show');clearTimeout(notice.t);notice.t=setTimeout(()=>ui.notice.classList.remove('show'),1700)}
  function runNotice(text,tone){ui.runNotice.textContent=text;ui.runNotice.style.borderColor=tone||'';ui.runNotice.classList.add('show');clearTimeout(runNotice.t);runNotice.t=setTimeout(()=>ui.runNotice.classList.remove('show'),1700)}
  function ensureAudio(){if(!save.settings.sound)return null;try{audio.ctx=audio.ctx||new (window.AudioContext||window.webkitAudioContext)();if(audio.ctx.state==='suspended')audio.ctx.resume();if(!audio.timer&&typeof window.setInterval==='function')audio.timer=window.setInterval(musicStep,420);return audio.ctx}catch(e){return null}}
  function tone(freq,duration,volume,type,slide,delay){let a=ensureAudio();if(!a)return;let o=a.createOscillator(),g=a.createGain(),t=a.currentTime+(delay||0);o.type=type||'triangle';o.frequency.setValueAtTime(Math.max(25,freq),t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(25,slide),t+duration*.85);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume||.02,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+duration+.02)}
  function musicStep(){if(!save.settings.sound||!audio.ctx)return;let sets=audio.mode==='boss'?[55,55,65,49,73,65,55,49]:audio.mode==='run'?[110,131,147,98,110,165,147,131]:[82,98,110,73,82,123,110,98],notes=sets[audio.step++%sets.length];tone(notes,audio.mode==='boss' ? .32 : .24,audio.mode==='boss' ? .012 : .008,'sine',notes*.998);if(audio.step%4===0)tone(notes*2,.12,.006,'triangle',notes*1.5,.06)}
  function setMusicMode(next){audio.mode=next==='run'?(bossActive?'boss':'run'):'base';if(audio.ctx)ensureAudio()}
  function sound(name){
    if(!save.settings.sound)return;ensureAudio();if(name==='shoot'){tone(250,.055,.018,'square',155);tone(620,.035,.009,'triangle',310)}else if(name==='hit'){tone(105,.06,.024,'square',65);tone(900,.035,.008,'sawtooth',320)}else if(name==='kill'){tone(145,.11,.025,'square',48);tone(520,.08,.012,'triangle',760,.025)}else if(name==='pickup'){tone(540,.08,.018,'triangle',790)}else if(name==='hurt'){tone(92,.2,.042,'sawtooth',38);tone(46,.24,.02,'square',35)}else if(name==='upgrade'){tone(330,.13,.02,'triangle',660);tone(495,.14,.015,'triangle',990,.08)}else if(name==='rare'){tone(660,.2,.025,'triangle',1320);tone(990,.24,.018,'sine',1480,.08)}else if(name==='legendary'){tone(330,.42,.035,'triangle',1320);tone(495,.38,.028,'sine',1480,.08);tone(660,.34,.022,'triangle',1760,.16)}else if(name==='boss'){tone(58,.34,.045,'sawtooth',31);tone(116,.28,.018,'square',55,.04)}else if(name==='shield'){tone(780,.12,.025,'sine',1280);tone(390,.15,.012,'triangle',910)}else if(name==='dash'){tone(180,.1,.018,'sawtooth',520)}else tone(150,.1,.018,'triangle',260)
  }

  function refreshBase(){
    ui.bank.textContent=Math.floor(save.scrap);ui.cores.textContent=save.cores;ui.best.textContent=save.best;ui.chassisLevel.textContent=save.chassis;ui.weaponLevel.textContent=save.weapon;ui.salvageLevel.textContent=save.salvage;ui.maxHp.textContent=maxHp();ui.damage.textContent=shotDamage();ui.magnet.textContent=magnetRange();
    for(const type of ['chassis','weapon','salvage']){let button=ui['upgrade'+type[0].toUpperCase()+type.slice(1)],cost=upgradePrice(type);ui[type+'Cost'].textContent=cost;button.disabled=save.scrap<cost}
    let secured=MODULE_IDS.reduce((sum,id)=>sum+save.blueprints[id].copies,0),upgrades=save.chassis+save.weapon+save.salvage;ui.scene.classList.toggle('evolved1',upgrades>=2||secured>=1);ui.scene.classList.toggle('evolved2',upgrades>=5||secured>=4);ui.scene.classList.toggle('evolved3',upgrades>=9||secured>=9);
    if(save.starter){ui.starterIcon.textContent=MODULES[save.starter].icon;ui.starterName.textContent=MODULES[save.starter].name.toUpperCase()+' '+blueprintMark(blueprintTier(save.starter))}else{ui.starterIcon.textContent='+';ui.starterName.textContent='NONE EQUIPPED'}
    let copies=blueprintCount(),corePart=Math.min(1,save.cores/3),copyPart=Math.min(1,copies/12),progress=(corePart+copyPart)*50;ui.contractReadout.textContent=Math.min(3,save.cores)+'/3 CORES · '+Math.min(12,copies)+'/12 BLUEPRINTS';ui.contractFill.style.width=progress+'%';ui.contractTracker.classList.toggle('complete',contractReady());ui.contractTitle.textContent=contractReady()?'LOWER VAULT ACCESS GRANTED':'BREACH THE LOWER VAULT';
  }
  function renderWardenSchematics(){
    ui.wardenTechGrid.innerHTML='';for(const id of SCHEMATIC_IDS){let def=BOSS_SCHEMATICS[id],level=schematicLevel(id),entry=document.createElement('article');entry.className='wardenTech'+(level?' recovered':'')+(id==='thermal'?' tyrantTech':'');entry.innerHTML='<i>'+def.icon+'</i><span><strong>'+def.name+'</strong><small>'+def.desc+'</small></span><em>'+(level?schematicEffect(id,level):'NOT RECOVERED')+'</em><b>RANK '+level+'/'+def.max+'</b>';ui.wardenTechGrid.appendChild(entry)}
  }
  function renderBlueprints(){
    ui.blueprintGrid.innerHTML='';ui.starterReadout.textContent=save.starter?MODULES[save.starter].name+' '+blueprintMark(blueprintTier(save.starter))+'  \u00B7  '+starterEffect(save.starter,starterPower(save.starter)):'No relic equipped';renderWardenSchematics();
    for(const id of MODULE_IDS){let def=MODULES[id],record=save.blueprints[id],tier=blueprintTier(id),unlocked=tier>0,entry=document.createElement('article');entry.className='blueprintEntry '+(unlocked?'unlocked':'locked')+(save.starter===id?' equipped':'');
      let power=starterPower(id),output=Math.round(power*100),nextPower=tier<3?starterPowerAt(tier+1,record.tune):power,nextText=tier<3?'NEXT OUTPUT  '+Math.round(nextPower*100)+'%  \u00B7  '+starterEffect(id,nextPower):'MAX COPY OUTPUT REACHED';entry.style.setProperty('--copy-progress',blueprintProgress(record,tier)+'%');entry.innerHTML='<i>'+def.icon+'</i><div class="blueprintHeading"><strong>'+def.name+'</strong><b>'+blueprintMark(tier)+'</b></div><p>'+def.desc+'</p><div class="blueprintOutput"><span>STARTER EFFECT <em>'+(unlocked?output+'% OUTPUT':'LOCKED')+'</em></span><b>'+starterEffect(id,power)+'</b></div><div class="copyTrack"><i></i></div><div class="blueprintRecovery"><span>'+blueprintRecoveryText(record,tier)+'</span><small>'+nextText+'</small></div><div class="blueprintMeta"><span>CALIBRATION '+record.tune+'/2  \u00B7  +'+record.tune*10+'% STARTER OUTPUT</span></div>';
      let actions=document.createElement('div');actions.className='benchActions';let equip=document.createElement('button');equip.className='equipButton';equip.textContent=save.starter===id?'UNEQUIP STARTER':'EQUIP STARTER';equip.title=unlocked?'Equip this relic in one cargo slot at the start of every expedition.':'Recover one copy before this can be equipped.';equip.disabled=!unlocked;equip.addEventListener('click',()=>equipStarter(save.starter===id?null:id));let tune=document.createElement('button');tune.className='tuneButton';let cost=tuneCost(id);tune.textContent=record.tune>=2?'CALIBRATION MAX':'CALIBRATE +10%  \u2B22 '+cost;tune.title='Spend workshop scrap to permanently add 10% starter output. Copy mastery and calibration stack.';tune.disabled=!unlocked||record.tune>=2||save.scrap<cost;tune.addEventListener('click',()=>tuneBlueprint(id));actions.append(equip,tune);entry.appendChild(actions);ui.blueprintGrid.appendChild(entry);
    }
    let extractRate=save.stats.runs?Math.round(save.stats.extractions/save.stats.runs*100)+'%':'0%',averageRun=save.stats.runs?formatTime(save.stats.totalTime/save.stats.runs):'0:00',stats=[['RUNS',save.stats.runs],['EXTRACT RATE',extractRate],['BOSSES',save.stats.bosses],['AVG RUN',averageRun]];ui.careerStats.innerHTML='';for(const pair of stats){let d=document.createElement('div');d.innerHTML='<span>'+pair[0]+'</span><b>'+pair[1]+'</b>';ui.careerStats.appendChild(d)}
  }
  function openBlueprints(){renderBlueprints();ui.blueprintOverlay.classList.add('show')}
  function closeBlueprints(){ui.blueprintOverlay.classList.remove('show');refreshBase()}
  function equipStarter(id){save.starter=id;persist();renderBlueprints();refreshBase();sound('pickup')}
  function tuneBlueprint(id){let record=save.blueprints[id],cost=tuneCost(id);if(blueprintTier(id)<1||record.tune>=2||save.scrap<cost)return;save.scrap-=cost;record.tune++;persist();refreshBase();renderBlueprints();notice(MODULES[id].name.toUpperCase()+' TUNED','#f2c14f');sound('upgrade')}

  function requestStart(){if(!save.seenIntro)ui.briefingOverlay.classList.add('show');else startRun()}
  function completeBriefing(){save.seenIntro=true;persist();ui.briefingOverlay.classList.remove('show');startRun()}
  function updateBuildHud(){let active=activeSynergies();ui.buildName.textContent=active.length?active.map(s=>s.name).join(' + '):cargo.length?'FIELD RIG':'EMPTY RIG';ui.buildHud.classList.toggle('active',active.length>0)}
  function updateZoneHud(){let zone=zoneAt(depth);ui.zoneDepth.textContent='DEPTH '+depth+' \u00B7 '+zone.threat;ui.zoneName.textContent=zone.name;ui.zoneHud.classList.toggle('boss',bossActive)}
  function updateCargoHud(){ui.cargoSlots.innerHTML='';for(let i=0;i<3;i++){let slot=document.createElement('div'),m=cargo[i],power=m?Math.round((m.power||1)*100)/100:0;slot.className='cargoSlot'+(m?' filled':'')+(m&&m.rareRecoveries?' rare':'')+(power>1?' fused':'');if(m)slot.innerHTML='<span>'+MODULES[m.id].icon+'</span>'+(power>1?'<b class="cargoRank">'+power.toFixed(power%1?1:0)+'</b>':'');else slot.textContent='\u00B7';slot.title=m?(m.starter?'Starter ':'')+MODULES[m.id].name+' \u00B7 Power '+power:'Empty relic slot';ui.cargoSlots.appendChild(slot)}updateBuildHud()}
  function applyCargoEffects(newModule){if(!player)return;let oldMax=player.maxHp||maxHp(),stats=cargoStats();player.maxHp=Math.max(40,Math.floor(maxHp()*stats.hp));player.hp=Math.min(player.maxHp,Math.max(1,player.hp*(player.maxHp/oldMax)));if(newModule&&newModule.id==='plating')player.shields=Math.min(stats.shields,(player.shields||0)+Math.max(1,Math.floor(newModule.power||(newModule.rare?2:1))));else player.shields=Math.min(stats.shields,player.shields||0);if(stats.burst<=0)player.burstCharge=0;updateCargoHud();updateHud()}
  function startRun(){
    cargo=[];if(save.starter)cargo.push({id:save.starter,rare:false,starter:true,power:starterPower(save.starter),recoveries:0,rareRecoveries:0});
    player={x:WORLD.w/2,y:WORLD.h/2,r:18,hp:maxHp(),maxHp:maxHp(),speed:235,fire:0,inv:0,angle:0,dashCd:0,dashTime:0,dashX:1,dashY:0,lastX:1,lastY:0,shields:baseShields(),recoil:0,volley:0,burstCharge:0,thermalCharges:0,ramHits:new Set()};
    enemies=[];bullets=[];enemyBullets=[];lootDrops=[];particles=[];effects=[];hazards=[];decor=[];caches=[];lootBag={};elapsed=0;runTime=0;spawnClock=.5;hazardClock=3.5;runScrap=0;depth=1;riskTier=0;decision=false;routeDecision=false;route=null;moduleDecision=false;depthPulse=0;extracting=0;shake=0;flash=0;paused=false;bossActive=false;bossDefeated=false;bossEntity=null;pendingWardenReward=null;zoneEventTriggered=false;runStats={damage:0,kills:0,elites:0,risks:0,items:0,legendary:0,modules:[],warden:null,route:null,boss:null};
    for(let i=0;i<78;i++)decor.push({x:80+Math.random()*(WORLD.w-160),y:80+Math.random()*(WORLD.h-160),r:8+Math.random()*24,type:Math.floor(Math.random()*4),rot:Math.random()*6});for(let i=0;i<8;i++){let pool=LOOT_BY_RARITY.common;spawnLoot(100+Math.random()*(WORLD.w-200),100+Math.random()*(WORLD.h-200),pool[Math.floor(Math.random()*pool.length)],false)}
    spawnCache(player.x+190,player.y+25,false,false);ui.extractOverlay.classList.remove('show');ui.riskOverlay.classList.remove('show');ui.routeOverlay.classList.remove('show');ui.moduleOverlay.classList.remove('show');ui.resultOverlay.classList.remove('show');ui.lootToast.classList.remove('show','legendary');ui.bossHud.classList.remove('show','tyrant');ui.cargoHud.classList.remove('bossHidden');ui.depthRoute.classList.remove('bossHidden','furnace','dynamo');ui.expedition.classList.remove('legendaryCargo');ui.extract.classList.remove('hotLoot');ui.routeLabel.textContent='TOWER';ui.settingsOverlay.classList.remove('show');setView('run');applyCargoEffects(cargo[0]);updateCargoHud();updateZoneHud();updateRouteHud();updateHud();save.stats.runs++;persist();runNotice(save.starter?MODULES[save.starter].name.toUpperCase()+' ONLINE':COMMON_ZONES[0].name,COMMON_ZONES[0].accent);sound('start')
  }

  function showResult(survived,scrapAmount,reached,modules,newRecord,status,fieldData){
    fieldData=fieldData||{time:0,kills:0,damage:0,risks:0,items:0,loot:[]};ui.resultPanel.classList.toggle('lost',!survived);ui.resultTitle.textContent=status||(survived?'CARGO SECURED':'CARGO LOST');ui.resultScrap.textContent=survived?scrapAmount:'0';ui.resultDepth.textContent=reached;ui.resultTime.textContent=formatTime(fieldData.time);ui.resultKills.textContent=fieldData.kills;ui.resultDamage.textContent=fieldData.damage;ui.resultRisk.textContent=fieldData.risks;ui.resultItems.textContent=fieldData.items||0;ui.resultRecord.textContent=newRecord?'NEW DEPTH RECORD':'';ui.resultLoot.innerHTML='';ui.resultModules.innerHTML='';
    for(const entry of (fieldData.loot||[]).slice(0,8)){let item=LOOT_BY_ID[entry.id],rarity=LOOT_RARITIES[item.rarity],chip=document.createElement('span');chip.className='lootResult'+(survived?'':' lost');chip.style.setProperty('--loot-color',rarity.color);chip.innerHTML='<i>'+lootGlyph(item)+'</i><span>'+item.name+(entry.count>1?' x'+entry.count:'')+'</span><b>'+entry.value+'</b>';ui.resultLoot.appendChild(chip)}
    let recovered=modules.filter(m=>!m.starter),reward=fieldData.wardenReward;if(reward){let chip=document.createElement('span');chip.className='resultModule wardenReward'+(survived?'':' lost');chip.textContent=reward==='dividend'?'CORE DIVIDEND  +'+CORE_DIVIDEND+' SCRAP':'BOSS SCHEMATIC  '+BOSS_SCHEMATICS[reward].name.toUpperCase()+(survived?'  RANK '+fieldData.wardenRank:' LOST');ui.resultModules.appendChild(chip)}if(fieldData.route){let routeChip=document.createElement('span');routeChip.className='resultModule routeReward';routeChip.textContent=ROUTES[fieldData.route].name;ui.resultModules.appendChild(routeChip)}if(!recovered.length&&!reward){let empty=document.createElement('span');empty.className='resultModule';empty.textContent=survived?'No relics recovered':'Relics lost';ui.resultModules.appendChild(empty)}for(const m of recovered){let chip=document.createElement('span'),power=Math.round((m.power||1)*10)/10;chip.className='resultModule'+(survived?'':' lost');chip.textContent=MODULES[m.id].name+(power>1?'  POWER '+power:'');ui.resultModules.appendChild(chip)}ui.resultOverlay.classList.add('show');
  }
  function returnBase(survived,status){
    let dividend=survived&&pendingWardenReward==='dividend'?CORE_DIVIDEND:0,reportScrap=runScrap+dividend,reportDepth=depth,reportCargo=cargo.map(m=>Object.assign({},m)),reportLoot=lootManifest().map(entry=>Object.assign({},entry)),itemCount=reportLoot.reduce((sum,entry)=>sum+entry.count,0),legendaryCount=reportLoot.reduce((sum,entry)=>sum+(LOOT_BY_ID[entry.id].rarity==='legendary'?entry.count:0),0),reportData={time:Math.round(runTime),kills:runStats?runStats.kills:0,damage:runStats?Math.round(runStats.damage):0,risks:riskTier,items:itemCount,legendary:legendaryCount,loot:reportLoot,route,wardenReward:pendingWardenReward,wardenRank:0},newRecord=survived&&depth>save.best,securedCore=survived&&bossDefeated,wasComplete=save.contractComplete;if(survived){if(BOSS_SCHEMATICS[pendingWardenReward]){let def=BOSS_SCHEMATICS[pendingWardenReward];save.schematics[pendingWardenReward]=Math.min(def.max,schematicLevel(pendingWardenReward)+1);reportData.wardenRank=save.schematics[pendingWardenReward]}save.scrap+=reportScrap;save.best=Math.max(save.best,depth);save.bestRisk=Math.max(save.bestRisk,riskTier);save.stats.extractions++;save.stats.totalScrap+=reportScrap;save.stats.itemsRecovered+=itemCount;save.stats.legendaryRecovered+=legendaryCount;if(securedCore)save.cores++;for(const entry of reportLoot)save.lootFound[entry.id]=(save.lootFound[entry.id]||0)+entry.count;for(const m of cargo){if(m.starter&&!m.recoveries)continue;let record=save.blueprints[m.id],recoveries=Math.max(0,Math.floor(m.recoveries||0));record.copies+=recoveries;record.rare+=Math.max(0,Math.floor(m.rareRecoveries||0))}save.contractComplete=contractReady();notice('+'+reportScrap+' LOOT SECURED','#47c5b6')}else{save.stats.losses++;notice(runScrap+' LOOT LOST','#ef5350')}save.stats.totalTime+=reportData.time;save.stats.totalKills+=reportData.kills;save.stats.totalDamage+=reportData.damage;save.stats.totalRisks+=reportData.risks;for(const id of runStats&&runStats.modules||[])save.playtest.modulePicks[id]=(save.playtest.modulePicks[id]||0)+1;save.playtest.runs.push({outcome:survived?'secured':'lost',depth:reportDepth,time:reportData.time,scrap:survived?reportScrap:0,kills:reportData.kills,damage:reportData.damage,risks:reportData.risks,items:itemCount,legendary:legendaryCount,route,warden:pendingWardenReward});save.playtest.runs=save.playtest.runs.slice(-12);persist();
    decision=false;routeDecision=false;moduleDecision=false;extracting=0;bossActive=false;paused=false;stick.active=false;stick.x=stick.y=0;ui.knob.style.transform='';ui.riskOverlay.classList.remove('show');ui.routeOverlay.classList.remove('show');ui.moduleOverlay.classList.remove('show');ui.extractOverlay.classList.remove('show');ui.lootToast.classList.remove('show','legendary');ui.bossHud.classList.remove('show','tyrant');ui.cargoHud.classList.remove('bossHidden');ui.depthRoute.classList.remove('bossHidden');ui.expedition.classList.remove('legendaryCargo');ui.extract.classList.remove('hotLoot');ui.settingsOverlay.classList.remove('show');setView('base');refreshBase();showResult(survived,reportScrap,reportDepth,reportCargo,newRecord,status,reportData)
    let records=[];if(newRecord)records.push('NEW DEPTH RECORD');if(survived&&legendaryCount)records.push(legendaryCount+' LEGENDARY SECURED');if(!survived&&legendaryCount)records.push(legendaryCount+' LEGENDARY LOST');if(securedCore)records.push('BOSS CORE SECURED');if(survived&&pendingWardenReward)records.push(pendingWardenReward==='dividend'?'CORE DIVIDEND SECURED':'SCHEMATIC SECURED');if(!wasComplete&&save.contractComplete)records.push('CONTRACT COMPLETE');ui.resultRecord.textContent=records.join(' \u00B7 ');pendingWardenReward=null
  }
  function closeResultPanel(){ui.resultOverlay.classList.remove('show');if(save.contractComplete&&!save.contractSeen)ui.contractOverlay.classList.add('show')}
  function claimContract(){save.contractSeen=true;persist();ui.contractOverlay.classList.remove('show');refreshBase();sound('rare')}
  function beginExtract(){if(mode!=='run'||extracting||decision||routeDecision||moduleDecision||paused)return;extracting=3.25;ui.extractOverlay.classList.add('show');runNotice('KEEP MOVING UNTIL EXTRACTION','#47c5b6');sound('pickup')}
  function cancelExtract(){extracting=0;ui.extractOverlay.classList.remove('show')}
  function showRiskDecision(){let best=bestLootEntry();decision=true;ui.riskScrap.textContent=runScrap;ui.riskBest.textContent=best?LOOT_BY_ID[best.id].name:'None';ui.riskBest.style.color=best?LOOT_RARITIES[LOOT_BY_ID[best.id].rarity].color:'';ui.nextMultiplier.textContent='x'+lootMultiplier(riskTier+1).toFixed(2);ui.riskOverlay.classList.add('show');sound('upgrade')}
  function pushDeeper(){if(!decision)return;decision=false;riskTier++;if(runStats)runStats.risks++;ui.riskOverlay.classList.remove('show');depthPulse=1.15;spawnEnemy(true);for(let i=0;i<Math.min(4,1+riskTier);i++)spawnEnemy(false,'rusher');shake=Math.max(shake,7);runNotice('RISK MULTIPLIER INCREASED','#f2c14f');sound('start');updateHud()}
  function extractFromRisk(){if(!decision)return;decision=false;ui.riskOverlay.classList.remove('show');beginExtract()}
  function showRouteDecision(){routeDecision=true;ui.routeOverlay.classList.add('show');runNotice('TOWER JUNCTION REACHED','#f2c14f');sound('upgrade')}
  function chooseRoute(id){if(!routeDecision||!ROUTES[id])return;route=id;routeDecision=false;if(runStats)runStats.route=id;ui.routeOverlay.classList.remove('show');ui.depthRoute.classList.remove('furnace','dynamo');ui.depthRoute.classList.add(id);ui.routeLabel.textContent=ROUTES[id].short;enterDepth(3);runNotice(ROUTES[id].name,zoneAt(3).accent);sound('start')}
  function enterDepth(nextDepth){depth=nextDepth;zoneEventTriggered=false;hazards=[];hazardClock=2.2;depthPulse=1.15;fieldRepair(depth===5?.2:.15);sound('upgrade');updateZoneHud();updateRouteHud();if(depth===5){startBoss();updateHud();return}let zone=zoneAt(depth),a=Math.random()*Math.PI*2,d=300+Math.random()*180,rareChance=.15+depth*.06+(routeConfig()?routeConfig().relicRare:0);runNotice(zone.name,zone.accent);spawnCache(Math.max(40,Math.min(WORLD.w-40,player.x+Math.cos(a)*d)),Math.max(40,Math.min(WORLD.h-40,player.y+Math.sin(a)*d)),depth>=3&&Math.random()<rareChance,false);if(!extracting&&depth%2===0){showRiskDecision();updateHud()}}
  function tryDash(){if(mode!=='run'||decision||routeDecision||moduleDecision||paused||!player||player.dashCd>0)return;let move=movement(),dx=move.x||player.lastX||Math.cos(player.angle),dy=move.y||player.lastY||Math.sin(player.angle),l=Math.hypot(dx,dy)||1,stats=cargoStats(),thermal=schematicLevel('thermal'),blast=thermalBlast(thermal);player.dashX=dx/l;player.dashY=dy/l;player.dashTime=.16;player.dashCd=stats.dashCd;player.ramHits=new Set();player.inv=Math.max(player.inv,stats.ram ? .34 : .24);if(thermal)player.thermalCharges=Math.max(player.thermalCharges||0,blast.charges);shake=Math.max(shake,3);burst(player.x,player.y,thermal?'#ff8b54':stats.ram?'#f2c14f':'#47c5b6',thermal?16:10,thermal?1.1:.8);sound('dash')}

  function spawnEnemy(elite,forcedType){
    if(enemies.length>=LIMITS.enemies)return;let x=player.x,y=player.y;for(let tries=0;tries<8;tries++){let a=Math.random()*Math.PI*2,d=500+Math.random()*250;x=Math.max(35,Math.min(WORLD.w-35,player.x+Math.cos(a)*d));y=Math.max(35,Math.min(WORLD.h-35,player.y+Math.sin(a)*d));if(Math.hypot(x-player.x,y-player.y)>370)break}
    let zone=zoneAt(depth),type=forcedType||zone.pool[Math.floor(Math.random()*zone.pool.length)],base=type==='brute'?{r:24,hp:46,speed:50,damage:16}:type==='shooter'?{r:17,hp:23,speed:68,damage:9}:type==='lancer'?{r:16,hp:27,speed:78,damage:14}:{r:15,hp:16,speed:108,damage:10},scale=1+(depth-1)*.13+riskTier*.1,entity={x,y,r:base.r*(elite?1.18:1),hp:base.hp*scale*(elite?2.05:1),max:base.hp*scale*(elite?2.05:1),speed:base.speed*(1+depth*.014)*(elite?1.05:1),damage:base.damage*(elite?1.28:1),hit:0,attack:0,fire:.8+Math.random(),charge:0,dashTime:0,dashX:0,dashY:0,type,elite:!!elite,angle:0,strafe:Math.random()<.5?-1:1,anim:0};enemies.push(entity);return entity
  }
  function triggerZoneEvent(){if(zoneEventTriggered||depth>=5)return;zoneEventTriggered=true;let zone=zoneAt(depth),type=zone.pool[zone.pool.length-1],elite=spawnEnemy(true,type);if(elite)elite.eventReward=3+depth*2;spawnEnemy(false);if(depth>1)spawnEnemy(false);shake=Math.max(shake,4);runNotice('PRIORITY SALVAGE SIGNAL',zone.accent);sound('start')}
  function startBoss(){
    let def=currentBoss(),isTyrant=def.kind==='tyrant';bossActive=true;extracting=0;hazards=[];ui.extractOverlay.classList.remove('show');enemies=[];enemyBullets=[];let a=Math.random()*Math.PI*2,x=Math.max(90,Math.min(WORLD.w-90,player.x+Math.cos(a)*410)),y=Math.max(90,Math.min(WORLD.h-90,player.y+Math.sin(a)*410)),hp=(620+riskTier*120+Math.min(540,save.weapon*18))*(isTyrant?1.08:1);bossEntity={x,y,r:isTyrant?54:48,hp,max:hp,speed:isTyrant?39:44,damage:(isTyrant?20:18)+riskTier*1.5,hit:0,attack:0,fire:1.3,charge:0,dashTime:0,type:'boss',boss:true,bossKind:def.kind,elite:true,angle:0,strafe:1,phase:0,bossStage:1,pattern:0,anim:0};enemies.push(bossEntity);if(runStats)runStats.boss=def.kind;ui.bossHud.classList.add('show');ui.bossHud.classList.toggle('tyrant',isTyrant);ui.bossName.textContent=def.name;ui.cargoHud.classList.add('bossHidden');ui.depthRoute.classList.add('bossHidden');ui.bossHealthFill.style.width='100%';ui.bossPhase.textContent=def.phase[0];depthPulse=1.2;shake=Math.max(shake,10);updateZoneHud();setMusicMode('run');runNotice(def.name+' ENGAGED',def.accent);sound('boss')
  }
  function setBossStage(e,stage){if(e.bossStage===stage)return;e.bossStage=stage;e.charge=0;e.fire=.55;enemyBullets=[];hazards=[];let def=BOSSES[e.bossKind]||currentBoss(),label=def.phase[stage-1];ui.bossPhase.textContent=label;runNotice(label,def.accent);effects.push({x:e.x,y:e.y,r:10,maxR:150,life:.7,max:.7,color:e.bossKind==='tyrant'?'#ff7a3d':stage===2?'#f2c14f':'#ef5350'});shake=Math.max(shake,9);sound('boss')}
  function defeatBoss(e){let def=BOSSES[e.bossKind]||currentBoss(),trophy=rollLootItem(true,'epic');bossActive=false;bossDefeated=true;bossEntity=null;save.stats.bosses++;persist();ui.bossHud.classList.remove('show');ui.cargoHud.classList.remove('bossHidden');ui.depthRoute.classList.remove('bossHidden');enemyBullets=[];hazards=[];for(const other of enemies)if(other!==e)other.dead=true;burst(e.x,e.y,def.accent,42,2);effects.push({x:e.x,y:e.y,r:18,maxR:210,life:1,max:1,color:def.accent});shake=Math.max(shake,14);flash=.06;setMusicMode('run');updateZoneHud();sound('rare');runNotice(def.name+' DOWN  \u00B7  TROPHY DROPPED','#f2c14f');spawnLoot(player.x,player.y,trophy,false);spawnCache(player.x,player.y,true,true)}
  function spawnLoot(x,y,item,scatter){if(lootDrops.length>=LIMITS.loot||!item)return;let rank=LOOT_RARITIES[item.rarity].rank;lootDrops.push({x:x+(scatter?(Math.random()-.5)*26:0),y:y+(scatter?(Math.random()-.5)*26:0),r:7+rank*1.4,item,spin:Math.random()*6,vx:scatter?(Math.random()-.5)*105:0,vy:scatter?(Math.random()-.5)*105:0})}
  function showLootToast(item,value){
    let rarity=LOOT_RARITIES[item.rarity];ui.lootToast.style.setProperty('--loot-color',rarity.color);ui.lootToastIcon.textContent=lootGlyph(item);ui.lootToastRarity.textContent=rarity.name+' LOOT';ui.lootToastName.textContent=item.name;ui.lootToastValue.textContent='+'+value;ui.lootToast.classList.toggle('legendary',item.rarity==='legendary');ui.lootToast.classList.remove('show');void ui.lootToast.offsetWidth;ui.lootToast.classList.add('show');clearTimeout(showLootToast.t);showLootToast.t=setTimeout(()=>ui.lootToast.classList.remove('show'),item.rarity==='legendary'?4200:1900)
  }
  function collectLoot(drop){
    let item=drop.item,rarity=LOOT_RARITIES[item.rarity],value=Math.max(1,Math.ceil(item.value*lootMultiplier())),entry=lootBag[item.id]||(lootBag[item.id]={id:item.id,count:0,value:0});entry.count++;entry.value+=value;runScrap+=value;if(runStats){runStats.items++;if(item.rarity==='legendary')runStats.legendary++}if(rarity.rank>=1)showLootToast(item,value);if(item.rarity==='legendary'){ui.expedition.classList.add('legendaryCargo');ui.extract.classList.add('hotLoot');shake=Math.max(shake,8);flash=.045;burst(drop.x,drop.y,rarity.color,34,1.8);sound('legendary')}else{burst(drop.x,drop.y,rarity.color,rarity.rank>=2?16:6,rarity.rank>=2?1:.5);sound(rarity.rank>=2?'rare':'pickup')}updateHud()
  }
  function spawnCache(x,y,rare,bossReward){caches.push({x,y,r:19,rare:!!rare,bossReward:!!bossReward,spin:Math.random()*6,opened:false})}
  function burst(x,y,color,count,power){if(!save.settings.particles)return;count=Math.min(count,LIMITS.particles-particles.length);for(let i=0;i<count;i++){let a=Math.random()*Math.PI*2,s=(20+Math.random()*80)*(power||1);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.35,max:.6,r:1.5+Math.random()*3,color})}}
  function impact(x,y,color,power){burst(x,y,color,Math.round(5+(power||1)*5),.55+(power||1)*.2);effects.push({x,y,r:3,maxR:20+(power||1)*10,life:.18,max:.18,color})}

  function randomModule(exclude,forceRare){let pool=MODULE_IDS.filter(id=>!exclude.includes(id)&&(!cargo.find(m=>m.id===id)||(cargo.find(m=>m.id===id).power||1)<RELIC_POWER_CAP));if(!pool.length)pool=MODULE_IDS.filter(id=>!exclude.includes(id));let id=pool[Math.floor(Math.random()*pool.length)],routeRare=routeConfig()?routeConfig().relicRare:0;return {id,rare:!!forceRare||Math.random()<Math.min(.07+depth*.03+routeRare,.34)}}
  function prepareRelic(module){let gain=module.gain||module.power||(module.rare?2:1);return {id:module.id,rare:!!module.rare,power:Math.min(RELIC_POWER_CAP,gain),recoveries:Math.max(1,module.recoveries||1),rareRecoveries:Math.max(module.rare?1:0,module.rareRecoveries||0)}}
  function fuseRelic(existing,pickup){let before=existing.power||1;existing.power=Math.min(RELIC_POWER_CAP,before+(pickup.power||1));existing.recoveries=(existing.recoveries||0)+Math.max(1,pickup.recoveries||1);existing.rareRecoveries=(existing.rareRecoveries||0)+(pickup.rareRecoveries||0);existing.rare=existing.rare||pickup.rare;return existing.power>before}
  function openModuleCache(cache){if(moduleDecision)return;if(cache.bossReward){openWardenReward(cache);return}moduleDecision=true;activeCache=cache;moduleStage='offer';let first=randomModule([],cache.rare),second=randomModule([first.id],false);moduleOffer=[first,second];renderModuleOffer();ui.moduleOverlay.classList.add('show');sound(cache.rare?'rare':'upgrade')}
  function moduleCard(module,onClick,replacement){let def=MODULES[module.id],existing=!replacement&&cargo.find(m=>m.id===module.id),gain=module.rare?2:1,next=existing?Math.min(RELIC_POWER_CAP,(existing.power||1)+gain):gain,combo=!existing&&!replacement&&synergyForPickup(module.id),button=document.createElement('button');button.className='moduleCard'+(module.rare?' rare':'')+(combo?' synergy':'')+(existing?' fusion':'');let tag=replacement?'INSTALLED \u00B7 POWER '+Math.round((module.power||1)*10)/10:existing?((existing.power||1)>=RELIC_POWER_CAP?'POWER MAX':'FUSE \u00B7 POWER '+Math.round((existing.power||1)*10)/10+' \u2192 '+next):combo?'COMBO \u00B7 '+combo.name:module.rare?'RARE \u00B7 +2 POWER':'RELIC \u00B7 +1 POWER';button.innerHTML='<i class="moduleIcon">'+def.icon+'</i><strong>'+def.name+'</strong><span>'+def.desc+'</span><em>'+tag+'</em>';button.addEventListener('click',onClick);return button}
  function wardenRewardCard(id){let button=document.createElement('button');button.className='moduleCard wardenCard'+(id==='thermal'?' tyrantCard':'');if(id==='dividend'){button.innerHTML='<i class="moduleIcon">\u2B22</i><strong>Core Dividend</strong><span>All route schematics mastered. Convert the recovered core data into secured workshop scrap.</span><em>PERMANENT \u00B7 +'+CORE_DIVIDEND+' SCRAP</em>'}else{let def=BOSS_SCHEMATICS[id],level=schematicLevel(id);button.innerHTML='<i class="moduleIcon">'+def.icon+'</i><strong>'+def.name+'</strong><span>'+def.desc+'</span><em>PERMANENT \u00B7 RANK '+level+' \u2192 '+(level+1)+' \u00B7 '+schematicEffect(id,level+1)+'</em>'}button.addEventListener('click',()=>chooseWardenReward(id));return button}
  function openWardenReward(cache){let def=currentBoss(),options=bossRewardOptions();moduleDecision=true;activeCache=cache;moduleStage='warden';pendingModule=null;ui.moduleEyebrow.textContent=def.name+' CORE BREACHED';ui.moduleTitle.textContent='CHOOSE A PERMANENT SCHEMATIC';ui.moduleSkip.hidden=true;ui.moduleChoices.classList.add('wardenChoices');ui.moduleChoices.classList.toggle('soloChoice',options.length===1);ui.moduleChoices.innerHTML='';for(const id of options)ui.moduleChoices.appendChild(wardenRewardCard(id));ui.moduleOverlay.classList.add('show');sound('rare')}
  function chooseWardenReward(id){if(moduleStage!=='warden')return;pendingWardenReward=id;if(runStats)runStats.warden=id;moduleDecision=false;moduleStage='offer';activeCache=null;ui.moduleSkip.hidden=false;ui.moduleChoices.classList.remove('wardenChoices');ui.moduleOverlay.classList.remove('show');runNotice(id==='dividend'?'CORE DIVIDEND READY':BOSS_SCHEMATICS[id].name.toUpperCase()+' READY','#f2c14f');setTimeout(()=>beginExtract(),220);sound('rare')}
  function renderModuleOffer(){moduleStage='offer';pendingModule=null;ui.moduleEyebrow.textContent='RELIC CACHE';ui.moduleTitle.textContent='CHOOSE A RELIC';ui.moduleSkip.hidden=false;ui.moduleChoices.classList.remove('wardenChoices','soloChoice');ui.moduleSkip.textContent='LEAVE IT';ui.moduleChoices.innerHTML='';for(const m of moduleOffer)ui.moduleChoices.appendChild(moduleCard(m,()=>chooseModule(m)))}
  function chooseModule(module){let pickup=prepareRelic(module),existing=cargo.find(m=>m.id===pickup.id);pendingModule=pickup;if(existing){let increased=fuseRelic(existing,pickup);pendingModule=existing;applyCargoEffects(existing);finishModuleChoice(increased);return}if(cargo.length<3){cargo.push(pickup);applyCargoEffects(pickup);finishModuleChoice(false);return}moduleStage='replace';ui.moduleEyebrow.textContent='RELIC RACK FULL';ui.moduleTitle.textContent='REPLACE WHICH RELIC?';ui.moduleSkip.textContent='BACK';ui.moduleChoices.innerHTML='';cargo.forEach((m,index)=>ui.moduleChoices.appendChild(moduleCard(m,()=>replaceModule(index),true)))}
  function replaceModule(index){cargo[index]=pendingModule;applyCargoEffects(pendingModule);finishModuleChoice(false)}
  function finishModuleChoice(fused){let chosen=pendingModule;moduleDecision=false;pendingModule=null;activeCache=null;ui.moduleOverlay.classList.remove('show');if(chosen){if(runStats)runStats.modules.push(chosen.id);runNotice(MODULES[chosen.id].name.toUpperCase()+(fused?' FUSED \u00B7 POWER '+Math.round((chosen.power||1)*10)/10:' INSTALLED'),fused||chosen.rare?'#8f9dff':'#47c5b6')}sound(fused?'rare':'pickup')}
  function skipModule(){if(moduleStage==='warden')return;if(moduleStage==='replace'){renderModuleOffer();return}finishModuleChoice()}

  function movement(){let x=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0)+stick.x,y=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0)+stick.y,l=Math.hypot(x,y);return l>.05?{x:x/l,y:y/l}:{x:0,y:0}}
  function nearestEnemy(range){let best=null,dist=range*range;for(const e of enemies){let dx=e.x-player.x,dy=e.y-player.y,d=dx*dx+dy*dy;if(d<dist){dist=d;best=e}}return best}
  function counterBurst(){let damage=shotDamage()*.72;for(let i=0;i<8&&bullets.length<LIMITS.bullets;i++){let a=i*Math.PI/4;bullets.push({x:player.x,y:player.y,vx:Math.cos(a)*470,vy:Math.sin(a)*470,r:5,life:.72,damage,color:'#7ff4e6'})}effects.push({x:player.x,y:player.y,r:6,maxR:54,life:.28,max:.28,color:'#7ff4e6'})}
  function fieldRepair(fraction){if(!player||player.hp>=player.maxHp)return 0;let amount=Math.min(player.maxHp-player.hp,Math.ceil(player.maxHp*fraction));player.hp+=amount;effects.push({x:player.x,y:player.y,r:8,maxR:52,life:.45,max:.45,color:'#47c5b6'});burst(player.x,player.y,'#47c5b6',12,.7);return amount}
  function damagePlayer(amount){if(player.inv>0)return false;let stats=cargoStats();if(player.shields>0){player.shields--;player.inv=.35;shake=Math.max(shake,4);burst(player.x,player.y,'#47c5b6',18,1.1);if(stats.counter)counterBurst();sound('shield');updateHud();return false}amount=Math.max(1,amount*(1-stats.armor));let applied=Math.min(player.hp,amount);player.hp-=amount;if(runStats)runStats.damage+=applied;player.inv=.6;shake=Math.max(shake,9);flash=.12;burst(player.x,player.y,'#ef5350',12,1);effects.push({x:player.x,y:player.y,r:5,maxR:42,life:.25,max:.25,color:'#ef5350'});sound('hurt');if(player.hp<=0){player.hp=0;updateHud();returnBase(false,'RIG DESTROYED');return true}return false}
  function burstVolleyBonus(power,rig){rig=rig||player;let shots=Math.floor(power+.0001),echo=Math.max(0,power-shots);rig.burstCharge=(rig.burstCharge||0)+echo;if(rig.burstCharge>=.9999){shots++;rig.burstCharge-=1}return Math.min(3,shots)}
  function fireAt(target){let dx=target.x-player.x,dy=target.y-player.y,l=Math.hypot(dx,dy)||1,nx=dx/l,ny=dy/l,stats=cargoStats(),thermal=player.thermalCharges>0,blast=thermalBlast(schematicLevel('thermal'));player.angle=Math.atan2(dy,dx);player.fire=Math.max(.13,Math.max(.22,.5-save.weapon*.014)*stats.fire);player.recoil=.11;player.volley++;let count=1+burstVolleyBonus(stats.burst),explosive=thermal||(stats.shrapnel&&player.volley%3===0),damageBoost=thermal?blast.damage:1;if(thermal)player.thermalCharges--;for(let i=0;i<count&&bullets.length<LIMITS.bullets;i++){let spread=(i-(count-1)/2)*.12,cs=Math.cos(spread),sn=Math.sin(spread),vx=nx*cs-ny*sn,vy=nx*sn+ny*cs;bullets.push({x:player.x+vx*24,y:player.y+vy*24,vx:vx*520,vy:vy*520,r:explosive?6:5,life:1.1,damage:shotDamage()*stats.damage*damageBoost,explosive,color:thermal?'#ff6b35':explosive?'#ff8b54':'#f2c14f'})}sound('shoot')}
  function enemyShot(e,angle,speed,damage,kind,turn){if(enemyBullets.length>=LIMITS.enemyBullets)return;enemyBullets.push({x:e.x+Math.cos(angle)*e.r,y:e.y+Math.sin(angle)*e.r,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r:kind==='core'?9:kind==='flame'?8:kind==='arc'?7:6,life:4.6,damage,kind:kind||'rivet',turn:turn||0})}
  function shootEnemy(e,nx,ny){let a=Math.atan2(ny,nx),speed=205+depth*5;enemyShot(e,a,speed,e.damage,'rivet');sound('shoot')}
  function spawnBossBoilers(e,count){for(let i=0;i<count;i++){let a=i*Math.PI*2/count+e.phase,d=95+Math.random()*165;hazards.push({x:Math.max(70,Math.min(WORLD.w-70,player.x+Math.cos(a)*d)),y:Math.max(70,Math.min(WORLD.h-70,player.y+Math.sin(a)*d)),r:48,type:'boiler',warm:1.15,active:.42,life:1.65,hit:false,damage:e.damage*.58})}}
  function tyrantVolley(e,nx,ny){let aim=Math.atan2(ny,nx),stage=e.bossStage||1,pattern=e.pattern++;if(stage===1){for(let i=-3;i<=3;i++)enemyShot(e,aim+i*.13,212,e.damage*.52,'flame');if(pattern%2===1)for(let i=0;i<8;i++)enemyShot(e,i*Math.PI/4+e.phase,138,e.damage*.34,'flame')}else if(stage===2){for(let i=-4;i<=4;i++)enemyShot(e,aim+i*.14,225,e.damage*.48,'flame');spawnBossBoilers(e,3);if(pattern%3===2)spawnEnemy(false,'brute')}else{for(let i=0;i<14;i++)enemyShot(e,i*Math.PI*2/14+e.phase,188,e.damage*.4,'flame',(i%2?1:-1)*.12);for(let i=-2;i<=2;i++)enemyShot(e,aim+i*.11,260,e.damage*.62,'core');if(pattern%2===0)spawnBossBoilers(e,4)}e.phase+=stage===3?.37:.29;effects.push({x:e.x,y:e.y,r:e.r*.72,maxR:e.r*1.75,life:.28,max:.28,color:'#ff7a3d'});shake=Math.max(shake,stage===3?6:4);sound('boss')}
  function bossVolley(e,nx,ny){if(e.bossKind==='tyrant'){tyrantVolley(e,nx,ny);return}let aim=Math.atan2(ny,nx),stage=e.bossStage||1,pattern=e.pattern++;if(stage===1){for(let i=-2;i<=2;i++)enemyShot(e,aim+i*.16,228,e.damage*.68,'core');if(pattern%2===1)for(let i=0;i<7;i++)enemyShot(e,i*Math.PI*2/7+e.phase,145,e.damage*.42,'rivet')}else if(stage===2){for(let i=0;i<16;i++){let a=i*Math.PI*2/16+e.phase,diff=Math.abs(Math.atan2(Math.sin(a-aim),Math.cos(a-aim)));if(diff>.27)enemyShot(e,a,174,e.damage*.48,'arc',(i%2?1:-1)*.14)}if(pattern%2===1){spawnEnemy(false,'rusher');spawnEnemy(false,'rusher')}}else{for(let i=0;i<18;i++){let a=i*Math.PI*2/18+e.phase;enemyShot(e,a,198,e.damage*.46,'arc',(i%2?1:-1)*.3)}for(let i=-2;i<=2;i++)enemyShot(e,aim+i*.12,270,e.damage*.72,'core');if(pattern%2===0)spawnEnemy(true,'lancer')}e.phase+=stage===3 ? .31 : .43;effects.push({x:e.x,y:e.y,r:e.r*.7,maxR:e.r*1.9,life:.3,max:.3,color:stage===1?'#ef5350':stage===2?'#f2c14f':'#8f9dff'});shake=Math.max(shake,stage===3?6:4);sound('boss')}
  function destroyEnemy(e){if(e.dead)return;e.dead=true;if(runStats){runStats.kills++;if(e.elite)runStats.elites++}if(e.boss){defeatBoss(e);return}shake=Math.max(shake,e.elite?6:2.5);let drops=1+(e.elite?1:0)+(e.eventReward?1:0);for(let i=0;i<drops;i++){let minimum=e.eventReward&&i===drops-1?(depth>=4?'epic':'rare'):e.elite&&i===0?'rare':null;spawnLoot(e.x,e.y,rollLootItem(e.elite,minimum),true)}burst(e.x,e.y,e.elite?'#f2c14f':e.type==='brute'?'#d7863b':e.type==='lancer'?'#8f9dff':'#ef5350',e.elite?20:10,e.elite?1.35:1);sound(e.elite?'rare':'kill')}
  function damageEnemy(e,amount,x,y,strong){if(!e||e.dead)return;e.hp-=amount;e.hit=strong ? .18 : .11;impact(x==null?e.x:x,y==null?e.y:y,e.boss?'#ff9b6d':strong?'#fff0a8':'#f2c14f',strong?1.5:.7);if(e.boss){ui.bossHealthFill.style.width=Math.max(0,e.hp/e.max*100)+'%';let pct=e.hp/e.max,stage=pct<=.33?3:pct<=.67?2:1;if(stage!==e.bossStage)setBossStage(e,stage)}if(e.hp<=0)destroyEnemy(e)}
  function spawnHazard(){if(depth!==3&&depth!==4)return;let a=Math.random()*Math.PI*2,d=130+Math.random()*190,isFurnace=route==='furnace',type=isFurnace?(depth===3?'steam':'fire'):'arc',warm=type==='steam'?1.15:type==='arc'?1:.9,active=type==='steam'?.7:type==='fire'?.58:.45;hazards.push({x:Math.max(70,Math.min(WORLD.w-70,player.x+Math.cos(a)*d)),y:Math.max(70,Math.min(WORLD.h-70,player.y+Math.sin(a)*d)),r:type==='steam'?64:type==='fire'?58:76,type,warm,active,life:warm+active,hit:false,damage:type==='steam'?8:type==='fire'?11:depth===3?7:10})}
  function updateHazards(dt){hazardClock-=dt;if(!bossActive&&(depth===3||depth===4)&&hazardClock<=0){hazardClock=route==='furnace'?(depth===3?3.6:2.85):(depth===3?3.8:3.25);spawnHazard()}for(const h of hazards){h.life-=dt;if(h.warm>0){h.warm-=dt;continue}h.active-=dt;let dx=player.x-h.x,dy=player.y-h.y;if(!h.hit&&dx*dx+dy*dy<h.r*h.r){h.hit=true;if(damagePlayer(h.damage||10))return true}}hazards=hazards.filter(h=>h.life>0);return false}

  function update(dt){
    if(mode!=='run'||paused)return;if(decision||routeDecision||moduleDecision)return;runTime+=dt;if(!bossActive&&!bossDefeated)elapsed+=dt;let nextDepth=depthForElapsed(elapsed);if(nextDepth>depth){if(nextDepth===3&&!route){if(!extracting){showRouteDecision();return}}else{enterDepth(nextDepth);if(decision||bossActive)return}}if(!bossActive&&!bossDefeated&&!zoneEventTriggered&&zoneProgress()>=.58)triggerZoneEvent();
    let move=movement(),stats=cargoStats();player.inv=Math.max(0,player.inv-dt);player.fire-=dt;player.recoil=Math.max(0,player.recoil-dt);player.dashCd=Math.max(0,player.dashCd-dt);if(player.dashTime>0){player.dashTime-=dt;player.x+=player.dashX*820*dt;player.y+=player.dashY*820*dt;if(save.settings.particles&&Math.random()<.65)particles.push({x:player.x-player.dashX*18,y:player.y-player.dashY*18,vx:-player.dashX*40,vy:-player.dashY*40,life:.22,max:.22,r:7,color:stats.ram?'#f2c14f':'#47c5b6'});if(stats.ram)for(const e of enemies){if(e.dead||player.ramHits.has(e))continue;let dx=e.x-player.x,dy=e.y-player.y;if(dx*dx+dy*dy<(e.r+player.r+8)*(e.r+player.r+8)){player.ramHits.add(e);damageEnemy(e,stats.ram,player.x,player.y,true)}}}else{player.x+=move.x*player.speed*stats.speed*dt;player.y+=move.y*player.speed*stats.speed*dt;if(move.x||move.y){player.lastX=move.x;player.lastY=move.y;player.angle=Math.atan2(move.y,move.x)}}player.x=Math.max(player.r,Math.min(WORLD.w-player.r,player.x));player.y=Math.max(player.r,Math.min(WORLD.h-player.r,player.y));if(updateHazards(dt))return;
    spawnClock-=dt;let interval=Math.max(.78,2.15-depth*.1-riskTier*.06-zoneProgress()*.32);if(!bossActive&&!bossDefeated&&spawnClock<=0){spawnClock=interval*(.78+Math.random()*.44);spawnEnemy()}
    let target=nearestEnemy(430);if(target&&player.fire<=0)fireAt(target);
    for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of enemies){if(e.dead||b.dead)continue;let dx=e.x-b.x,dy=e.y-b.y;if(dx*dx+dy*dy<(e.r+b.r)*(e.r+b.r)){b.dead=true;damageEnemy(e,b.damage,b.x,b.y,b.explosive);if(b.explosive){effects.push({x:b.x,y:b.y,r:8,maxR:74,life:.32,max:.32,color:'#ff8b54'});for(const other of enemies){if(other===e||other.dead)continue;let ox=other.x-b.x,oy=other.y-b.y;if(ox*ox+oy*oy<74*74)damageEnemy(other,b.damage*.55,b.x,b.y,true)}}sound('hit')}}}bullets=bullets.filter(b=>!b.dead&&b.life>0);
    for(const e of enemies){if(e.dead)continue;e.anim=(e.anim||0)+dt;e.hit=Math.max(0,e.hit-dt);e.attack=Math.max(0,e.attack-dt);e.fire-=dt;let dx=player.x-e.x,dy=player.y-e.y,l=Math.hypot(dx,dy)||1,nx=dx/l,ny=dy/l;e.angle=Math.atan2(dy,dx);if(e.boss){let stage=e.bossStage||1,tyrant=e.bossKind==='tyrant',desired=tyrant?(stage===1?270:stage===2?235:205):(stage===1?295:stage===2?255:220),approach=l>desired+35?1:l<desired-45?-1:0,orbit=tyrant?(stage===3?.48:stage===2?.34:.22):(stage===3?.72:stage===2?.56:.4);e.x+=(nx*approach-ny*orbit)*e.speed*dt;e.y+=(ny*approach+nx*orbit)*e.speed*dt;if(e.charge>0){e.charge-=dt;if(e.charge<=0)bossVolley(e,nx,ny)}else if(e.fire<=0){e.charge=tyrant?(stage===1?.78:stage===2?.72:.55):(stage===1?.72:stage===2?.88:.58);e.fire=tyrant?(stage===1?2.05:stage===2?1.82:1.48):(stage===1?2.15:stage===2?1.9:1.55)}}else if(e.type==='shooter'){let approach=l>315?1:l<205?-1:0;e.x+=(nx*approach-ny*.48*e.strafe)*e.speed*dt;e.y+=(ny*approach+nx*.48*e.strafe)*e.speed*dt;if(e.charge>0){e.charge-=dt;if(e.charge<=0)shootEnemy(e,nx,ny)}else if(e.fire<=0){e.charge=.48;e.fire=Math.max(.9,2.25-depth*.05-riskTier*.07)}}else if(e.type==='lancer'){if(e.dashTime>0){e.dashTime-=dt;e.x+=e.dashX*430*dt;e.y+=e.dashY*430*dt}else{let approach=l>270?1:l<180?-1:0;e.x+=(nx*approach-ny*.65*e.strafe)*e.speed*dt;e.y+=(ny*approach+nx*.65*e.strafe)*e.speed*dt;if(e.charge>0){e.charge-=dt;if(e.charge<=0){e.dashTime=.34;e.dashX=nx;e.dashY=ny;effects.push({x:e.x,y:e.y,r:4,maxR:34,life:.2,max:.2,color:'#8f9dff'})}}else if(e.fire<=0){e.charge=.62;e.fire=2.1-riskTier*.08}}}else{e.x+=nx*e.speed*dt;e.y+=ny*e.speed*dt}if(l<e.r+player.r+3&&e.attack<=0){e.attack=.72;if(damagePlayer(e.damage))return}}enemies=enemies.filter(e=>!e.dead);
    for(const b of enemyBullets){if(b.turn){let a=b.turn*dt,cs=Math.cos(a),sn=Math.sin(a),vx=b.vx,vy=b.vy;b.vx=vx*cs-vy*sn;b.vy=vx*sn+vy*cs}b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let dx=b.x-player.x,dy=b.y-player.y;if(dx*dx+dy*dy<(b.r+player.r)*(b.r+player.r)){b.dead=true;if(damagePlayer(b.damage))return}}enemyBullets=enemyBullets.filter(b=>!b.dead&&b.life>0&&b.x>-30&&b.y>-30&&b.x<WORLD.w+30&&b.y<WORLD.h+30);
    const magnet=magnetRange()+stats.magnet;for(const drop of lootDrops){drop.spin+=dt*(2.5+LOOT_RARITIES[drop.item.rarity].rank*.45);drop.x+=drop.vx*dt;drop.y+=drop.vy*dt;drop.vx*=Math.pow(.02,dt);drop.vy*=Math.pow(.02,dt);let dx=player.x-drop.x,dy=player.y-drop.y,l=Math.hypot(dx,dy)||1;if(l<magnet){let pull=(1-l/magnet)*820;drop.x+=dx/l*pull*dt;drop.y+=dy/l*pull*dt}if(l<player.r+drop.r+5){drop.dead=true;collectLoot(drop);if(stats.flux)player.dashCd=Math.max(0,player.dashCd-.07)}}lootDrops=lootDrops.filter(drop=>!drop.dead);
    for(const c of caches){c.spin+=dt*1.4;let dx=player.x-c.x,dy=player.y-c.y,l=Math.hypot(dx,dy)||1;if(l<magnet*.72){let pull=(1-l/(magnet*.72))*320;c.x+=dx/l*pull*dt;c.y+=dy/l*pull*dt}if(l<player.r+c.r+7){c.opened=true;burst(c.x,c.y,c.rare?'#f2c14f':'#47c5b6',c.rare?28:16,c.rare?1.4:1);openModuleCache(c);break}}caches=caches.filter(c=>!c.opened);
    for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.06,dt);p.vy*=Math.pow(.06,dt);p.life-=dt}particles=particles.filter(p=>p.life>0);for(const e of effects)e.life-=dt;effects=effects.filter(e=>e.life>0);shake*=Math.pow(.02,dt);flash=Math.max(0,flash-dt);depthPulse=Math.max(0,depthPulse-dt);
    if(extracting>0){extracting-=dt;ui.extractCount.textContent=Math.max(1,Math.ceil(extracting));if(extracting<=0){ui.extractOverlay.classList.remove('show');returnBase(true);return}}updateHud();
  }

  function camera(){return{x:Math.max(W/2,Math.min(WORLD.w-W/2,player.x)),y:Math.max(H/2,Math.min(WORLD.h-H/2,player.y))}}
  function worldToScreen(x,y,cam){return{x:x-cam.x+W/2,y:y-cam.y+H/2}}
  function roundedRect(x,y,w,h,r){ctx.beginPath();if(ctx.roundRect){ctx.roundRect(x,y,w,h,r);return}r=Math.min(r,w/2,h/2);ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
  function drawGear(x,y,r,rot,color){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.fillStyle=color;for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillRect(r*.72,-r*.14,r*.42,r*.28)}ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#131719';ctx.beginPath();ctx.arc(0,0,r*.38,0,Math.PI*2);ctx.fill();ctx.restore()}
  function drawCache(c,cam){let p=worldToScreen(c.x,c.y,cam),color=c.rare?'#f2c14f':'#47c5b6';ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.sin(c.spin)*.06);ctx.shadowColor=color;ctx.shadowBlur=c.rare?20:10;ctx.fillStyle='#273034';ctx.strokeStyle=color;ctx.lineWidth=3;roundedRect(-20,-16,40,32,5);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=color;ctx.fillRect(-4,-9,8,18);ctx.fillRect(-13,-3,26,6);ctx.fillStyle='#0d1416';ctx.beginPath();ctx.arc(0,0,4,0,Math.PI*2);ctx.fill();ctx.restore()}
  function drawLootDrop(drop,cam){let item=drop.item,rarity=LOOT_RARITIES[item.rarity],rank=rarity.rank,p=worldToScreen(drop.x,drop.y,cam),bob=Math.sin(performance.now()/180+drop.spin)*3,r=drop.r;ctx.save();ctx.translate(p.x,p.y+bob);if(rank===4){ctx.globalAlpha=.28;let beam=ctx.createLinearGradient(0,-82,0,28);beam.addColorStop(0,'#f2c14f00');beam.addColorStop(.65,'#f2c14f88');beam.addColorStop(1,'#f2c14f00');ctx.fillStyle=beam;ctx.fillRect(-8,-82,16,110);ctx.globalAlpha=1}ctx.rotate(drop.spin);ctx.shadowColor=rarity.glow;ctx.shadowBlur=rank?8+rank*5:3;ctx.fillStyle=rank?'#171b1d':'#252c2e';ctx.strokeStyle=rarity.color;ctx.lineWidth=2+rank*.45;if(item.form==='gear'){drawGear(0,0,r,drop.spin*.25,rarity.color)}else if(item.form==='ring'){ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(0,0,r*.46,0,Math.PI*2);ctx.stroke()}else if(item.form==='coil'){ctx.beginPath();for(let i=-2;i<=2;i++)ctx.arc(i*r*.22,0,r*.34,-Math.PI*.72,Math.PI*.72);ctx.stroke()}else if(item.form==='bolt'){ctx.fillStyle=rarity.color;ctx.fillRect(-r*.22,-r*.78,r*.44,r*1.56);ctx.beginPath();for(let i=0;i<6;i++){let a=i*Math.PI/3;ctx.lineTo(Math.cos(a)*r*.62,Math.sin(a)*r*.62-r*.72)}ctx.closePath();ctx.fill()}else if(item.form==='canister'){roundedRect(-r*.55,-r*.78,r*1.1,r*1.56,r*.24);ctx.fill();ctx.stroke();ctx.fillStyle=rarity.color;ctx.fillRect(-r*.28,-r,r*.56,r*.25)}else if(item.form==='plate'){ctx.beginPath();ctx.moveTo(-r,-r*.55);ctx.lineTo(r*.7,-r*.72);ctx.lineTo(r,r*.58);ctx.lineTo(-r*.72,r*.76);ctx.closePath();ctx.fill();ctx.stroke()}else{ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=rarity.color;ctx.beginPath();ctx.arc(0,0,item.form==='core'?r*.48:r*.3,0,Math.PI*2);ctx.fill();if(item.form==='gauge'){ctx.strokeStyle=rarity.glow;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(r*.48,-r*.35);ctx.stroke()}}ctx.shadowBlur=0;if(rank>=2){ctx.strokeStyle=rarity.glow;ctx.globalAlpha=.7;ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,r*1.35,-drop.spin,Math.PI-drop.spin);ctx.stroke()}ctx.restore()}
  function drawBossEntity(e){let stage=e.bossStage||1;if(e.bossKind==='tyrant'){let hot=stage===3?'#ffdf83':stage===2?'#ff9a4d':'#ff6b35',r=e.r,bob=Math.sin(e.anim*2.4)*2;ctx.translate(0,bob);ctx.strokeStyle=hot+'88';ctx.lineWidth=3;for(let ring=1;ring<=2;ring++){ctx.beginPath();ctx.arc(0,0,r*(1+.22*ring),e.anim*.18*ring,e.anim*.18*ring+Math.PI*(stage===3?1.8:1.15));ctx.stroke()}ctx.fillStyle=e.hit?'#fff0c2':'#4a2618';ctx.strokeStyle='#160b08';ctx.lineWidth=6;roundedRect(-r*.82,-r*.66,r*1.55,r*1.32,14);ctx.fill();ctx.stroke();ctx.fillStyle='#2a1711';ctx.strokeStyle='#b86632';ctx.lineWidth=3;roundedRect(-r*.72,-r*.55,r*1.24,r*1.1,10);ctx.fill();ctx.stroke();ctx.fillStyle='#382018';ctx.strokeStyle='#17100c';ctx.lineWidth=4;ctx.fillRect(-r*.48,-r*.9,r*.24,r*.37);ctx.strokeRect(-r*.48,-r*.9,r*.24,r*.37);ctx.fillRect(r*.12,-r*.88,r*.22,r*.34);ctx.strokeRect(r*.12,-r*.88,r*.22,r*.34);ctx.fillStyle='#c67838';ctx.fillRect(-r*.54,-r*.94,r*.36,r*.08);ctx.fillRect(r*.06,-r*.92,r*.34,r*.08);drawGear(-r*.55,r*.18,r*.27,-e.anim*1.1,'#8e542c');drawGear(r*.46,r*.2,r*.23,e.anim*1.35,'#a15a2d');ctx.fillStyle='#140b08';ctx.strokeStyle=hot;ctx.lineWidth=5;ctx.beginPath();ctx.arc(r*.02,0,r*.32,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=e.charge>0?'#fff0c2':hot;ctx.shadowColor=hot;ctx.shadowBlur=stage===3?22:12;ctx.beginPath();ctx.arc(r*.02,0,r*.18,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#160807';for(let i=0;i<3;i++)ctx.fillRect(-r*.08+i*r*.1,-r*.14,r*.045,r*.28);ctx.fillStyle='#2b1710';ctx.strokeStyle='#b86632';ctx.lineWidth=3;roundedRect(r*.55,-r*.17,r*.66,r*.34,8);ctx.fill();ctx.stroke();ctx.fillStyle=hot;ctx.beginPath();ctx.arc(r*1.18,0,r*.13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d9a15f';for(let i=0;i<8;i++){let a=i*Math.PI/4;ctx.beginPath();ctx.arc(Math.cos(a)*r*.64,Math.sin(a)*r*.48,r*.035,0,Math.PI*2);ctx.fill()}}else{let stageColor=stage===3?'#8f9dff':stage===2?'#f2c14f':'#ef5350';ctx.rotate(-e.angle+e.anim*(.38+stage*.15));ctx.strokeStyle=stageColor+'99';ctx.lineWidth=4;for(let ring=1;ring<=2;ring++){ctx.beginPath();ctx.arc(0,0,e.r*(1+.24*ring),ring?e.anim*.15:0,Math.PI*2+e.anim*.15);ctx.stroke()}drawGear(0,0,e.r,e.anim*.8,e.hit?'#fff0c2':'#70342f');ctx.fillStyle='#161113';ctx.beginPath();ctx.arc(0,0,e.r*.58,0,Math.PI*2);ctx.fill();ctx.strokeStyle=stageColor;ctx.lineWidth=5;ctx.stroke();ctx.fillStyle=e.charge>0?'#fff0c2':stageColor;ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.fill();ctx.shadowColor=stageColor;ctx.shadowBlur=18;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#1a0c0c';ctx.beginPath();ctx.arc(0,0,6,0,Math.PI*2);ctx.fill()}}
  function draw(){
    if(mode!=='run')return;ctx.clearRect(0,0,W,H);let cam=camera(),zone=zoneAt(depth),shakeNow=save.settings.shake?shake:0,sx=(Math.random()-.5)*shakeNow,sy=(Math.random()-.5)*shakeNow;ctx.save();ctx.translate(sx,sy);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,zone.top);g.addColorStop(1,zone.bottom);ctx.fillStyle=g;ctx.fillRect(-10,-10,W+20,H+20);
    let grid=depth===2?64:80,ox=(-cam.x+W/2)%grid,oy=(-cam.y+H/2)%grid;ctx.strokeStyle=zone.grid;ctx.lineWidth=1;for(let x=ox;x<W;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=oy;y<H;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}if(depth===2){ctx.fillStyle='#47c5b60a';for(let y=oy;y<H;y+=grid*2)ctx.fillRect(0,y,W,grid*.48)}else if((depth===3||depth===4)&&route==='furnace'){ctx.strokeStyle=zone.accent+'20';ctx.lineWidth=depth===4?16:10;for(let x=ox-grid;x<W+grid;x+=grid*2){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+H*.38,H);ctx.stroke()}}else if(depth===3||depth===4){ctx.strokeStyle=zone.accent+'22';ctx.lineWidth=2;for(let x=ox;x<W;x+=grid*2){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+Math.sin(elapsed*2+x)*18,H);ctx.stroke()}}else if(depth===5){ctx.strokeStyle=zone.accent+'24';ctx.lineWidth=3;for(let r=90;r<Math.max(W,H);r+=110){ctx.beginPath();ctx.arc(W/2,H/2,r,0,Math.PI*2);ctx.stroke()}}
    for(const d of decor){let p=worldToScreen(d.x,d.y,cam);if(p.x<-60||p.x>W+60||p.y<-60||p.y>H+60)continue;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(d.rot);if(d.type===0)drawGear(0,0,d.r,d.rot,route==='dynamo'&&depth>=3?'#343b59':route==='furnace'&&depth>=3?'#5a3423':'#3d4547');else if(d.type===1){ctx.fillStyle=route==='furnace'&&depth>=3?'#5b3524':route==='dynamo'&&depth>=3?'#29324d':'#463425';ctx.fillRect(-d.r,-d.r*.55,d.r*2,d.r*1.1);ctx.strokeStyle=zone.accent+'55';ctx.strokeRect(-d.r,-d.r*.55,d.r*2,d.r*1.1)}else if(d.type===2){ctx.strokeStyle=zone.accent+'44';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,d.r,-2.5,1.4);ctx.stroke()}else{ctx.fillStyle=route==='dynamo'&&depth>=3?'#303852':route==='furnace'&&depth>=3?'#4b2b20':'#2b3437';ctx.beginPath();ctx.moveTo(-d.r,d.r);ctx.lineTo(0,-d.r);ctx.lineTo(d.r,d.r);ctx.fill()}ctx.restore()}
    for(const h of hazards){let p=worldToScreen(h.x,h.y,cam),warning=h.warm>0,pulse=.65+Math.sin(performance.now()/90)*.2,hot=h.type==='steam'||h.type==='fire'||h.type==='boiler',color=h.type==='steam'?'#ef8f3c':h.type==='fire'?'#ff6338':h.type==='boiler'?'#ff7a3d':'#8f9dff';ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=warning?pulse:Math.max(.25,h.active*1.4);ctx.strokeStyle=color;ctx.lineWidth=warning?3:7;ctx.setLineDash(warning?[9,7]:[]);ctx.beginPath();ctx.arc(0,0,h.r*(warning?1:.88),0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);if(h.type==='boiler'&&warning)drawGear(0,0,h.r*.28,performance.now()/260,'#6b3a22');if(!warning){let hg=ctx.createRadialGradient(0,0,4,0,0,h.r);hg.addColorStop(0,hot?'#fff0bdcc':'#dfe5ffdd');hg.addColorStop(.35,color+'99');hg.addColorStop(1,'#0000');ctx.fillStyle=hg;ctx.beginPath();ctx.arc(0,0,h.r,0,Math.PI*2);ctx.fill()}ctx.restore()}
    for(const c of caches)drawCache(c,cam);for(const drop of lootDrops)drawLootDrop(drop,cam);
    for(const b of bullets){let p=worldToScreen(b.x,b.y,cam),color=b.color||'#f2c14f';ctx.strokeStyle=color+'77';ctx.lineWidth=b.explosive?8:5;ctx.beginPath();ctx.moveTo(p.x-b.vx*.028,p.y-b.vy*.028);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.fillStyle=b.explosive?'#fff0bd':'#fff2ac';ctx.beginPath();ctx.arc(p.x,p.y,b.r,0,Math.PI*2);ctx.fill()}for(const b of enemyBullets){let p=worldToScreen(b.x,b.y,cam),color=b.kind==='arc'?'#8f9dff':b.kind==='flame'?'#ff6b35':b.kind==='core'?'#ff9b6d':'#ef5350';ctx.strokeStyle=color+'66';ctx.lineWidth=b.r*1.15;ctx.beginPath();ctx.moveTo(p.x-b.vx*.045,p.y-b.vy*.045);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,b.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff0d5';ctx.beginPath();ctx.arc(p.x-2,p.y-2,b.r*.3,0,Math.PI*2);ctx.fill()}
    for(const e of enemies){
      let p=worldToScreen(e.x,e.y,cam);
      if(e.charge>0){let aim=worldToScreen(player.x,player.y,cam),tyrant=e.boss&&e.bossKind==='tyrant',chargeMax=e.boss?(tyrant?(e.bossStage===1?.78:e.bossStage===2?.72:.55):(e.bossStage===2?.88:e.bossStage===3?.58:.72)):e.type==='lancer'?.62:.48,progress=1-Math.min(1,e.charge/chargeMax),telegraph=tyrant?'255,122,61':e.type==='lancer'?'143,157,255':'239,83,80';ctx.strokeStyle='rgba('+telegraph+','+(.28+progress*.7)+')';ctx.lineWidth=e.boss?3:2;ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([])}
      ctx.save();ctx.translate(p.x,p.y);ctx.rotate(e.angle);
      if(e.boss)drawBossEntity(e);
      else{if(e.elite){ctx.strokeStyle='#f2c14f88';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,e.r*1.45,0,Math.PI*2);ctx.stroke()}ctx.fillStyle=e.hit?'#fff0c2':e.type==='brute'?'#7d482d':e.type==='shooter'?'#49324e':e.type==='lancer'?'#343b68':'#642f2d';ctx.strokeStyle=e.elite?'#f2c14f':'#101315';ctx.lineWidth=4;if(e.type==='shooter'){ctx.beginPath();ctx.moveTo(e.r,0);ctx.lineTo(0,e.r*.82);ctx.lineTo(-e.r,0);ctx.lineTo(0,-e.r*.82);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#2a3032';ctx.fillRect(e.r*.3,-4,e.r*1.05,8);ctx.fillStyle=e.charge>0?'#fff0c2':'#ef5350';ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill()}else if(e.type==='lancer'){ctx.beginPath();ctx.moveTo(e.r*1.45,0);ctx.lineTo(-e.r*.65,e.r*.72);ctx.lineTo(-e.r*.25,0);ctx.lineTo(-e.r*.65,-e.r*.72);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=e.charge>0?'#fff':'#8f9dff';ctx.beginPath();ctx.arc(e.r*.28,0,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#8f9dff88';ctx.lineWidth=3;ctx.beginPath();ctx.arc(-e.r*.1,0,e.r*.9,e.anim*2,e.anim*2+Math.PI);ctx.stroke()}else{roundedRect(-e.r,-e.r*.72,e.r*2,e.r*1.44,e.type==='brute'?8:5);ctx.fill();ctx.stroke();ctx.fillStyle='#ef5350';ctx.beginPath();ctx.arc(e.r*.35,-e.r*.18,e.elite?4.5:3.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2a3032';ctx.fillRect(-e.r*1.25,-4,e.r*.7,8);if(e.type==='brute')drawGear(-e.r*.55,0,e.r*.45,e.anim*2,'#a76a35')}}
      ctx.restore();let hp=Math.max(0,e.hp/e.max);if(!e.boss&&(hp<1||e.elite)){ctx.fillStyle='#2a1717';ctx.fillRect(p.x-e.r,p.y-e.r-11,e.r*2,4);ctx.fillStyle=e.elite?'#f2c14f':e.type==='lancer'?'#8f9dff':'#ef5350';ctx.fillRect(p.x-e.r,p.y-e.r-11,e.r*2*hp,4)}
    }
    let pp=worldToScreen(player.x,player.y,cam),stats=cargoStats(),thermalReady=player.thermalCharges>0,coreColor=thermalReady?'#ff6b35':'#47c5b6';ctx.save();ctx.translate(pp.x,pp.y);ctx.rotate(player.angle);if(player.inv>0&&player.dashTime<=0&&Math.floor(player.inv*16)%2===0)ctx.globalAlpha=.4;if(player.dashTime>0){ctx.strokeStyle=thermalReady?'#ff8b54cc':stats.ram?'#f2c14faa':'#47c5b6aa';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,player.r+6,0,Math.PI*2);ctx.stroke()}if(player.shields>0){ctx.strokeStyle='#7ff4e6aa';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,player.r+7,0,Math.PI*2);ctx.stroke()}if(thermalReady){ctx.strokeStyle='#ff6b35aa';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,player.r+10+Math.sin(performance.now()/110)*2,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#283438';ctx.strokeStyle='#0a0d0e';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=coreColor;ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.fill();ctx.shadowColor=coreColor;ctx.shadowBlur=thermalReady?17:10;ctx.fill();ctx.shadowBlur=0;let kick=Math.min(7,player.recoil*60);ctx.fillStyle=thermalReady?'#8b3420':'#d7863b';roundedRect(8-kick,-5,24,10,3);ctx.fill();ctx.fillStyle=thermalReady?'#ffba70':'#f2c14f';ctx.beginPath();ctx.arc(5,-7,3,0,Math.PI*2);ctx.arc(5,7,3,0,Math.PI*2);ctx.fill();ctx.restore();
    for(const fx of effects){let q=worldToScreen(fx.x,fx.y,cam),progress=1-fx.life/fx.max;ctx.globalAlpha=Math.max(0,fx.life/fx.max);ctx.strokeStyle=fx.color;ctx.lineWidth=Math.max(1,4*(1-progress));ctx.beginPath();ctx.arc(q.x,q.y,fx.r+(fx.maxR-fx.r)*progress,0,Math.PI*2);ctx.stroke()}for(const p of particles){let q=worldToScreen(p.x,p.y,cam);ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(q.x-p.r/2,q.y-p.r/2,p.r,p.r)}ctx.globalAlpha=1;let vignette=ctx.createRadialGradient(W/2,H/2,Math.min(W,H)*.25,W/2,H/2,Math.max(W,H)*.72);vignette.addColorStop(.55,'#0000');vignette.addColorStop(1,'#0009');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);if(flash>0){ctx.fillStyle='rgba(239,83,80,'+(flash*1.8)+')';ctx.fillRect(0,0,W,H)}ctx.restore();
    if(depthPulse>0){let a=Math.min(1,depthPulse*1.8),scale=1+(1.15-depthPulse)*.08,boss=currentBoss();ctx.save();ctx.globalAlpha=a;ctx.translate(W/2,H*.22);ctx.scale(scale,scale);ctx.textAlign='center';ctx.font='900 11px Segoe UI,Arial';ctx.fillStyle='#c0c9cb';ctx.fillText(depth===5?'BOSS SIGNAL':'DEPTH '+depth,0,-13);ctx.font='900 28px Segoe UI,Arial';ctx.fillStyle=zone.accent;ctx.fillText(depth===5?boss.name:zone.name,0,22);ctx.restore()}
    if(paused){ctx.fillStyle='#05090ba8';ctx.fillRect(0,0,W,H)}
  }

  function updateRouteHud(){let ticks=[...ui.routeTicks.children];ticks.forEach((tick,index)=>{let level=index+1;tick.className=level<depth||bossDefeated?'done':level===depth?(bossActive?'boss':'current'):''});ui.routeLabel.textContent=route?ROUTES[route].short:'TOWER';ui.depthRoute.classList.toggle('furnace',route==='furnace');ui.depthRoute.classList.toggle('dynamo',route==='dynamo');ui.routeProgress.style.width=(bossActive||bossDefeated?100:zoneProgress()*100)+'%'}
  function updateHud(){let hp=Math.max(0,player?player.hp:0),max=player?player.maxHp:maxHp(),danger=depth+riskTier*2,mult=lootMultiplier(),best=bestLootEntry(),bestItem=best&&LOOT_BY_ID[best.id],legendary=lootManifest().some(entry=>LOOT_BY_ID[entry.id].rarity==='legendary');ui.healthText.textContent=Math.ceil(hp)+' / '+max+(player&&player.shields?'  \u25C6'+player.shields:'');ui.healthFill.style.width=(hp/max*100)+'%';ui.runScrap.textContent=runScrap;ui.lootBest.textContent=bestItem?bestItem.name:'EMPTY';ui.lootBest.style.color=bestItem?LOOT_RARITIES[bestItem.rarity].color:'';ui.lootMetric.classList.toggle('legendary',legendary);ui.expedition.classList.toggle('legendaryCargo',legendary);ui.extract.classList.toggle('hotLoot',legendary);ui.depth.textContent=depth;let risk=bossActive?'BOSS':danger<3?'LOW':danger<7?'RISING':danger<11?'HIGH':'EXTREME';ui.risk.textContent=risk+' x'+mult.toFixed(1);ui.risk.style.color=bossActive?currentBoss().accent:danger<3?'#7ccf63':danger<7?'#f2c14f':'#ef5350';if(player){let dashMax=cargoStats().dashCd,ready=Math.max(0,1-player.dashCd/dashMax);ui.dash.style.setProperty('--ready',ready*360+'deg');ui.dash.classList.toggle('cooling',player.dashCd>0)}updateRouteHud()}
  function loop(now){let dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}

  function buyUpgrade(type){let cost=upgradePrice(type);if(save.scrap<cost)return;save.scrap-=cost;save[type]++;persist();refreshBase();notice(type.toUpperCase()+' UPGRADED','#f2c14f');sound('upgrade')}
  function syncSettings(){for(const pair of [[ui.soundToggle,'sound'],[ui.shakeToggle,'shake'],[ui.particlesToggle,'particles']]){let on=save.settings[pair[1]];pair[0].classList.toggle('off',!on);pair[0].setAttribute('aria-checked',String(on));pair[0].querySelector('b').textContent=on?'ON':'OFF'}}
  function syncDevTools(){let inRun=mode==='run',next=SCHEMATIC_IDS.find(id=>schematicLevel(id)<BOSS_SCHEMATICS[id].max);ui.devScrap.textContent=inRun?'+500 RUN LOOT':'+500 BANK SCRAP';ui.devHeal.disabled=!inRun;ui.devCache.disabled=!inRun;ui.devLoot.disabled=!inRun;ui.devSchematic.disabled=!next;ui.devSchematic.textContent=next?'NEXT SCHEMATIC':'SCHEMATICS MAX'}
  function openSettings(){settingsWasRun=mode==='run';if(settingsWasRun)paused=true;abandonArmed=false;devResetArmed=false;ui.abandon.textContent='ABANDON EXPEDITION';ui.abandon.classList.remove('confirm');ui.devReset.textContent='HARD RESET SAVE';ui.devReset.classList.remove('confirm');ui.devPanel.classList.remove('show');ui.devButton.setAttribute('aria-expanded','false');ui.settingsPanel.classList.toggle('baseMode',!settingsWasRun);syncSettings();syncDevTools();ui.settingsOverlay.classList.add('show')}
  function closeSettings(){ui.settingsOverlay.classList.remove('show');paused=false;abandonArmed=false;devResetArmed=false;last=performance.now()}
  function toggleSetting(key){save.settings[key]=!save.settings[key];persist();syncSettings();if(key==='sound'){if(save.settings.sound){ensureAudio();sound('pickup')}else if(audio.timer){clearInterval(audio.timer);audio.timer=null}}}
  function abandonRun(){if(!settingsWasRun)return;if(!abandonArmed){abandonArmed=true;ui.abandon.textContent='CONFIRM: LOSE RUN CARGO';ui.abandon.classList.add('confirm');return}returnBase(false,'EXPEDITION ABANDONED')}
  function toggleDevPanel(){let open=ui.devPanel.classList.toggle('show');ui.devButton.setAttribute('aria-expanded',String(open));devResetArmed=false;ui.devReset.textContent='HARD RESET SAVE';ui.devReset.classList.remove('confirm');syncDevTools()}
  function devFeedback(text){if(mode==='run')runNotice(text,'#f2c14f');else notice(text,'#f2c14f');sound('upgrade')}
  function devAddScrap(){if(mode==='run'){runScrap+=500;updateHud();devFeedback('+500 RUN LOOT')}else{save.scrap+=500;persist();refreshBase();devFeedback('+500 BANK SCRAP')}}
  function devUpgradeRig(){for(const key of ['chassis','weapon','salvage'])save[key]=Math.min(200,save[key]+1);persist();refreshBase();if(mode==='run'&&player){applyCargoEffects();player.hp=player.maxHp;updateHud()}devFeedback('RIG LEVELS +1')}
  function devRepair(){if(mode!=='run'||!player)return;player.hp=player.maxHp;player.shields=cargoStats().shields;updateHud();devFeedback('FULL REPAIR')}
  function devDropCache(){if(mode!=='run'||!player)return;closeSettings();spawnCache(player.x+54,player.y,true,false);runNotice('RARE CACHE DROPPED','#f2c14f')}
  function devDropLegendary(){if(mode!=='run'||!player)return;closeSettings();let pool=LOOT_BY_RARITY.legendary,item=pool[Math.floor(Math.random()*pool.length)];spawnLoot(player.x+54,player.y,item,false);runNotice('LEGENDARY SIGNAL','#f2c14f')}
  function devFightBoss(routeId){if(mode!=='run')startRun();else closeSettings();decision=false;routeDecision=false;moduleDecision=false;extracting=0;bossDefeated=false;pendingWardenReward=null;activeCache=null;caches=[];route=routeId;if(runStats)runStats.route=routeId;ui.riskOverlay.classList.remove('show');ui.routeOverlay.classList.remove('show');ui.moduleOverlay.classList.remove('show');ui.extractOverlay.classList.remove('show');depth=5;elapsed=DEPTH_THRESHOLDS[4];updateRouteHud();startBoss();updateHud()}
  function devFightWarden(){devFightBoss('dynamo')}
  function devFightTyrant(){devFightBoss('furnace')}
  function devUnlockSchematic(){let id=SCHEMATIC_IDS.find(key=>schematicLevel(key)<BOSS_SCHEMATICS[key].max);if(!id)return;save.schematics[id]++;persist();refreshBase();syncDevTools();devFeedback(BOSS_SCHEMATICS[id].name.toUpperCase()+' +1')}
  function devHardReset(){if(!devResetArmed){devResetArmed=true;ui.devReset.textContent='CONFIRM: DELETE ALL PROGRESS';ui.devReset.classList.add('confirm');return}localStorage.removeItem(SAVE_KEY);window.location.reload()}

  ui.start.addEventListener('click',requestStart);ui.briefingStart.addEventListener('click',completeBriefing);ui.blueprintButton.addEventListener('click',openBlueprints);ui.closeBlueprints.addEventListener('click',closeBlueprints);ui.closeResult.addEventListener('click',closeResultPanel);ui.closeContract.addEventListener('click',claimContract);
  ui.extract.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();beginExtract()});ui.cancelExtract.addEventListener('click',cancelExtract);ui.riskExtract.addEventListener('click',extractFromRisk);ui.riskPush.addEventListener('click',pushDeeper);ui.routeFurnace.addEventListener('click',()=>chooseRoute('furnace'));ui.routeDynamo.addEventListener('click',()=>chooseRoute('dynamo'));ui.moduleSkip.addEventListener('click',skipModule);
  ui.upgradeChassis.addEventListener('click',()=>buyUpgrade('chassis'));ui.upgradeWeapon.addEventListener('click',()=>buyUpgrade('weapon'));ui.upgradeSalvage.addEventListener('click',()=>buyUpgrade('salvage'));ui.dash.addEventListener('pointerdown',e=>{e.preventDefault();tryDash()});
  ui.settingsButton.addEventListener('click',openSettings);ui.closeSettings.addEventListener('click',closeSettings);ui.resume.addEventListener('click',closeSettings);ui.soundToggle.addEventListener('click',()=>toggleSetting('sound'));ui.shakeToggle.addEventListener('click',()=>toggleSetting('shake'));ui.particlesToggle.addEventListener('click',()=>toggleSetting('particles'));ui.abandon.addEventListener('click',abandonRun);ui.devButton.addEventListener('click',toggleDevPanel);ui.devScrap.addEventListener('click',devAddScrap);ui.devRig.addEventListener('click',devUpgradeRig);ui.devHeal.addEventListener('click',devRepair);ui.devCache.addEventListener('click',devDropCache);ui.devLoot.addEventListener('click',devDropLegendary);ui.devWarden.addEventListener('click',devFightWarden);ui.devTyrant.addEventListener('click',devFightTyrant);ui.devSchematic.addEventListener('click',devUnlockSchematic);ui.devReset.addEventListener('click',devHardReset);
  window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'&&!e.repeat)tryDash();if(e.code==='KeyE'&&!e.repeat)beginExtract();if(e.code==='Escape'&&!e.repeat){if(ui.settingsOverlay.classList.contains('show'))closeSettings();else if(ui.blueprintOverlay.classList.contains('show'))closeBlueprints();else if(ui.resultOverlay.classList.contains('show'))closeResultPanel();else if(ui.contractOverlay.classList.contains('show'))claimContract();else openSettings()}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('resize',resize);
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='run'&&!paused)openSettings()});
  function stickMove(e){let r=ui.joystick.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),m=r.width*.34,l=Math.hypot(x,y)||1,cl=Math.min(m,l);stick.x=x/l*(cl/m);stick.y=y/l*(cl/m);ui.knob.style.transform='translate('+(stick.x*m)+'px,'+(stick.y*m)+'px)'}
  ui.joystick.addEventListener('pointerdown',e=>{stick.active=true;stick.id=e.pointerId;ui.joystick.setPointerCapture(e.pointerId);stickMove(e)});ui.joystick.addEventListener('pointermove',e=>{if(stick.active&&e.pointerId===stick.id)stickMove(e)});function stickEnd(e){if(e.pointerId!==stick.id)return;stick.active=false;stick.x=stick.y=0;ui.knob.style.transform=''}ui.joystick.addEventListener('pointerup',stickEnd);ui.joystick.addEventListener('pointercancel',stickEnd);
  let lastTouchEnd=0,lastTouchTarget=null;document.addEventListener('touchend',e=>{let now=Date.now(),button=e.target.closest&&e.target.closest('button');if(now-lastTouchEnd<340&&e.target===lastTouchTarget){e.preventDefault();if(button&&!button.disabled)button.click()}lastTouchEnd=now;lastTouchTarget=e.target},{passive:false});for(const event of ['gesturestart','gesturechange','gestureend','dblclick'])document.addEventListener(event,e=>e.preventDefault(),{passive:false});document.addEventListener('contextmenu',e=>e.preventDefault());

  persist();refreshBase();updateCargoHud();syncSettings();setView('base');requestAnimationFrame(loop);
})();
