(function(){
  'use strict';

  const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
  const ui={
    base:$('baseView'),expedition:$('expeditionView'),scene:document.querySelector('.workshopScene'),
    bank:$('bankScrap'),best:$('bestDepth'),settingsButton:$('settingsButton'),
    chassisLevel:$('chassisLevel'),weaponLevel:$('weaponLevel'),salvageLevel:$('salvageLevel'),
    maxHp:$('maxHpStat'),damage:$('damageStat'),magnet:$('magnetStat'),
    chassisCost:$('chassisCost'),weaponCost:$('weaponCost'),salvageCost:$('salvageCost'),
    upgradeChassis:$('upgradeChassis'),upgradeWeapon:$('upgradeWeapon'),upgradeSalvage:$('upgradeSalvage'),
    start:$('startButton'),notice:$('baseNotice'),blueprintButton:$('blueprintButton'),starterIcon:$('starterIcon'),starterName:$('starterName'),
    blueprintOverlay:$('blueprintOverlay'),closeBlueprints:$('closeBlueprints'),starterReadout:$('starterReadout'),blueprintGrid:$('blueprintGrid'),careerStats:$('careerStats'),
    briefingOverlay:$('briefingOverlay'),briefingStart:$('briefingStart'),
    resultOverlay:$('resultOverlay'),resultPanel:document.querySelector('.resultPanel'),resultTitle:$('resultTitle'),resultScrap:$('resultScrap'),resultDepth:$('resultDepth'),resultRecord:$('resultRecord'),resultModules:$('resultModules'),closeResult:$('closeResult'),
    healthText:$('healthText'),healthFill:$('healthFill'),runScrap:$('runScrap'),depth:$('depthText'),risk:$('riskText'),extract:$('extractButton'),
    depthRoute:$('depthRoute'),routeTicks:$('routeTicks'),runNotice:$('runNotice'),cargoSlots:$('cargoSlots'),bossHud:$('bossHud'),bossHealthFill:$('bossHealthFill'),
    extractOverlay:$('extractOverlay'),extractCount:$('extractCount'),cancelExtract:$('cancelExtract'),
    riskOverlay:$('riskOverlay'),riskScrap:$('riskScrap'),nextMultiplier:$('nextMultiplier'),riskExtract:$('riskExtract'),riskPush:$('riskPush'),
    moduleOverlay:$('moduleOverlay'),moduleEyebrow:$('moduleEyebrow'),moduleTitle:$('moduleTitle'),moduleChoices:$('moduleChoices'),moduleSkip:$('moduleSkip'),
    joystick:$('joystick'),knob:$('joystickKnob'),dash:$('dashButton'),
    settingsOverlay:$('settingsOverlay'),settingsPanel:document.querySelector('.settingsPanel'),closeSettings:$('closeSettings'),soundToggle:$('soundToggle'),shakeToggle:$('shakeToggle'),particlesToggle:$('particlesToggle'),resume:$('resumeButton'),abandon:$('abandonButton')
  };

  const SAVE_KEY='scrapbound_prototype_v1',SAVE_VERSION=2,WORLD={w:2400,h:1600},DEPTH_SECONDS=18;
  const LIMITS={enemies:72,bullets:220,enemyBullets:260,scraps:240,particles:320};
  const MODULES={
    burst:{name:'Burst Capacitor',icon:'\u2726',desc:'Adds another projectile to every volley.'},
    magnet:{name:'Magnetic Core',icon:'\u25CE',desc:'Pulls scrap and cargo from farther away.'},
    plating:{name:'Reactive Plating',icon:'\u25C6',desc:'Blocks incoming hits before armor takes damage.'},
    overdrive:{name:'Overdrive Coil',icon:'\u00BB',desc:'Boosts movement speed and cannon fire rate.'},
    volatile:{name:'Volatile Reactor',icon:'!',desc:'Raises damage, but lowers maximum health.'}
  };
  const MODULE_IDS=Object.keys(MODULES);
  const keys={},stick={active:false,id:null,x:0,y:0},audio={ctx:null};
  let save=loadSave(),mode='base',paused=false,settingsWasRun=false,abandonArmed=false;
  let W=960,H=540,dpr=1,last=0,elapsed=0,spawnClock=0,shake=0,flash=0,depthPulse=0,extracting=0,runScrap=0,depth=1,riskTier=0,decision=false;
  let player,enemies=[],bullets=[],enemyBullets=[],scraps=[],particles=[],decor=[],caches=[],cargo=[];
  let moduleDecision=false,moduleStage='offer',moduleOffer=[],pendingModule=null,activeCache=null,bossActive=false,bossDefeated=false,bossEntity=null;

  function clampNumber(value,min,max){value=Number(value);return Number.isFinite(value)?Math.max(min,Math.min(max,value)):min}
  function defaultBlueprint(){return {copies:0,rare:0,tune:0}}
  function defaultSave(){return {version:SAVE_VERSION,scrap:0,best:0,chassis:0,weapon:0,salvage:0,starter:null,seenIntro:false,blueprints:{},stats:{runs:0,extractions:0,losses:0,bosses:0,totalScrap:0},settings:{sound:true,shake:true,particles:true}}}
  function loadSave(){
    let raw={};try{raw=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')||{}}catch(e){}
    let data=defaultSave(),legacy=Math.max(0,Number(raw.rig)||0);data.scrap=clampNumber(raw.scrap,0,1e15);data.best=Math.floor(clampNumber(raw.best,0,999));data.chassis=Math.floor(clampNumber(raw.chassis==null?legacy:raw.chassis,0,200));data.weapon=Math.floor(clampNumber(raw.weapon==null?legacy:raw.weapon,0,200));data.salvage=Math.floor(clampNumber(raw.salvage,0,200));
    data.seenIntro=!!raw.seenIntro;data.settings=Object.assign(data.settings,raw.settings||{});for(const key of Object.keys(data.settings))data.settings[key]=data.settings[key]!==false;
    data.stats=Object.assign(data.stats,raw.stats||{});for(const key of Object.keys(data.stats))data.stats[key]=Math.floor(clampNumber(data.stats[key],0,1e12));
    for(const id of MODULE_IDS){let old=raw.blueprints&&raw.blueprints[id],record=defaultBlueprint();if(old&&typeof old==='object'){record.copies=Math.floor(clampNumber(old.copies,0,9999));record.rare=Math.floor(clampNumber(old.rare,0,9999));record.tune=Math.floor(clampNumber(old.tune,0,2))}else{record.copies=Math.floor(clampNumber(old,0,9999));record.rare=Math.floor(clampNumber(raw.blueprints&&raw.blueprints[id+'Rare'],0,9999))}data.blueprints[id]=record}
    data.starter=MODULES[raw.starter]&&data.blueprints[raw.starter].copies>0?raw.starter:null;data.version=SAVE_VERSION;return data;
  }
  function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save))}catch(e){}}

  function upgradePrice(type){let base=type==='chassis'?45:type==='weapon'?55:50;return Math.floor(base*Math.pow(1.68,save[type]||0))}
  function maxHp(){return 100+save.chassis*15}
  function shotDamage(){return Math.round((8+save.weapon*1.6)*10)/10}
  function magnetRange(){return 85+save.salvage*10}
  function lootMultiplier(nextTier){return (1+(depth-1)*.11)*(1+(nextTier==null?riskTier:nextTier)*.32)*(1+save.salvage*.045)}
  function blueprintTier(id){let copies=save.blueprints[id].copies;return copies>=7?3:copies>=3?2:copies>=1?1:0}
  function blueprintMark(tier){return tier===3?'MK III':tier===2?'MK II':tier===1?'MK I':'LOCKED'}
  function starterPower(id){let tier=blueprintTier(id),tune=save.blueprints[id].tune;return tier?1+(tier-1)*.15+tune*.1:0}
  function tuneCost(id){let record=save.blueprints[id],tier=blueprintTier(id);return Math.floor(80*(record.tune+1)*(1+tier*.45))}
  function modulePower(id){return cargo.reduce((sum,m)=>sum+(m.id===id?(m.power||(m.rare?2:1)):0),0)}
  function cargoStats(){let over=modulePower('overdrive'),volatile=modulePower('volatile');return {burst:Math.min(3,Math.floor(modulePower('burst')+.01)),magnet:modulePower('magnet')*48,shields:Math.floor(modulePower('plating')+.01),speed:1+over*.12,fire:Math.max(.55,1-over*.11),damage:1+volatile*.34,hp:Math.max(.58,1-volatile*.11)}}

  function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(2,window.devicePixelRatio||1);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function setView(next){mode=next;ui.base.classList.toggle('active',next==='base');ui.expedition.classList.toggle('active',next==='run');if(next==='run')requestAnimationFrame(()=>{resize();last=performance.now()})}
  function notice(text,tone){ui.notice.textContent=text;ui.notice.style.borderColor=tone||'';ui.notice.classList.add('show');clearTimeout(notice.t);notice.t=setTimeout(()=>ui.notice.classList.remove('show'),1700)}
  function runNotice(text,tone){ui.runNotice.textContent=text;ui.runNotice.style.borderColor=tone||'';ui.runNotice.classList.add('show');clearTimeout(runNotice.t);runNotice.t=setTimeout(()=>ui.runNotice.classList.remove('show'),1700)}
  function sound(name){
    if(!save.settings.sound)return;try{audio.ctx=audio.ctx||new (window.AudioContext||window.webkitAudioContext)();let a=audio.ctx,o=a.createOscillator(),g=a.createGain(),t=a.currentTime,f=name==='hit'?95:name==='pickup'?620:name==='shoot'?240:name==='hurt'?70:name==='upgrade'?420:name==='rare'?840:name==='boss'?58:name==='shield'?760:160,d=(name==='rare'||name==='boss')?.22:.11;o.type=name==='pickup'||name==='upgrade'||name==='rare'?'triangle':'square';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(30,f*((name==='hurt'||name==='boss')?.45:1.7)),t+d*.82);g.gain.setValueAtTime(name==='boss'?.05:.032,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+d+.01);if(name==='rare')setTimeout(()=>sound('upgrade'),80)}catch(e){}
  }

  function refreshBase(){
    ui.bank.textContent=Math.floor(save.scrap);ui.best.textContent=save.best;ui.chassisLevel.textContent=save.chassis;ui.weaponLevel.textContent=save.weapon;ui.salvageLevel.textContent=save.salvage;ui.maxHp.textContent=maxHp();ui.damage.textContent=shotDamage();ui.magnet.textContent=magnetRange();
    for(const type of ['chassis','weapon','salvage']){let button=ui['upgrade'+type[0].toUpperCase()+type.slice(1)],cost=upgradePrice(type);ui[type+'Cost'].textContent=cost;button.disabled=save.scrap<cost}
    let secured=MODULE_IDS.reduce((sum,id)=>sum+save.blueprints[id].copies,0),upgrades=save.chassis+save.weapon+save.salvage;ui.scene.classList.toggle('evolved1',upgrades>=2||secured>=1);ui.scene.classList.toggle('evolved2',upgrades>=5||secured>=4);ui.scene.classList.toggle('evolved3',upgrades>=9||secured>=9);
    if(save.starter){ui.starterIcon.textContent=MODULES[save.starter].icon;ui.starterName.textContent=MODULES[save.starter].name.toUpperCase()+' '+blueprintMark(blueprintTier(save.starter))}else{ui.starterIcon.textContent='+';ui.starterName.textContent='NONE EQUIPPED'}
  }
  function renderBlueprints(){
    ui.blueprintGrid.innerHTML='';ui.starterReadout.textContent=save.starter?MODULES[save.starter].name+' '+blueprintMark(blueprintTier(save.starter)):'No module equipped';
    for(const id of MODULE_IDS){let def=MODULES[id],record=save.blueprints[id],tier=blueprintTier(id),unlocked=tier>0,entry=document.createElement('article');entry.className='blueprintEntry '+(unlocked?'unlocked':'locked')+(save.starter===id?' equipped':'');
      let needed=tier===0?'Find in salvage caches':tier===1?record.copies+'/3 copies':tier===2?record.copies+'/7 copies':'Mastered';entry.innerHTML='<i>'+def.icon+'</i><strong>'+def.name+'</strong><p>'+def.desc+'</p><div class="blueprintMeta"><span>'+blueprintMark(tier)+' &middot; TUNE '+record.tune+'/2</span><b>'+needed+'</b></div>';
      let actions=document.createElement('div');actions.className='benchActions';let equip=document.createElement('button');equip.className='equipButton';equip.textContent=save.starter===id?'UNEQUIP':'EQUIP';equip.disabled=!unlocked;equip.addEventListener('click',()=>equipStarter(save.starter===id?null:id));let tune=document.createElement('button');tune.className='tuneButton';let cost=tuneCost(id);tune.textContent=record.tune>=2?'MAX TUNE':'TUNE  \u2B22 '+cost;tune.disabled=!unlocked||record.tune>=2||save.scrap<cost;tune.addEventListener('click',()=>tuneBlueprint(id));actions.append(equip,tune);entry.appendChild(actions);ui.blueprintGrid.appendChild(entry);
    }
    let stats=[['RUNS',save.stats.runs],['EXTRACTED',save.stats.extractions],['WARDENS',save.stats.bosses],['SCRAP BANKED',save.stats.totalScrap]];ui.careerStats.innerHTML='';for(const pair of stats){let d=document.createElement('div');d.innerHTML='<span>'+pair[0]+'</span><b>'+pair[1]+'</b>';ui.careerStats.appendChild(d)}
  }
  function openBlueprints(){renderBlueprints();ui.blueprintOverlay.classList.add('show')}
  function closeBlueprints(){ui.blueprintOverlay.classList.remove('show');refreshBase()}
  function equipStarter(id){save.starter=id;persist();renderBlueprints();refreshBase();sound('pickup')}
  function tuneBlueprint(id){let record=save.blueprints[id],cost=tuneCost(id);if(blueprintTier(id)<1||record.tune>=2||save.scrap<cost)return;save.scrap-=cost;record.tune++;persist();refreshBase();renderBlueprints();notice(MODULES[id].name.toUpperCase()+' TUNED','#f2c14f');sound('upgrade')}

  function requestStart(){if(!save.seenIntro)ui.briefingOverlay.classList.add('show');else startRun()}
  function completeBriefing(){save.seenIntro=true;persist();ui.briefingOverlay.classList.remove('show');startRun()}
  function updateCargoHud(){ui.cargoSlots.innerHTML='';for(let i=0;i<3;i++){let slot=document.createElement('div'),m=cargo[i];slot.className='cargoSlot'+(m?' filled':'')+(m&&m.rare?' rare':'');slot.textContent=m?MODULES[m.id].icon:'\u00B7';slot.title=m?(m.starter?'Starter ':'')+(m.rare?'Rare ':'')+MODULES[m.id].name:'Empty cargo slot';ui.cargoSlots.appendChild(slot)}}
  function applyCargoEffects(newModule){if(!player)return;let oldMax=player.maxHp||maxHp(),stats=cargoStats();player.maxHp=Math.max(40,Math.floor(maxHp()*stats.hp));player.hp=Math.min(player.maxHp,Math.max(1,player.hp*(player.maxHp/oldMax)));if(newModule&&newModule.id==='plating')player.shields=Math.min(stats.shields,(player.shields||0)+Math.max(1,Math.floor(newModule.power||(newModule.rare?2:1))));else player.shields=Math.min(stats.shields,player.shields||0);updateCargoHud();updateHud()}
  function startRun(){
    cargo=[];if(save.starter)cargo.push({id:save.starter,rare:false,starter:true,power:starterPower(save.starter)});
    player={x:WORLD.w/2,y:WORLD.h/2,r:18,hp:maxHp(),maxHp:maxHp(),speed:235,fire:0,inv:0,angle:0,dashCd:0,dashTime:0,dashX:1,dashY:0,lastX:1,lastY:0,shields:0};
    enemies=[];bullets=[];enemyBullets=[];scraps=[];particles=[];decor=[];caches=[];elapsed=0;spawnClock=.5;runScrap=0;depth=1;riskTier=0;decision=false;moduleDecision=false;depthPulse=0;extracting=0;shake=0;flash=0;paused=false;bossActive=false;bossDefeated=false;bossEntity=null;
    for(let i=0;i<78;i++)decor.push({x:80+Math.random()*(WORLD.w-160),y:80+Math.random()*(WORLD.h-160),r:8+Math.random()*24,type:Math.floor(Math.random()*4),rot:Math.random()*6});for(let i=0;i<18;i++)spawnScrap(100+Math.random()*(WORLD.w-200),100+Math.random()*(WORLD.h-200),1+Math.floor(Math.random()*3),false);
    spawnCache(player.x+190,player.y+25,false,false);ui.extractOverlay.classList.remove('show');ui.riskOverlay.classList.remove('show');ui.moduleOverlay.classList.remove('show');ui.resultOverlay.classList.remove('show');ui.bossHud.classList.remove('show');ui.settingsOverlay.classList.remove('show');setView('run');applyCargoEffects(cargo[0]);updateCargoHud();updateRouteHud();updateHud();save.stats.runs++;persist();if(save.starter)runNotice(MODULES[save.starter].name.toUpperCase()+' ONLINE','#47c5b6');sound('start')
  }

  function showResult(survived,scrapAmount,reached,modules,newRecord,status){
    ui.resultPanel.classList.toggle('lost',!survived);ui.resultTitle.textContent=status||(survived?'CARGO SECURED':'CARGO LOST');ui.resultScrap.textContent=survived?scrapAmount:'0';ui.resultDepth.textContent=reached;ui.resultRecord.textContent=newRecord?'NEW DEPTH RECORD':'';ui.resultModules.innerHTML='';
    let recovered=modules.filter(m=>!m.starter);if(!recovered.length){let empty=document.createElement('span');empty.className='resultModule';empty.textContent=survived?'No field modules recovered':'Cargo hold empty';ui.resultModules.appendChild(empty)}for(const m of recovered){let chip=document.createElement('span');chip.className='resultModule'+(survived?'':' lost');chip.textContent=(m.rare?'RARE ':'')+MODULES[m.id].name;ui.resultModules.appendChild(chip)}ui.resultOverlay.classList.add('show');
  }
  function returnBase(survived,status){
    let reportScrap=runScrap,reportDepth=depth,reportCargo=cargo.map(m=>Object.assign({},m)),newRecord=survived&&depth>save.best;if(survived){save.scrap+=runScrap;save.best=Math.max(save.best,depth);save.stats.extractions++;save.stats.totalScrap+=runScrap;for(const m of cargo){if(m.starter)continue;let record=save.blueprints[m.id];record.copies+=m.rare?2:1;if(m.rare)record.rare++}notice('+'+runScrap+' SCRAP SECURED','#47c5b6')}else{save.stats.losses++;notice(runScrap+' SCRAP LOST','#ef5350')}persist();
    decision=false;moduleDecision=false;extracting=0;bossActive=false;paused=false;stick.active=false;stick.x=stick.y=0;ui.knob.style.transform='';ui.riskOverlay.classList.remove('show');ui.moduleOverlay.classList.remove('show');ui.extractOverlay.classList.remove('show');ui.bossHud.classList.remove('show');ui.settingsOverlay.classList.remove('show');setView('base');refreshBase();showResult(survived,reportScrap,reportDepth,reportCargo,newRecord,status)
  }
  function beginExtract(){if(mode!=='run'||extracting||decision||moduleDecision||paused)return;extracting=3.25;ui.extractOverlay.classList.add('show');runNotice('KEEP MOVING UNTIL EXTRACTION','#47c5b6');sound('pickup')}
  function cancelExtract(){extracting=0;ui.extractOverlay.classList.remove('show')}
  function showRiskDecision(){decision=true;ui.riskScrap.textContent=runScrap;ui.nextMultiplier.textContent='x'+lootMultiplier(riskTier+1).toFixed(2);ui.riskOverlay.classList.add('show');sound('upgrade')}
  function pushDeeper(){if(!decision)return;decision=false;riskTier++;ui.riskOverlay.classList.remove('show');depthPulse=1.15;spawnEnemy(true);for(let i=0;i<Math.min(4,1+riskTier);i++)spawnEnemy(false,'rusher');shake=Math.max(shake,7);runNotice('RISK MULTIPLIER INCREASED','#f2c14f');sound('start');updateHud()}
  function extractFromRisk(){if(!decision)return;decision=false;ui.riskOverlay.classList.remove('show');beginExtract()}
  function tryDash(){if(mode!=='run'||decision||moduleDecision||paused||!player||player.dashCd>0)return;let move=movement(),dx=move.x||player.lastX||Math.cos(player.angle),dy=move.y||player.lastY||Math.sin(player.angle),l=Math.hypot(dx,dy)||1;player.dashX=dx/l;player.dashY=dy/l;player.dashTime=.16;player.dashCd=2.2;player.inv=Math.max(player.inv,.24);shake=Math.max(shake,3);burst(player.x,player.y,'#47c5b6',10,.8);sound('pickup')}

  function spawnEnemy(elite,forcedType){
    if(enemies.length>=LIMITS.enemies)return;let x=player.x,y=player.y;for(let tries=0;tries<8;tries++){let a=Math.random()*Math.PI*2,d=500+Math.random()*250;x=Math.max(35,Math.min(WORLD.w-35,player.x+Math.cos(a)*d));y=Math.max(35,Math.min(WORLD.h-35,player.y+Math.sin(a)*d));if(Math.hypot(x-player.x,y-player.y)>370)break}
    let roll=Math.random(),type=forcedType||(depth>=3&&roll<.23?'brute':depth>=2&&roll<.48?'shooter':'rusher'),base=type==='brute'?{r:24,hp:42,speed:52,damage:17}:{r:type==='shooter'?17:15,hp:type==='shooter'?22:15,speed:type==='shooter'?68:105,damage:type==='shooter'?9:10},scale=1+(depth-1)*.15+riskTier*.1;enemies.push({x,y,r:base.r*(elite?1.18:1),hp:base.hp*scale*(elite?2.15:1),max:base.hp*scale*(elite?2.15:1),speed:base.speed*(1+depth*.016)*(elite?1.06:1),damage:base.damage*(elite?1.3:1),hit:0,attack:0,fire:.9+Math.random(),charge:0,type,elite:!!elite,angle:0,strafe:Math.random()<.5?-1:1,anim:0})
  }
  function startBoss(){
    bossActive=true;extracting=0;ui.extractOverlay.classList.remove('show');enemies=[];enemyBullets=[];let a=Math.random()*Math.PI*2,x=Math.max(80,Math.min(WORLD.w-80,player.x+Math.cos(a)*390)),y=Math.max(80,Math.min(WORLD.h-80,player.y+Math.sin(a)*390)),hp=500+riskTier*105;bossEntity={x,y,r:43,hp,max:hp,speed:43,damage:19+riskTier*2,hit:0,attack:0,fire:1.45,charge:0,type:'boss',boss:true,elite:true,angle:0,strafe:1,phase:0,anim:0};enemies.push(bossEntity);ui.bossHud.classList.add('show');ui.bossHealthFill.style.width='100%';depthPulse=1.2;shake=Math.max(shake,10);runNotice('SCRAP WARDEN ENGAGED','#ef5350');sound('boss')
  }
  function defeatBoss(e){let bounty=Math.ceil(30*lootMultiplier());bossActive=false;bossDefeated=true;bossEntity=null;runScrap+=bounty;save.stats.bosses++;persist();ui.bossHud.classList.remove('show');enemyBullets=[];for(const other of enemies)if(other!==e)other.dead=true;burst(e.x,e.y,'#f2c14f',42,2);shake=Math.max(shake,14);flash=.06;sound('rare');runNotice('WARDEN DOWN  +'+bounty+' SCRAP','#f2c14f');spawnCache(player.x,player.y,true,true)}
  function spawnScrap(x,y,value,scatter){if(scraps.length>=LIMITS.scraps)return;scraps.push({x:x+(scatter?(Math.random()-.5)*24:0),y:y+(scatter?(Math.random()-.5)*24:0),r:7,value,spin:Math.random()*6,vx:scatter?(Math.random()-.5)*110:0,vy:scatter?(Math.random()-.5)*110:0})}
  function spawnCache(x,y,rare,bossReward){caches.push({x,y,r:19,rare:!!rare,bossReward:!!bossReward,spin:Math.random()*6,opened:false})}
  function burst(x,y,color,count,power){if(!save.settings.particles)return;count=Math.min(count,LIMITS.particles-particles.length);for(let i=0;i<count;i++){let a=Math.random()*Math.PI*2,s=(20+Math.random()*80)*(power||1);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.35,max:.6,r:1.5+Math.random()*3,color})}}

  function randomModule(exclude,forceRare){let pool=MODULE_IDS.filter(id=>!exclude.includes(id)),id=pool[Math.floor(Math.random()*pool.length)];return {id,rare:!!forceRare||Math.random()<Math.min(.07+depth*.03,.24)}}
  function openModuleCache(cache){if(moduleDecision)return;moduleDecision=true;activeCache=cache;moduleStage='offer';let first=randomModule([],cache.rare),second=randomModule([first.id],cache.bossReward);moduleOffer=[first,second];renderModuleOffer();ui.moduleOverlay.classList.add('show');sound(cache.rare?'rare':'upgrade')}
  function moduleCard(module,onClick){let def=MODULES[module.id],button=document.createElement('button');button.className='moduleCard'+(module.rare?' rare':'');button.innerHTML='<i class="moduleIcon">'+def.icon+'</i><strong>'+def.name+'</strong><span>'+def.desc+'</span><em>'+(module.rare?'RARE &middot; DOUBLE POWER':'FIELD MODULE')+'</em>';button.addEventListener('click',onClick);return button}
  function renderModuleOffer(){moduleStage='offer';pendingModule=null;ui.moduleEyebrow.textContent=activeCache&&activeCache.bossReward?'BOSS SALVAGE':'SALVAGE CACHE';ui.moduleTitle.textContent='CHOOSE A MODULE';ui.moduleSkip.textContent='LEAVE IT';ui.moduleChoices.innerHTML='';for(const m of moduleOffer)ui.moduleChoices.appendChild(moduleCard(m,()=>chooseModule(m)))}
  function chooseModule(module){if(cargo.length<3){cargo.push(module);applyCargoEffects(module);finishModuleChoice();return}moduleStage='replace';pendingModule=module;ui.moduleEyebrow.textContent='CARGO FULL';ui.moduleTitle.textContent='REPLACE WHICH MODULE?';ui.moduleSkip.textContent='BACK';ui.moduleChoices.innerHTML='';cargo.forEach((m,index)=>ui.moduleChoices.appendChild(moduleCard(m,()=>replaceModule(index))))}
  function replaceModule(index){cargo[index]=pendingModule;applyCargoEffects(pendingModule);finishModuleChoice()}
  function finishModuleChoice(){let bossReward=activeCache&&activeCache.bossReward,chosen=pendingModule;moduleDecision=false;pendingModule=null;activeCache=null;ui.moduleOverlay.classList.remove('show');if(chosen)runNotice(MODULES[chosen.id].name.toUpperCase()+' INSTALLED',chosen.rare?'#f2c14f':'#47c5b6');if(bossReward)setTimeout(()=>beginExtract(),220);sound('pickup')}
  function skipModule(){if(moduleStage==='replace'){renderModuleOffer();return}finishModuleChoice()}

  function movement(){let x=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0)+stick.x,y=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0)+stick.y,l=Math.hypot(x,y);return l>.05?{x:x/l,y:y/l}:{x:0,y:0}}
  function nearestEnemy(range){let best=null,dist=range*range;for(const e of enemies){let dx=e.x-player.x,dy=e.y-player.y,d=dx*dx+dy*dy;if(d<dist){dist=d;best=e}}return best}
  function damagePlayer(amount){if(player.inv>0)return false;if(player.shields>0){player.shields--;player.inv=.35;shake=Math.max(shake,4);burst(player.x,player.y,'#47c5b6',18,1.1);sound('shield');updateHud();return false}player.hp-=amount;player.inv=.6;shake=Math.max(shake,10);flash=.14;burst(player.x,player.y,'#ef5350',12,1);sound('hurt');if(player.hp<=0){player.hp=0;updateHud();returnBase(false,'RIG DESTROYED');return true}return false}
  function fireAt(target){let dx=target.x-player.x,dy=target.y-player.y,l=Math.hypot(dx,dy)||1,nx=dx/l,ny=dy/l,stats=cargoStats(),count=1+stats.burst;player.angle=Math.atan2(dy,dx);player.fire=Math.max(.13,Math.max(.22,.5-save.weapon*.014)*stats.fire);for(let i=0;i<count&&bullets.length<LIMITS.bullets;i++){let spread=(i-(count-1)/2)*.12,cs=Math.cos(spread),sn=Math.sin(spread),vx=nx*cs-ny*sn,vy=nx*sn+ny*cs;bullets.push({x:player.x+vx*24,y:player.y+vy*24,vx:vx*520,vy:vy*520,r:5,life:1.1,damage:shotDamage()*stats.damage})}sound('shoot')}
  function shootEnemy(e,nx,ny){if(enemyBullets.length>=LIMITS.enemyBullets)return;let speed=205+depth*5;enemyBullets.push({x:e.x+nx*22,y:e.y+ny*22,vx:nx*speed,vy:ny*speed,r:e.elite?8:6,life:3.4,damage:e.damage});sound('shoot')}
  function bossVolley(e,nx,ny){let shots=e.hp/e.max<.5?12:8,speed=e.hp/e.max<.5?188:162;for(let i=0;i<shots&&enemyBullets.length<LIMITS.enemyBullets;i++){let a=i*Math.PI*2/shots+e.phase;enemyBullets.push({x:e.x+Math.cos(a)*e.r,y:e.y+Math.sin(a)*e.r,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:7,life:4,damage:e.damage*.62})}for(let i=-1;i<=1&&enemyBullets.length<LIMITS.enemyBullets;i++){let a=Math.atan2(ny,nx)+i*.18;enemyBullets.push({x:e.x+nx*e.r,y:e.y+ny*e.r,vx:Math.cos(a)*232,vy:Math.sin(a)*232,r:8,life:4,damage:e.damage})}e.phase+=.37;shake=Math.max(shake,4);sound('boss')}

  function update(dt){
    if(mode!=='run'||decision||moduleDecision||paused)return;if(!bossActive&&!bossDefeated)elapsed+=dt;let nextDepth=Math.min(5,1+Math.floor(elapsed/DEPTH_SECONDS));if(nextDepth>depth){depth=nextDepth;depthPulse=1.15;sound('upgrade');updateRouteHud();if(depth===5){startBoss();updateHud()}else{let a=Math.random()*Math.PI*2,d=300+Math.random()*180;spawnCache(Math.max(40,Math.min(WORLD.w-40,player.x+Math.cos(a)*d)),Math.max(40,Math.min(WORLD.h-40,player.y+Math.sin(a)*d)),depth>=3&&Math.random()<.15+depth*.06,false);if(!extracting&&depth%2===0){showRiskDecision();updateHud();return}}}
    let move=movement(),stats=cargoStats();player.inv=Math.max(0,player.inv-dt);player.fire-=dt;player.dashCd=Math.max(0,player.dashCd-dt);if(player.dashTime>0){player.dashTime-=dt;player.x+=player.dashX*820*dt;player.y+=player.dashY*820*dt;if(save.settings.particles&&Math.random()<.65)particles.push({x:player.x-player.dashX*18,y:player.y-player.dashY*18,vx:-player.dashX*40,vy:-player.dashY*40,life:.22,max:.22,r:7,color:'#47c5b6'})}else{player.x+=move.x*player.speed*stats.speed*dt;player.y+=move.y*player.speed*stats.speed*dt;if(move.x||move.y){player.lastX=move.x;player.lastY=move.y;player.angle=Math.atan2(move.y,move.x)}}player.x=Math.max(player.r,Math.min(WORLD.w-player.r,player.x));player.y=Math.max(player.r,Math.min(WORLD.h-player.r,player.y));
    spawnClock-=dt;let interval=Math.max(.3,1.18-depth*.065-riskTier*.035);if(!bossActive&&!bossDefeated&&spawnClock<=0){spawnClock=interval*(.75+Math.random()*.5);spawnEnemy()}
    let target=nearestEnemy(430);if(target&&player.fire<=0)fireAt(target);
    for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of enemies){if(e.dead||b.dead)continue;let dx=e.x-b.x,dy=e.y-b.y;if(dx*dx+dy*dy<(e.r+b.r)*(e.r+b.r)){e.hp-=b.damage;e.hit=.12;b.dead=true;burst(b.x,b.y,e.boss?'#ff9b6d':'#f2c14f',e.boss?8:5,.7);sound('hit');if(e.boss)ui.bossHealthFill.style.width=Math.max(0,e.hp/e.max*100)+'%';if(e.hp<=0){e.dead=true;if(e.boss)defeatBoss(e);else{shake=Math.max(shake,e.elite?7:3);let reward=(e.type==='brute'?4:e.type==='shooter'?2:1)+(e.elite?7:0)+Math.floor((depth-1)*.22);for(let i=0;i<reward;i++)spawnScrap(e.x,e.y,1,true);burst(e.x,e.y,e.elite?'#f2c14f':e.type==='brute'?'#d7863b':'#ef5350',e.elite?22:11,e.elite?1.4:1)}}}}}bullets=bullets.filter(b=>!b.dead&&b.life>0);
    for(const e of enemies){if(e.dead)continue;e.anim=(e.anim||0)+dt;e.hit=Math.max(0,e.hit-dt);e.attack=Math.max(0,e.attack-dt);e.fire-=dt;let dx=player.x-e.x,dy=player.y-e.y,l=Math.hypot(dx,dy)||1,nx=dx/l,ny=dy/l;e.angle=Math.atan2(dy,dx);if(e.boss){let desired=275,approach=l>desired+35?1:l<desired-45?-1:0;e.x+=(nx*approach-ny*.42)*e.speed*dt;e.y+=(ny*approach+nx*.42)*e.speed*dt;if(e.charge>0){e.charge-=dt;if(e.charge<=0)bossVolley(e,nx,ny)}else if(e.fire<=0){e.charge=.72;e.fire=e.hp/e.max<.5?1.75:2.3}}else if(e.type==='shooter'){let approach=l>315?1:l<205?-1:0;e.x+=(nx*approach-ny*.48*e.strafe)*e.speed*dt;e.y+=(ny*approach+nx*.48*e.strafe)*e.speed*dt;if(e.charge>0){e.charge-=dt;if(e.charge<=0)shootEnemy(e,nx,ny)}else if(e.fire<=0){e.charge=.48;e.fire=Math.max(.9,2.25-depth*.05-riskTier*.07)}}else{e.x+=nx*e.speed*dt;e.y+=ny*e.speed*dt}if(l<e.r+player.r+3&&e.attack<=0){e.attack=.72;if(damagePlayer(e.damage))return}}enemies=enemies.filter(e=>!e.dead);
    for(const b of enemyBullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let dx=b.x-player.x,dy=b.y-player.y;if(dx*dx+dy*dy<(b.r+player.r)*(b.r+player.r)){b.dead=true;if(damagePlayer(b.damage))return}}enemyBullets=enemyBullets.filter(b=>!b.dead&&b.life>0&&b.x>-30&&b.y>-30&&b.x<WORLD.w+30&&b.y<WORLD.h+30);
    const magnet=magnetRange()+stats.magnet;for(const s of scraps){s.spin+=dt*4;s.x+=s.vx*dt;s.y+=s.vy*dt;s.vx*=Math.pow(.02,dt);s.vy*=Math.pow(.02,dt);let dx=player.x-s.x,dy=player.y-s.y,l=Math.hypot(dx,dy)||1;if(l<magnet){let pull=(1-l/magnet)*820;s.x+=dx/l*pull*dt;s.y+=dy/l*pull*dt}if(l<player.r+s.r+5){s.dead=true;runScrap+=Math.max(1,Math.ceil(s.value*lootMultiplier()));burst(s.x,s.y,'#47c5b6',5,.45);sound('pickup')}}scraps=scraps.filter(s=>!s.dead);
    for(const c of caches){c.spin+=dt*1.4;let dx=player.x-c.x,dy=player.y-c.y,l=Math.hypot(dx,dy)||1;if(l<magnet*.72){let pull=(1-l/(magnet*.72))*320;c.x+=dx/l*pull*dt;c.y+=dy/l*pull*dt}if(l<player.r+c.r+7){c.opened=true;burst(c.x,c.y,c.rare?'#f2c14f':'#47c5b6',c.rare?28:16,c.rare?1.4:1);openModuleCache(c);break}}caches=caches.filter(c=>!c.opened);
    for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.06,dt);p.vy*=Math.pow(.06,dt);p.life-=dt}particles=particles.filter(p=>p.life>0);shake*=Math.pow(.02,dt);flash=Math.max(0,flash-dt);depthPulse=Math.max(0,depthPulse-dt);
    if(extracting>0){extracting-=dt;ui.extractCount.textContent=Math.max(1,Math.ceil(extracting));if(extracting<=0){ui.extractOverlay.classList.remove('show');returnBase(true);return}}updateHud();
  }

  function camera(){return{x:Math.max(W/2,Math.min(WORLD.w-W/2,player.x)),y:Math.max(H/2,Math.min(WORLD.h-H/2,player.y))}}
  function worldToScreen(x,y,cam){return{x:x-cam.x+W/2,y:y-cam.y+H/2}}
  function roundedRect(x,y,w,h,r){ctx.beginPath();if(ctx.roundRect){ctx.roundRect(x,y,w,h,r);return}r=Math.min(r,w/2,h/2);ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
  function drawGear(x,y,r,rot,color){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.fillStyle=color;for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillRect(r*.72,-r*.14,r*.42,r*.28)}ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#131719';ctx.beginPath();ctx.arc(0,0,r*.38,0,Math.PI*2);ctx.fill();ctx.restore()}
  function drawCache(c,cam){let p=worldToScreen(c.x,c.y,cam),color=c.rare?'#f2c14f':'#47c5b6';ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.sin(c.spin)*.06);ctx.shadowColor=color;ctx.shadowBlur=c.rare?20:10;ctx.fillStyle='#273034';ctx.strokeStyle=color;ctx.lineWidth=3;roundedRect(-20,-16,40,32,5);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=color;ctx.fillRect(-4,-9,8,18);ctx.fillRect(-13,-3,26,6);ctx.fillStyle='#0d1416';ctx.beginPath();ctx.arc(0,0,4,0,Math.PI*2);ctx.fill();ctx.restore()}
  function draw(){
    if(mode!=='run')return;ctx.clearRect(0,0,W,H);let cam=camera(),shakeNow=save.settings.shake?shake:0,sx=(Math.random()-.5)*shakeNow,sy=(Math.random()-.5)*shakeNow;ctx.save();ctx.translate(sx,sy);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#20292a');g.addColorStop(1,'#101516');ctx.fillStyle=g;ctx.fillRect(-10,-10,W+20,H+20);
    let grid=80,ox=(-cam.x+W/2)%grid,oy=(-cam.y+H/2)%grid;ctx.strokeStyle='#75808412';ctx.lineWidth=1;for(let x=ox;x<W;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=oy;y<H;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
    for(const d of decor){let p=worldToScreen(d.x,d.y,cam);if(p.x<-60||p.x>W+60||p.y<-60||p.y>H+60)continue;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(d.rot);if(d.type===0)drawGear(0,0,d.r,d.rot,'#3d4547');else if(d.type===1){ctx.fillStyle='#463425';ctx.fillRect(-d.r,-d.r*.55,d.r*2,d.r*1.1);ctx.strokeStyle='#72543a';ctx.strokeRect(-d.r,-d.r*.55,d.r*2,d.r*1.1)}else if(d.type===2){ctx.strokeStyle='#48575a';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,d.r,-2.5,1.4);ctx.stroke()}else{ctx.fillStyle='#2b3437';ctx.beginPath();ctx.moveTo(-d.r,d.r);ctx.lineTo(0,-d.r);ctx.lineTo(d.r,d.r);ctx.fill()}ctx.restore()}
    for(const c of caches)drawCache(c,cam);for(const s of scraps){let p=worldToScreen(s.x,s.y,cam);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(s.spin);ctx.fillStyle='#4bd5c3';ctx.strokeStyle='#172a29';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<6;i++){let a=i*Math.PI/3;ctx.lineTo(Math.cos(a)*s.r,Math.sin(a)*s.r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#dffbf5';ctx.fillRect(-1,-4,2,5);ctx.restore()}
    for(const b of bullets){let p=worldToScreen(b.x,b.y,cam);ctx.strokeStyle='#f2c14f66';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(p.x-b.vx*.025,p.y-b.vy*.025);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.fillStyle='#fff2ac';ctx.beginPath();ctx.arc(p.x,p.y,b.r,0,Math.PI*2);ctx.fill()}for(const b of enemyBullets){let p=worldToScreen(b.x,b.y,cam);ctx.strokeStyle='#ef535055';ctx.lineWidth=b.r*1.2;ctx.beginPath();ctx.moveTo(p.x-b.vx*.04,p.y-b.vy*.04);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.fillStyle='#ff6b62';ctx.beginPath();ctx.arc(p.x,p.y,b.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd0b0';ctx.beginPath();ctx.arc(p.x-2,p.y-2,b.r*.35,0,Math.PI*2);ctx.fill()}
    for(const e of enemies){let p=worldToScreen(e.x,e.y,cam);if(e.charge>0){let aim=worldToScreen(player.x,player.y,cam);ctx.strokeStyle='rgba(239,83,80,'+(.25+(.72-e.charge)*.75)+')';ctx.lineWidth=e.boss?3:2;ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([])}ctx.save();ctx.translate(p.x,p.y);ctx.rotate(e.angle);if(e.boss){ctx.rotate(-e.angle+(e.anim||0)*.5);ctx.strokeStyle='#ef535088';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,e.r*1.25,0,Math.PI*2);ctx.stroke();drawGear(0,0,e.r,(e.anim||0)*.8,e.hit?'#fff0c2':'#7d382d');ctx.fillStyle=e.charge>0?'#fff0c2':'#ef5350';ctx.beginPath();ctx.arc(0,0,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1a0c0c';ctx.beginPath();ctx.arc(0,0,6,0,Math.PI*2);ctx.fill()}else{if(e.elite){ctx.strokeStyle='#f2c14f88';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,e.r*1.45,0,Math.PI*2);ctx.stroke()}ctx.fillStyle=e.hit?'#fff0c2':e.type==='brute'?'#7d482d':e.type==='shooter'?'#49324e':'#642f2d';ctx.strokeStyle=e.elite?'#f2c14f':'#101315';ctx.lineWidth=4;if(e.type==='shooter'){ctx.beginPath();ctx.moveTo(e.r,0);ctx.lineTo(0,e.r*.82);ctx.lineTo(-e.r,0);ctx.lineTo(0,-e.r*.82);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#2a3032';ctx.fillRect(e.r*.3,-4,e.r*1.05,8);ctx.fillStyle=e.charge>0?'#fff0c2':'#ef5350';ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill()}else{roundedRect(-e.r,-e.r*.72,e.r*2,e.r*1.44,e.type==='brute'?8:5);ctx.fill();ctx.stroke();ctx.fillStyle='#ef5350';ctx.beginPath();ctx.arc(e.r*.35,-e.r*.18,e.elite?4.5:3.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2a3032';ctx.fillRect(-e.r*1.25,-4,e.r*.7,8);if(e.type==='brute')drawGear(-e.r*.55,0,e.r*.45,e.anim*2,'#a76a35')}}ctx.restore();let hp=Math.max(0,e.hp/e.max);if(!e.boss&&(hp<1||e.elite)){ctx.fillStyle='#2a1717';ctx.fillRect(p.x-e.r,p.y-e.r-11,e.r*2,4);ctx.fillStyle=e.elite?'#f2c14f':'#ef5350';ctx.fillRect(p.x-e.r,p.y-e.r-11,e.r*2*hp,4)}}
    let pp=worldToScreen(player.x,player.y,cam);ctx.save();ctx.translate(pp.x,pp.y);ctx.rotate(player.angle);if(player.inv>0&&player.dashTime<=0&&Math.floor(player.inv*16)%2===0)ctx.globalAlpha=.4;if(player.dashTime>0){ctx.strokeStyle='#47c5b6aa';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,player.r+6,0,Math.PI*2);ctx.stroke()}if(player.shields>0){ctx.strokeStyle='#7ff4e6aa';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,player.r+7,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#283438';ctx.strokeStyle='#0a0d0e';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#47c5b6';ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.fill();ctx.shadowColor='#47c5b6';ctx.shadowBlur=10;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#d7863b';ctx.fillRect(8,-5,22,10);ctx.fillStyle='#f2c14f';ctx.beginPath();ctx.arc(5,-7,3,0,Math.PI*2);ctx.arc(5,7,3,0,Math.PI*2);ctx.fill();ctx.restore();
    for(const p of particles){let q=worldToScreen(p.x,p.y,cam);ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(q.x-p.r/2,q.y-p.r/2,p.r,p.r)}ctx.globalAlpha=1;let vignette=ctx.createRadialGradient(W/2,H/2,Math.min(W,H)*.25,W/2,H/2,Math.max(W,H)*.72);vignette.addColorStop(.55,'#0000');vignette.addColorStop(1,'#0009');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);if(flash>0){ctx.fillStyle='rgba(239,83,80,'+(flash*1.8)+')';ctx.fillRect(0,0,W,H)}ctx.restore();
    if(depthPulse>0){let a=Math.min(1,depthPulse*1.8),scale=1+(1.15-depthPulse)*.08;ctx.save();ctx.globalAlpha=a;ctx.translate(W/2,H*.22);ctx.scale(scale,scale);ctx.textAlign='center';ctx.font='900 12px Segoe UI,Arial';ctx.fillStyle='#9aa5aa';ctx.fillText(depth===5?'WARDEN SIGNAL':'DESCENT',0,-13);ctx.font='900 34px Segoe UI,Arial';ctx.fillStyle=depth===5?'#ef5350':'#f2c14f';ctx.fillText(depth===5?'SCRAP WARDEN':'DEPTH '+depth,0,22);ctx.restore()}
    if(paused){ctx.fillStyle='#05090ba8';ctx.fillRect(0,0,W,H)}
  }

  function updateRouteHud(){let ticks=[...ui.routeTicks.children];ticks.forEach((tick,index)=>{let level=index+1;tick.className=level<depth||bossDefeated?'done':level===depth?(bossActive?'boss':'current'):''})}
  function updateHud(){let hp=Math.max(0,player?player.hp:0),max=player?player.maxHp:maxHp(),danger=depth+riskTier*2,mult=lootMultiplier();ui.healthText.textContent=Math.ceil(hp)+' / '+max+(player&&player.shields?'  \u25C6'+player.shields:'');ui.healthFill.style.width=(hp/max*100)+'%';ui.runScrap.textContent=runScrap;ui.depth.textContent=depth;let risk=bossActive?'BOSS':danger<3?'LOW':danger<7?'RISING':danger<11?'HIGH':'EXTREME';ui.risk.textContent=risk+' x'+mult.toFixed(1);ui.risk.style.color=bossActive?'#ef5350':danger<3?'#7ccf63':danger<7?'#f2c14f':'#ef5350';if(player){let ready=Math.max(0,1-player.dashCd/2.2);ui.dash.style.setProperty('--ready',ready*360+'deg');ui.dash.classList.toggle('cooling',player.dashCd>0)}updateRouteHud()}
  function loop(now){let dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}

  function buyUpgrade(type){let cost=upgradePrice(type);if(save.scrap<cost)return;save.scrap-=cost;save[type]++;persist();refreshBase();notice(type.toUpperCase()+' UPGRADED','#f2c14f');sound('upgrade')}
  function syncSettings(){for(const pair of [[ui.soundToggle,'sound'],[ui.shakeToggle,'shake'],[ui.particlesToggle,'particles']]){let on=save.settings[pair[1]];pair[0].classList.toggle('off',!on);pair[0].setAttribute('aria-checked',String(on));pair[0].querySelector('b').textContent=on?'ON':'OFF'}}
  function openSettings(){settingsWasRun=mode==='run';if(settingsWasRun)paused=true;abandonArmed=false;ui.abandon.textContent='ABANDON EXPEDITION';ui.abandon.classList.remove('confirm');ui.settingsPanel.classList.toggle('baseMode',!settingsWasRun);syncSettings();ui.settingsOverlay.classList.add('show')}
  function closeSettings(){ui.settingsOverlay.classList.remove('show');paused=false;abandonArmed=false;last=performance.now()}
  function toggleSetting(key){save.settings[key]=!save.settings[key];persist();syncSettings();if(key==='sound'&&save.settings.sound)sound('pickup')}
  function abandonRun(){if(!settingsWasRun)return;if(!abandonArmed){abandonArmed=true;ui.abandon.textContent='CONFIRM: LOSE RUN CARGO';ui.abandon.classList.add('confirm');return}returnBase(false,'EXPEDITION ABANDONED')}

  ui.start.addEventListener('click',requestStart);ui.briefingStart.addEventListener('click',completeBriefing);ui.blueprintButton.addEventListener('click',openBlueprints);ui.closeBlueprints.addEventListener('click',closeBlueprints);ui.closeResult.addEventListener('click',()=>ui.resultOverlay.classList.remove('show'));
  ui.extract.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();beginExtract()});ui.cancelExtract.addEventListener('click',cancelExtract);ui.riskExtract.addEventListener('click',extractFromRisk);ui.riskPush.addEventListener('click',pushDeeper);ui.moduleSkip.addEventListener('click',skipModule);
  ui.upgradeChassis.addEventListener('click',()=>buyUpgrade('chassis'));ui.upgradeWeapon.addEventListener('click',()=>buyUpgrade('weapon'));ui.upgradeSalvage.addEventListener('click',()=>buyUpgrade('salvage'));ui.dash.addEventListener('pointerdown',e=>{e.preventDefault();tryDash()});
  ui.settingsButton.addEventListener('click',openSettings);ui.closeSettings.addEventListener('click',closeSettings);ui.resume.addEventListener('click',closeSettings);ui.soundToggle.addEventListener('click',()=>toggleSetting('sound'));ui.shakeToggle.addEventListener('click',()=>toggleSetting('shake'));ui.particlesToggle.addEventListener('click',()=>toggleSetting('particles'));ui.abandon.addEventListener('click',abandonRun);
  window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'&&!e.repeat)tryDash();if(e.code==='KeyE'&&!e.repeat)beginExtract();if(e.code==='Escape'&&!e.repeat){if(ui.settingsOverlay.classList.contains('show'))closeSettings();else if(ui.blueprintOverlay.classList.contains('show'))closeBlueprints();else if(ui.resultOverlay.classList.contains('show'))ui.resultOverlay.classList.remove('show');else openSettings()}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('resize',resize);
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='run'&&!paused)openSettings()});
  function stickMove(e){let r=ui.joystick.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),m=r.width*.34,l=Math.hypot(x,y)||1,cl=Math.min(m,l);stick.x=x/l*(cl/m);stick.y=y/l*(cl/m);ui.knob.style.transform='translate('+(stick.x*m)+'px,'+(stick.y*m)+'px)'}
  ui.joystick.addEventListener('pointerdown',e=>{stick.active=true;stick.id=e.pointerId;ui.joystick.setPointerCapture(e.pointerId);stickMove(e)});ui.joystick.addEventListener('pointermove',e=>{if(stick.active&&e.pointerId===stick.id)stickMove(e)});function stickEnd(e){if(e.pointerId!==stick.id)return;stick.active=false;stick.x=stick.y=0;ui.knob.style.transform=''}ui.joystick.addEventListener('pointerup',stickEnd);ui.joystick.addEventListener('pointercancel',stickEnd);
  let lastTouchEnd=0,lastTouchTarget=null;document.addEventListener('touchend',e=>{let now=Date.now(),button=e.target.closest&&e.target.closest('button');if(now-lastTouchEnd<340&&e.target===lastTouchTarget){e.preventDefault();if(button&&!button.disabled)button.click()}lastTouchEnd=now;lastTouchTarget=e.target},{passive:false});for(const event of ['gesturestart','gesturechange','gestureend','dblclick'])document.addEventListener(event,e=>e.preventDefault(),{passive:false});document.addEventListener('contextmenu',e=>e.preventDefault());

  persist();refreshBase();updateCargoHud();syncSettings();setView('base');requestAnimationFrame(loop);
})();
