const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Classes{constructor(){this.s=new Set()}add(...n){n.forEach(x=>this.s.add(x))}remove(...n){n.forEach(x=>this.s.delete(x))}toggle(n,v){if(v===undefined)v=!this.s.has(n);v?this.s.add(n):this.s.delete(n);return v}contains(n){return this.s.has(n)}}
class Element{constructor(id){this.id=id;this.classList=new Classes();this.style={setProperty(k,v){this[k]=v}};this.listeners={};this.children=[];this.disabled=false;this.history=[];this.textContent='';this._html='';this.attributes={}}set textContent(v){this._text=String(v);if(this.history)this.history.push(this._text)}get textContent(){return this._text}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(n,fn){(this.listeners[n]||(this.listeners[n]=[])).push(fn)}appendChild(e){this.children.push(e);return e}append(...e){e.forEach(x=>this.appendChild(x))}setAttribute(k,v){this.attributes[k]=v}querySelector(q){if(q==='b')return this._b||(this._b=new Element('b'));return null}getBoundingClientRect(){return {left:0,top:0,width:960,height:540}}setPointerCapture(){}closest(){return null}click(){if(this.disabled)return;for(const fn of this.listeners.click||[])fn({preventDefault(){},stopPropagation(){},target:this})}getContext(){return context2d}}
const gradient={addColorStop(){}};const context2d=new Proxy({createLinearGradient(){return gradient},createRadialGradient(){return gradient},setTransform(){}},{get(o,k){return k in o?o[k]:(()=>{})},set(o,k,v){o[k]=v;return true}});
const html=fs.readFileSync('index.html','utf8'),elements={};for(const m of html.matchAll(/id="([^"]+)"/g))elements[m[1]]=new Element(m[1]);for(let i=0;i<5;i++)elements.routeTicks.appendChild(new Element('tick'+i));
const scene=new Element('scene'),resultPanel=new Element('resultPanel'),settingsPanel=new Element('settingsPanel'),documentListeners={},windowListeners={},raf=[];
const document={hidden:false,getElementById:id=>elements[id]||(elements[id]=new Element(id)),querySelector:q=>q==='.workshopScene'?scene:q==='.resultPanel'?resultPanel:q==='.settingsPanel'?settingsPanel:new Element(q),createElement:()=>new Element(),addEventListener:(n,fn)=>{(documentListeners[n]||(documentListeners[n]=[])).push(fn)}};
const rigLevel=Number(process.env.SMOKE_LEVEL==null?30:process.env.SMOKE_LEVEL);let saved=JSON.stringify({scrap:999999,best:2,chassis:rigLevel,weapon:rigLevel,salvage:rigLevel,cores:2,blueprints:{burst:2,burstRare:1,magnet:3,plating:2,overdrive:2,volatile:2}}),clock=0,seed=(Number(process.env.SMOKE_SEED)||1337)>>>0;
const seededMath=Object.create(Math);seededMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const sandbox={console,document,location:{hostname:'localhost'},localStorage:{getItem:()=>saved,setItem:(k,v)=>{saved=v}},performance:{now:()=>clock},requestAnimationFrame:fn=>{raf.push(fn)},setTimeout:fn=>{fn();return 1},clearTimeout(){},Math:seededMath,Date,JSON,window:null};sandbox.window=sandbox;sandbox.window.devicePixelRatio=1;sandbox.window.addEventListener=(n,fn)=>{(windowListeners[n]||(windowListeners[n]=[])).push(fn)};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('script.js','utf8'),sandbox);
let migrated=JSON.parse(saved);assert.equal(migrated.version,5,'save was not migrated');assert.equal(migrated.blueprints.burst.copies,2,'legacy blueprint copies were lost');assert.equal(migrated.cores,2,'warden cores were lost during migration');assert.equal(migrated.schematics.aegis,0,'legacy save received an unearned schematic');assert(migrated.playtest&&Array.isArray(migrated.playtest.runs),'playtest history was not migrated');
elements.blueprintButton.click();assert(elements.blueprintOverlay.classList.contains('show'),'blueprint bench did not open');assert.equal(elements.wardenTechGrid.children.length,3,'schematic bench did not render');let burstEntry=elements.blueprintGrid.children[0],actions=burstEntry.children[0];actions.children[0].click();assert(elements.starterName.textContent.includes('BURST CAPACITOR'),'starter module did not equip');elements.closeBlueprints.click();
elements.startButton.click();assert(elements.briefingOverlay.classList.contains('show'),'first-run briefing did not open');elements.briefingStart.click();assert(elements.expeditionView.classList.contains('active'),'run view did not open');assert(elements.cargoSlots.children[0].textContent!=='\u00B7','starter module missing from cargo');
const safeExtract=process.env.SAFE_EXTRACT==='1';function resolveOverlays(){if(elements.moduleOverlay.classList.contains('show'))elements.moduleChoices.children[0].click();if(elements.riskOverlay.classList.contains('show'))elements[safeExtract?'riskExtract':'riskPush'].click()}
function frame(){clock+=16.666;let callbacks=raf.splice(0);callbacks.forEach(fn=>fn(clock));resolveOverlays()}
(windowListeners.keydown||[]).forEach(fn=>fn({code:'KeyD',repeat:false,preventDefault(){}}));for(let i=0;i<85;i++)frame();(windowListeners.keyup||[]).forEach(fn=>fn({code:'KeyD'}));assert(elements.cargoSlots.children.filter(e=>e.textContent!=='\u00B7').length>=2,'field cache did not add a module');
let driveCode=null;function drive(i){let code=['KeyD','KeyS','KeyA','KeyW'][Math.floor(i/150)%4];if(code!==driveCode){if(driveCode)(windowListeners.keyup||[]).forEach(fn=>fn({code:driveCode}));driveCode=code;(windowListeners.keydown||[]).forEach(fn=>fn({code,repeat:false,preventDefault(){}}))}if(i%105===0){(windowListeners.keydown||[]).forEach(fn=>fn({code:'Space',repeat:false,preventDefault(){}}));(windowListeners.keyup||[]).forEach(fn=>fn({code:'Space'}))}}
for(let i=0;i<26000&&!elements.resultOverlay.classList.contains('show');i++){drive(i);frame()}if(driveCode)(windowListeners.keyup||[]).forEach(fn=>fn({code:driveCode}));assert(elements.resultOverlay.classList.contains('show'),'expedition did not reach a result (depth '+elements.depthText.textContent+', phase '+elements.bossPhaseText.textContent+', boss HP '+elements.bossHealthFill.style.width+')');assert.equal(elements.resultTitle.textContent,'CARGO SECURED','expedition did not secure cargo (depth '+elements.resultDepth.textContent+', time '+elements.resultTime.textContent+', kills '+elements.resultKills.textContent+')');assert(Number(elements.resultDepth.textContent)>=(safeExtract?2:5),safeExtract?'safe depth was not reached':'warden depth was not reached');assert(elements.baseView.classList.contains('active'),'workshop did not reopen');assert(Number(elements.resultKills.textContent)>0,'post-run kill count was not rendered');
migrated=JSON.parse(saved);assert(migrated.stats.runs>=1&&migrated.stats.extractions>=1,'career stats did not persist');assert(migrated.stats.totalTime>0&&migrated.stats.totalKills>0,'aggregate playtest stats did not persist');assert.equal(migrated.playtest.runs.length,1,'run history was not recorded');assert(Object.values(migrated.blueprints).reduce((sum,v)=>sum+v.copies,0)>11,'recovered modules did not persist');if(safeExtract){assert.equal(elements.resultDepth.textContent,'2','safe route did not extract at its first decision');assert(migrated.playtest.runs[0].time>=55,'safe route arrived before the intended pacing milestone');assert.equal(migrated.cores,2,'safe extraction incorrectly granted a core');assert.equal(migrated.schematics.aegis,0,'safe extraction incorrectly granted Warden tech');elements.closeResult.click()}else{assert(migrated.playtest.runs[0].time>=280,'warden route skipped the pacing curve');assert(migrated.stats.bosses>=1,'warden victory did not persist');assert.equal(migrated.cores,3,'warden core was not secured');assert.equal(migrated.schematics.aegis,1,'chosen Warden schematic did not persist');assert.equal(migrated.playtest.runs[0].warden,'aegis','Warden choice was not recorded');assert(elements.resultModules.children[0].textContent.includes('WARDEN SCHEMATIC'),'permanent boss reward was not shown in the report');assert.equal(migrated.contractComplete,true,'long-term contract was not completed');assert(elements.zoneName.history.includes('FURNACE WARD')&&elements.zoneName.history.includes('DYNAMO VAULT')&&elements.zoneName.history.includes('WARDEN CORE'),'zone progression did not render');assert(elements.bossPhaseText.history.some(v=>v.includes('PHASE II'))&&elements.bossPhaseText.history.some(v=>v.includes('PHASE III')),'warden phases did not trigger');elements.closeResult.click();assert(elements.contractOverlay.classList.contains('show'),'contract completion was not presented');elements.closeContract.click();assert.equal(JSON.parse(saved).contractSeen,true,'contract reward was not claimed');elements.blueprintButton.click();assert(elements.wardenTechGrid.children[0].className.includes('recovered'),'secured schematic was not visible at the bench');elements.closeBlueprints.click();elements.startButton.click();assert(elements.healthText.textContent.includes('\u25C61'),'Aegis Lattice did not grant its starting shield')}
elements.settingsButton.click();elements.devButton.click();assert(elements.devPanel.classList.contains('show'),'dev panel did not open');assert((elements.devWarden.listeners.click||[]).length===1,'Warden test shortcut was not wired');elements.soundToggle.click();elements.closeSettings.click();assert.equal(JSON.parse(saved).settings.sound,false,'settings did not persist');console.log('Release smoke passed in '+(clock/1000).toFixed(1)+' simulated seconds: migration -> bench -> briefing -> build -> '+(safeExtract?'safe extraction':'risk -> warden -> contract')+' -> dev tools -> settings');
