const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Classes{constructor(){this.s=new Set()}add(...n){n.forEach(x=>this.s.add(x))}remove(...n){n.forEach(x=>this.s.delete(x))}toggle(n,v){if(v===undefined)v=!this.s.has(n);v?this.s.add(n):this.s.delete(n);return v}contains(n){return this.s.has(n)}}
class Element{constructor(id){this.id=id;this.classList=new Classes();this.style={setProperty(k,v){this[k]=v}};this.listeners={};this.children=[];this.disabled=false;this.history=[];this.textContent='';this._html='';this.attributes={}}set textContent(v){this._text=String(v);if(this.history)this.history.push(this._text)}get textContent(){return this._text}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(n,fn){(this.listeners[n]||(this.listeners[n]=[])).push(fn)}appendChild(e){this.children.push(e);return e}append(...e){e.forEach(x=>this.appendChild(x))}setAttribute(k,v){this.attributes[k]=v}querySelector(q){if(q==='b')return this._b||(this._b=new Element('b'));return null}getBoundingClientRect(){return {left:0,top:0,width:960,height:540}}setPointerCapture(){}closest(){return null}click(){if(this.disabled)return;for(const fn of this.listeners.click||[])fn({preventDefault(){},stopPropagation(){},target:this})}getContext(){return context2d}}
const gradient={addColorStop(){}};const context2d=new Proxy({createLinearGradient(){return gradient},createRadialGradient(){return gradient},setTransform(){}},{get(o,k){return k in o?o[k]:(()=>{})},set(o,k,v){o[k]=v;return true}});
const html=fs.readFileSync('index.html','utf8'),elements={};for(const m of html.matchAll(/id="([^"]+)"/g))elements[m[1]]=new Element(m[1]);for(let i=0;i<5;i++)elements.routeTicks.appendChild(new Element('tick'+i));
const scene=new Element('scene'),resultPanel=new Element('resultPanel'),settingsPanel=new Element('settingsPanel'),documentListeners={},windowListeners={},raf=[];
const document={hidden:false,getElementById:id=>elements[id]||(elements[id]=new Element(id)),querySelector:q=>q==='.workshopScene'?scene:q==='.resultPanel'?resultPanel:q==='.settingsPanel'?settingsPanel:new Element(q),createElement:()=>new Element(),addEventListener:(n,fn)=>{(documentListeners[n]||(documentListeners[n]=[])).push(fn)}};
const rigLevel=Number(process.env.SMOKE_LEVEL==null?30:process.env.SMOKE_LEVEL);let saved=JSON.stringify({scrap:999999,best:2,chassis:rigLevel,weapon:rigLevel,salvage:rigLevel,cores:2,lootFound:{bentCog:2},blueprints:{burst:2,burstRare:1,magnet:3,plating:2,overdrive:2,volatile:2}}),clock=0,seed=(Number(process.env.SMOKE_SEED)||1337)>>>0;
const seededMath=Object.create(Math);seededMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const sandbox={console,document,location:{hostname:'localhost'},localStorage:{getItem:()=>saved,setItem:(k,v)=>{saved=v}},performance:{now:()=>clock},requestAnimationFrame:fn=>{raf.push(fn)},setTimeout:fn=>{fn();return 1},clearTimeout(){},Math:seededMath,Date,JSON,window:null};sandbox.window=sandbox;sandbox.window.devicePixelRatio=1;sandbox.window.addEventListener=(n,fn)=>{(windowListeners[n]||(windowListeners[n]=[])).push(fn)};
const gameSource=fs.readFileSync('script.js','utf8').replace(/\}\)\(\);\s*$/,'window.__blueprintTest={starterPowerAt,starterEffect,platingProtection,burstVolleyBonus,thermalBlast,fuseRelic,gearStats,gearScore,gearSellableCount,filteredGearSaleSummary,lootCatalogSize:LOOT_ITEMS.length,gearSlots:GEAR_SLOTS.slice(),gearVisualKeys:LOOT_ITEMS.map(item=>item.visual.key),lootCounts:Object.fromEntries(Object.keys(LOOT_RARITIES).map(rarity=>[rarity,LOOT_BY_RARITY[rarity].length]))};})();');vm.createContext(sandbox);vm.runInContext(gameSource,sandbox);
let migrated=JSON.parse(saved);assert.equal(migrated.version,8,'save was not migrated');assert.equal(migrated.blueprints.burst.copies,2,'legacy blueprint copies were lost');assert.equal(migrated.cores,2,'boss cores were lost during migration');assert.equal(migrated.schematics.aegis,0,'legacy save received an unearned schematic');assert.equal(migrated.schematics.thermal,0,'legacy save received unearned Tyrant tech');assert(migrated.playtest&&Array.isArray(migrated.playtest.runs),'playtest history was not migrated');assert.equal(Object.keys(migrated.lootFound).length,40,'loot collection was not migrated');assert.equal(Object.values(migrated.lootFound).reduce((sum,count)=>sum+count,0),2,'legacy loot collection was not preserved');assert.equal(migrated.gearInventory.bentCog.count,2,'legacy loot was not converted into gear');assert.equal(migrated.equipped.hat,'bentCog','best legacy gear was not equipped');assert.equal(Object.keys(migrated.equipped).length,5,'loadout slots were not migrated');
assert.equal(sandbox.__blueprintTest.lootCatalogSize,40,'loot catalog must contain exactly 40 items');assert.equal(sandbox.__blueprintTest.lootCounts.common,20,'common loot count is wrong');assert.equal(sandbox.__blueprintTest.lootCounts.rare,10,'rare loot count is wrong');assert.equal(sandbox.__blueprintTest.lootCounts.epic,5,'epic loot count is wrong');assert.equal(sandbox.__blueprintTest.lootCounts.mythic,3,'mythic loot count is wrong');assert.equal(sandbox.__blueprintTest.lootCounts.legendary,2,'legendary loot count is wrong');assert.equal(new Set(Array.from(sandbox.__blueprintTest.gearVisualKeys)).size,40,'all 40 gear items need distinct visual identities');
assert.deepEqual(sandbox.__blueprintTest.gearSlots,['hat','scarf','coat','hammer','boots'],'gear loadout slots are wrong');assert.equal(sandbox.__blueprintTest.gearStats().hp,5,'equipped legacy gear does not affect stats');
let fusedRelic={id:'burst',power:1,recoveries:0,rareRecoveries:0};assert.equal(sandbox.__blueprintTest.fuseRelic(fusedRelic,{id:'burst',power:2,recoveries:1,rareRecoveries:1,rare:true}),true,'matching rare relic did not fuse');assert.equal(fusedRelic.power,3,'rare relic did not add two power');assert.equal(fusedRelic.recoveries,1,'fused relic recovery was not counted');sandbox.__blueprintTest.fuseRelic(fusedRelic,{id:'burst',power:2,recoveries:1,rareRecoveries:1,rare:true});assert.equal(fusedRelic.power,4,'relic fusion did not respect the power cap');
assert.equal(sandbox.__blueprintTest.starterPowerAt(2,0),1.15,'MK II starter output is wrong');assert(sandbox.__blueprintTest.starterEffect('burst',1.15).includes('15% ECHO SHOT'),'fractional Burst mastery has no visible effect');assert(Math.abs(sandbox.__blueprintTest.platingProtection(1.3).armor-.12)<.0001,'fractional Plating mastery has no armor effect');assert.deepEqual(sandbox.__blueprintTest.thermalBlast(3),{charges:2,damage:1.5},'Thermal Capacitor rank III is wrong');let echoRig={burstCharge:0},echoShots=0;for(let i=0;i<10;i++)echoShots+=sandbox.__blueprintTest.burstVolleyBonus(1.15,echoRig);assert.equal(echoShots,11,'Burst echo accumulator did not produce its mastery shot');
elements.blueprintButton.click();assert(elements.blueprintOverlay.classList.contains('show'),'relic rack did not open');assert.equal(elements.wardenTechGrid.children.length,4,'boss trophy rack did not render');let burstEntry=elements.blueprintGrid.children[0],actions=burstEntry.children[0];assert(burstEntry.innerHTML.includes('LUCKY EFFECT')&&burstEntry.innerHTML.includes('2 / 3 RECOVERED'),'relic recovery and effect are not explained');assert(!burstEntry.innerHTML.includes('PICKS'),'internal pick telemetry leaked into the player-facing rack');actions.children[0].click();assert(elements.starterName.textContent.includes('HAMMER ECHO'),'lucky relic did not equip');let platingEntry=elements.blueprintGrid.children[2],platingActions=platingEntry.children[0];platingActions.children[1].click();assert(elements.blueprintGrid.children[2].innerHTML.includes('110% POWER')&&elements.blueprintGrid.children[2].innerHTML.includes('4% ARMOR'),'polish did not update the concrete Guard Charm effect');elements.closeBlueprints.click();
elements.gearLockerButton.click();assert(elements.gearOverlay.classList.contains('show'),'Gear Locker did not open');assert.equal(elements.gearLoadoutSlots.children.length,5,'Gear Locker did not render five slots');assert.equal(elements.gearRarityFilters.children.length,6,'rarity filters did not render');assert.equal(elements.gearCharacterPreview.children.length,0,'obsolete geometric gear leaked onto the animated character');assert(elements.gearLoadoutSlots.children[0].innerHTML.includes('gearArt'),'equipped atlas art is missing from the loadout slot');assert.equal(elements.gearGrid.children.length,1,'migrated gear did not render in the locker');assert(elements.gearGrid.children[0].innerHTML.includes('Guild Work Hat'),'gear card did not explain the recovered item');elements.gearRarityFilters.children[2].click();assert.equal(elements.gearGrid.children.length,0,'rare filter showed common gear');elements.gearRarityFilters.children[0].click();assert.equal(elements.gearGrid.children.length,1,'all-rarity filter did not restore inventory');let coinsBeforeSale=JSON.parse(saved).scrap;elements.sellFilteredGear.click();assert.equal(JSON.parse(saved).gearInventory.bentCog.count,2,'filtered sale skipped confirmation');elements.sellFilteredGear.click();assert.equal(JSON.parse(saved).gearInventory.bentCog.count,1,'filtered sale did not keep the equipped copy');assert.equal(JSON.parse(saved).equipped.hat,'bentCog','filtered sale removed equipped gear');assert(JSON.parse(saved).scrap>coinsBeforeSale,'filtered sale did not bank coins');let firstGearActions=elements.gearGrid.children[0].children[0];assert(firstGearActions.children[1].disabled,'equipped-only item was still sellable');firstGearActions.children[0].click();assert.equal(JSON.parse(saved).equipped.hat,null,'gear could not be unequipped');firstGearActions=elements.gearGrid.children[0].children[0];firstGearActions.children[0].click();assert.equal(JSON.parse(saved).equipped.hat,'bentCog','gear could not be re-equipped');assert.equal(elements.gearCharacterPreview.children.length,0,'geometric character overlays returned after equipping');elements.closeGear.click();
elements.startButton.click();assert(elements.briefingOverlay.classList.contains('show'),'first-run briefing did not open');elements.briefingStart.click();assert(elements.expeditionView.classList.contains('active'),'run view did not open');assert(elements.cargoSlots.children[0].textContent!=='\u00B7','starter module missing from cargo');
const safeExtract=process.env.SAFE_EXTRACT==='1',furnaceRoute=process.env.FURNACE_ROUTE==='1';function resolveOverlays(){if(elements.moduleOverlay.classList.contains('show'))elements.moduleChoices.children[0].click();if(elements.routeOverlay.classList.contains('show'))elements[furnaceRoute?'routeFurnace':'routeDynamo'].click();if(elements.riskOverlay.classList.contains('show'))elements[safeExtract?'riskExtract':'riskPush'].click()}
function frame(){clock+=16.666;let callbacks=raf.splice(0);callbacks.forEach(fn=>fn(clock));resolveOverlays()}
(windowListeners.keydown||[]).forEach(fn=>fn({code:'KeyD',repeat:false,preventDefault(){}}));for(let i=0;i<85;i++)frame();(windowListeners.keyup||[]).forEach(fn=>fn({code:'KeyD'}));assert(elements.cargoSlots.children.filter(e=>e.textContent!=='\u00B7').length>=2,'field cache did not add a module');
let driveCode=null;function drive(i){let code=['KeyD','KeyS','KeyA','KeyW'][Math.floor(i/150)%4];if(code!==driveCode){if(driveCode)(windowListeners.keyup||[]).forEach(fn=>fn({code:driveCode}));driveCode=code;(windowListeners.keydown||[]).forEach(fn=>fn({code,repeat:false,preventDefault(){}}))}if(i%105===0){(windowListeners.keydown||[]).forEach(fn=>fn({code:'Space',repeat:false,preventDefault(){}}));(windowListeners.keyup||[]).forEach(fn=>fn({code:'Space'}))}}
for(let i=0;i<28000&&!elements.resultOverlay.classList.contains('show');i++){drive(i);frame()}if(driveCode)(windowListeners.keyup||[]).forEach(fn=>fn({code:driveCode}));assert(elements.resultOverlay.classList.contains('show'),'expedition did not reach a result (floor '+elements.depthText.textContent+', phase '+elements.bossPhaseText.textContent+', boss HP '+elements.bossHealthFill.style.width+')');assert.equal(elements.resultTitle.textContent,'GEAR SECURED','expedition did not secure gear (floor '+elements.resultDepth.textContent+', time '+elements.resultTime.textContent+', kills '+elements.resultKills.textContent+')');assert(Number(elements.resultDepth.textContent)>=(safeExtract?2:5),safeExtract?'safe floor was not reached':'boss floor was not reached');assert(elements.baseView.classList.contains('active'),'workshop did not reopen');assert(Number(elements.resultKills.textContent)>0,'post-run kill count was not rendered');assert(Number(elements.resultItems.textContent)>0,'recovered item count was not rendered');assert(elements.resultLoot.children.length>0,'recovered gear was not rendered');
migrated=JSON.parse(saved);
assert(migrated.stats.runs>=1&&migrated.stats.extractions>=1,'career stats did not persist');
assert(migrated.stats.totalTime>0&&migrated.stats.totalKills>0,'aggregate playtest stats did not persist');
assert(migrated.stats.itemsRecovered>0,'recovered items did not persist');
assert(Object.values(migrated.lootFound).some(count=>count>0),'loot collection contains no recovered items');
assert(Object.values(migrated.gearInventory).some(record=>record.count>0),'recovered gear did not persist in the inventory');
assert.equal(migrated.playtest.runs.length,1,'run history was not recorded');
assert(migrated.playtest.runs[0].items>0,'run history did not record item recovery');
assert(Object.values(migrated.blueprints).reduce((sum,v)=>sum+v.copies,0)>11,'recovered relics did not persist');
if(safeExtract){
  assert.equal(elements.resultDepth.textContent,'2','safe path did not extract at its first decision');
  assert(migrated.playtest.runs[0].time>=55,'safe path arrived before the intended pacing milestone');
  assert.equal(migrated.cores,2,'safe extraction incorrectly granted a boss seal');
  assert.equal(migrated.schematics.aegis,0,'safe extraction incorrectly granted a boss trophy');
  elements.closeResult.click();
}else{
  let expectedRoute=furnaceRoute?'furnace':'dynamo',expectedReward=furnaceRoute?'thermal':'aegis';
  assert(migrated.playtest.runs[0].time>=280,'boss path skipped the pacing curve');
  assert(migrated.stats.bosses>=1,'boss victory did not persist');
  assert.equal(migrated.cores,3,'boss seal was not secured');
  assert.equal(migrated.schematics[expectedReward],1,'chosen boss trophy did not persist');
  assert.equal(migrated.playtest.runs[0].warden,expectedReward,'boss reward choice was not recorded');
  assert.equal(migrated.playtest.runs[0].route,expectedRoute,'path choice was not recorded');
  assert(elements.resultModules.children[0].textContent.includes('BOSS TROPHY'),'permanent boss trophy was not shown in the report');
  assert.equal(migrated.contractComplete,true,'long-term contract was not completed');
  if(furnaceRoute){
    assert(elements.zoneName.history.includes('RED BANNER YARD')&&elements.zoneName.history.includes('EMBER COURT')&&elements.zoneName.history.includes("CHAMPION'S HALL"),'Crimson Path zones did not render');
    assert(elements.bossName.history.includes('CRIMSON CHAMPION'),'Crimson Champion did not render');
  }else{
    assert(elements.zoneName.history.includes('LANTERN GALLERY')&&elements.zoneName.history.includes('MOON VAULT')&&elements.zoneName.history.includes("WARDEN'S KEEP"),'Moonlit Path zones did not render');
    assert(elements.bossName.history.includes('VAULT WARDEN'),'Vault Warden did not render');
  }
  assert(elements.bossPhaseText.history.some(v=>v.includes('PHASE II'))&&elements.bossPhaseText.history.some(v=>v.includes('PHASE III')),'boss phases did not trigger');
  elements.closeResult.click();
  assert(elements.contractOverlay.classList.contains('show'),'contract completion was not presented');
  elements.closeContract.click();
  assert.equal(JSON.parse(saved).contractSeen,true,'contract reward was not claimed');
  elements.blueprintButton.click();
  assert(elements.wardenTechGrid.children[furnaceRoute?3:0].className.includes('recovered'),'secured trophy was not visible on the rack');
  elements.closeBlueprints.click();
  if(!furnaceRoute){elements.startButton.click();assert(elements.healthText.textContent.includes('\u25C61'),'Guardian Crest did not grant its starting guard charge')}
}
elements.settingsButton.click();elements.devButton.click();assert(elements.devPanel.classList.contains('show'),'dev panel did not open');assert((elements.devLoot.listeners.click||[]).length===1,'legendary loot shortcut was not wired');assert((elements.devWarden.listeners.click||[]).length===1,'Warden test shortcut was not wired');assert((elements.devTyrant.listeners.click||[]).length===1,'Tyrant test shortcut was not wired');elements.soundToggle.click();elements.closeSettings.click();assert.equal(JSON.parse(saved).settings.sound,false,'settings did not persist');console.log('Release smoke passed in '+(clock/1000).toFixed(1)+' simulated seconds: migration -> bench -> briefing -> relic fusion -> loot recovery -> '+(safeExtract?'safe extraction':(furnaceRoute?'Furnace route -> Tyrant':'Dynamo route -> Warden')+' -> contract')+' -> dev tools -> settings');
