const fs=require('fs'),assert=require('assert'),child=require('child_process');

const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('style.css','utf8');
const script=fs.readFileSync('script.js','utf8');
const progression=require('../progression.js');
const packageJson=JSON.parse(fs.readFileSync('package.json','utf8'));
const retiredRarity=String.fromCharCode(109,121,116,104,105,99);
const ignoredAuditDirs=new Set(['.git','node_modules','playwright-report','test-results']);
function sourceFiles(dir='.'){let files=[];for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(ignoredAuditDirs.has(entry.name))continue;let path=dir+'/'+entry.name;if(entry.isDirectory())files.push(...sourceFiles(path));else if(/\.(?:html|css|js|json|md|py)$/.test(entry.name))files.push(path)}return files}
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);
const unique=new Set(ids);

assert.equal(ids.length,unique.size,'duplicate HTML ids found');
for(const match of script.matchAll(/\$\('([^']+)'\)/g)){
  assert(unique.has(match[1]),'script references missing element #'+match[1]);
}

const openBraces=(css.match(/{/g)||[]).length;
const closeBraces=(css.match(/}/g)||[]).length;
assert.equal(openBraces,closeBraces,'CSS braces are unbalanced');
assert(html.includes('style.css?v='+packageJson.version)&&html.includes('infinite-world.js?v='+packageJson.version)&&html.includes('progression.js?v='+packageJson.version)&&html.includes('script.js?v='+packageJson.version),'release assets do not match package version '+packageJson.version);
assert.equal(progression.MAX_PLAYER_LEVEL,100,'shared player level cap is not 100');
assert.equal(progression.TOTAL_XP_TO_MAX,61094,'Level 100 total XP changed unexpectedly');
assert(script.includes('const progression=window.RiskLootProgression')&&script.includes('MAX_PLAYER_LEVEL')&&script.includes('applyXp(save.level,save.xp'),'shared progression source is not wired into gameplay');
for(const file of sourceFiles())assert(!new RegExp(retiredRarity,'i').test(fs.readFileSync(file,'utf8')),'retired rarity survived in '+file);
assert(/id:'stormrunner',name:'STORMCALLER',rarity:'legendary'/.test(script),'Stormcaller is not classified as Legendary');
assert(fs.existsSync('guild-terrain.js')&&html.includes('guild-terrain.js?v='+packageJson.version),'Guild Outskirts terrain generator is missing or stale');
assert(fs.existsSync('infinite-world.js')&&script.includes('infiniteWorldApi.create')&&script.includes('function refreshWorldStreaming')&&script.includes('function regionContainsLoadedPoint'),'deterministic infinite-world streaming is missing');
assert(script.includes('function beginTouchHelp')&&script.includes('function gearHelpFromNode'),'unified mobile hold-help system is missing');
assert(css.includes('.gearHoverPreview.touchPreview'),'mobile gear comparison preview is missing');
assert(html.includes('id="contractPrompt"')&&html.includes('id="vaultReward"')&&script.includes('function vaultProgress')&&script.includes('function openGrandVault')&&script.includes('function rollVaultGear')&&css.includes('.contractTracker.imminent')&&css.includes('.vaultReward.revealed'),'repeatable Grand Vault reward or anticipation presentation is missing');
for(const asset of ['pappa-hammer-player.png','pappa-hammer-idle-v2.png','pappa-hammer-run-v2.png','pappa-hammer-attack-v2.png','pappa-hammer-workshop.png','pappa-hammer-enemies.png','pappa-hammer-bosses.png','gear-items-atlas.png','gear-drops-atlas.png','gear-atlas.json','set-gear-atlas.png','set-gear-drops.png','set-gear-atlas.json','legendary-gear-atlas.png','legendary-gear-drops.png','legendary-gear-atlas.json','anime-adventure-bag-v2.webp'])assert(fs.existsSync('assets/'+asset),'Pappa Hammer asset is missing: '+asset);
assert(fs.existsSync('assets/bosses/skyglass-leviathan.png'),'Skyglass Leviathan boss asset is missing');
for(const asset of ['dreamworld-ground-tile.png','dreamworld-manifest.json','props/crescent-arch.png','props/violet-crystals.png','props/dream-lotus.png','props/star-map-obelisk.png','props/floating-ruin-pillar.png','props/moon-lantern.png','props/dream-tree.png','props/broken-crescent-shrine.png','cover/intact-ruin-wall.png','cover/broken-ruin-wall.png','cover/violet-crystal-hedge.png','cover/crescent-balustrade.png','cover/floating-stone-blocks.png','cover/cloudstone-wall.png'])assert(fs.existsSync('assets/environment/dreamworld/'+asset),'Dreamworld environment asset is missing: '+asset);
for(const asset of ['skyglass-ground-tile.png','skyglass-manifest.json','props/jellyfish-lantern.png','props/pearl-shell-shrine.png','props/tide-compass-pedestal.png','props/spiral-shell-portal.png','props/coral-garden.png','props/sea-glass-arch.png','props/floating-reef-pillar.png','props/celestial-koi-statue.png','cover/coral-reef-hedge.png','cover/pearl-shell-wall.png','cover/floating-reef-blocks.png','cover/sea-glass-shard-wall.png','cover/intact-glass-balustrade.png','cover/broken-glass-balustrade.png'])assert(fs.existsSync('assets/environment/skyglass/'+asset),'Skyglass environment asset is missing: '+asset);
const gearAtlas=JSON.parse(fs.readFileSync('assets/gear-atlas.json','utf8'));
assert.equal(gearAtlas.items.length,40,'gear atlas must map all 40 items');
assert.equal(new Set(gearAtlas.items.map(item=>item.id)).size,40,'gear atlas item ids must be unique');
assert.deepEqual(gearAtlas.slotOrder,['hat','scarf','coat','hammer','boots'],'gear atlas slot rows are out of order');
for(const item of gearAtlas.items)assert(script.includes("gearDef('"+item.id+"'"),'gear atlas references unknown item: '+item.id);
function pngSize(path){const data=fs.readFileSync(path);return [data.readUInt32BE(16),data.readUInt32BE(20)]}
assert.deepEqual(pngSize('assets/gear-items-atlas.png'),[2560,1280],'full gear atlas dimensions are wrong');
assert.deepEqual(pngSize('assets/gear-drops-atlas.png'),[800,400],'drop gear atlas dimensions are wrong');
const setGearAtlas=JSON.parse(fs.readFileSync('assets/set-gear-atlas.json','utf8'));
assert.equal(setGearAtlas.items.length,80,'set gear atlas must map all 80 authored set pieces');
assert.equal(new Set(setGearAtlas.items.map(item=>item.id)).size,80,'set gear atlas item ids must be unique');
assert.deepEqual(setGearAtlas.slotOrder,['hat','scarf','coat','hammer','boots'],'set gear atlas slot columns are out of order');
assert.deepEqual(pngSize('assets/set-gear-atlas.png'),[1280,4096],'set gear atlas dimensions are wrong');
assert.deepEqual(pngSize('assets/set-gear-drops.png'),[400,1280],'set gear drop atlas dimensions are wrong');
const legendaryAtlas=JSON.parse(fs.readFileSync('assets/legendary-gear-atlas.json','utf8'));
assert.equal(legendaryAtlas.items.length,22,'legendary atlas must map all 20 set pieces and 2 legacy rewards');
assert.equal(new Set(legendaryAtlas.items.map(item=>item.id)).size,22,'legendary atlas item ids must be unique');
assert.deepEqual(legendaryAtlas.slotOrder,['hat','scarf','coat','hammer','boots'],'legendary atlas slot columns are out of order');
assert.deepEqual(pngSize('assets/legendary-gear-atlas.png'),[2560,2560],'legendary gear atlas dimensions are wrong');
assert.deepEqual(pngSize('assets/legendary-gear-drops.png'),[800,800],'legendary drop atlas dimensions are wrong');
for(const pose of ['idle','run','attack'])for(const slot of ['hat','scarf','coat','hammer','boots']){const path='assets/paper-doll/'+pose+'-'+slot+'.png';assert(fs.existsSync(path),'paper-doll mask is missing: '+path);assert.deepEqual(pngSize(path),[1024,512],'paper-doll mask dimensions are wrong: '+path)}
for(const pose of ['idle','run','attack'])assert.deepEqual(pngSize('assets/pappa-hammer-'+pose+'-v2.png'),[2048,1024],'restored original hammer '+pose+' sheet dimensions are wrong');
for(const pose of ['idle','run','attack'])assert.deepEqual(pngSize('assets/hammer-choir-'+pose+'-v1.png'),[2048,1024],'Hammer Choir '+pose+' sheet dimensions are wrong');
for(const pose of ['idle','run','attack'])assert.deepEqual(pngSize('assets/black-hole-hammer-'+pose+'-v1.png'),[2048,1024],'Black Hole Hammer '+pose+' sheet dimensions are wrong');
for(const pose of ['idle','run','attack'])assert.deepEqual(pngSize('assets/lava-hammer-'+pose+'-v1.png'),[2048,1024],'Lava Set '+pose+' sheet dimensions are wrong');
assert.deepEqual(pngSize('assets/handlava-hit-splash-v1.png'),[2048,1024],'Handlava hit splash sheet dimensions are wrong');
assert.deepEqual(pngSize('assets/black-hole-hammer-vfx-v1.png'),[2048,1024],'Black Hole Hammer VFX sheet dimensions are wrong');
for(const phase of ['spawn','idle','pull','pulse','dash','collapse','burst'])assert.deepEqual(pngSize('assets/black-hole-vortex-'+phase+'-v2.png'),[1536,384],'Black Hole vortex '+phase+' sheet dimensions are wrong');
assert.deepEqual(pngSize('assets/black-hole-gear-icons-v1.png'),[1280,256],'Black Hole gear icon strip dimensions are wrong');
assert.deepEqual(pngSize('assets/black-hole-gear-drops-v1.png'),[400,80],'Black Hole gear drop strip dimensions are wrong');
const handlavaPhases=['idle','extend','grab','swing','throw','retract'];
for(const phase of handlavaPhases){const asset='assets/handlava-'+phase+'-v1.png';assert(fs.existsSync(asset),'Handlava '+phase+' spritesheet is missing');assert.deepEqual(pngSize(asset),[1024,256],'Handlava '+phase+' sheet dimensions are wrong')}
assert.deepEqual(pngSize('assets/lava-gear-icons-v1.png'),[1280,256],'Lava Set gear icon strip dimensions are wrong');
assert.deepEqual(pngSize('assets/lava-gear-drops-v1.png'),[400,80],'Lava Set gear drop strip dimensions are wrong');
require('./handlava-assets-smoke.js');
for(const pose of ['idle','run','attack'])assert.deepEqual(pngSize('assets/nature-hammer-'+pose+'-v1.png'),[2048,1024],'Nature Set '+pose+' sheet dimensions are wrong');
assert.deepEqual(pngSize('assets/ancient-ent-v1.png'),[2048,1024],'Ancient Ent sheet dimensions are wrong');
assert.deepEqual(pngSize('assets/nature-root-trap-v1.png'),[2048,1024],'Rootwhip trap sheet dimensions are wrong');
assert.deepEqual(pngSize('assets/nature-gear-icons-v1.png'),[1280,256],'Nature Set gear icon strip dimensions are wrong');
assert.deepEqual(pngSize('assets/nature-gear-drops-v1.png'),[400,80],'Nature Set gear drop strip dimensions are wrong');
require('./nature-assets-smoke.js');
assert(script.includes("assets/pappa-hammer-idle-v2.png")&&script.includes("assets/pappa-hammer-run-v2.png")&&script.includes("assets/pappa-hammer-attack-v2.png")&&script.includes("assets/pappa-hammer-enemies.png")&&script.includes("assets/pappa-hammer-bosses.png"),'Pappa Hammer animation or combat assets are not wired');
assert(script.includes('paperDollSetSprites')&&script.includes('equippedFullSetId')&&script.includes('paperDollSetReady')&&script.includes("assets/hammer-choir-idle-v1.png")&&script.includes("assets/hammer-choir-run-v1.png")&&script.includes("assets/hammer-choir-attack-v1.png"),'production Hammer Choir skin is not wired');
assert(script.includes("assets/black-hole-hammer-idle-v1.png")&&script.includes("assets/black-hole-hammer-run-v1.png")&&script.includes("assets/black-hole-hammer-attack-v1.png")&&script.includes("assets/black-hole-vortex-spawn-v2.png")&&script.includes("assets/black-hole-vortex-idle-v2.png")&&script.includes("assets/black-hole-vortex-pull-v2.png")&&script.includes("assets/black-hole-vortex-pulse-v2.png")&&script.includes("assets/black-hole-vortex-dash-v2.png")&&script.includes("assets/black-hole-vortex-collapse-v2.png")&&script.includes("assets/black-hole-vortex-burst-v2.png")&&script.includes("assets/black-hole-gear-icons-v1.png")&&script.includes("assets/black-hole-gear-drops-v1.png"),'production Black Hole Hammer presentation is not wired');
assert(script.includes('function drawBlackHoleStorm')&&script.includes('function blackHoleStormPhase')&&script.includes('function spawnGravityMotes')&&script.includes("kind:'blackHoleCollapse'")&&!script.includes('blackHoleVfxAtlas'),'dedicated Black Hole timing, particles, collapse, or sprite pipeline is missing');
assert(script.includes("assets/lava-gear-icons-v1.png")&&script.includes("assets/lava-gear-drops-v1.png")&&script.includes("assets/lava-hammer-idle-v1.png")&&script.includes("assets/lava-hammer-run-v1.png")&&script.includes("assets/lava-hammer-attack-v1.png")&&script.includes("assets/handlava-hit-splash-v1.png")&&script.includes("for(const phase of ['idle','extend','grab','swing','throw','retract'])")&&script.includes("loadImage('assets/handlava-'+phase+'-v1.png')"),'Lava Set transformation, gear, splash, or Handlava phase assets are not wired');
assert(script.includes('function createHandlavaState')&&script.includes('function updateHandlava')&&script.includes('function drawHandlavaArms')&&script.includes('profile.handlava=profile.lavaSet'),'Handlava state, rendering, or 5/5 signature alias is missing');
assert(script.includes("assets/nature-gear-icons-v1.png")&&script.includes("assets/nature-gear-drops-v1.png")&&script.includes("assets/nature-hammer-idle-v1.png")&&script.includes("assets/nature-hammer-run-v1.png")&&script.includes("assets/nature-hammer-attack-v1.png")&&script.includes("assets/ancient-ent-v1.png")&&script.includes("assets/nature-root-trap-v1.png"),'Nature Set transformation, gear, Ancient Ent, or Rootwhip assets are not wired');
assert(script.includes('function createNatureAllyState')&&script.includes('function updateNatureAlly')&&script.includes('function drawNatureAlly')&&script.includes('profile.forestAlly=profile.natureSet'),'Ancient Ent state, rendering, or 5/5 Nature signature alias is missing');
assert(script.includes('pendingStrikes')&&script.includes('releaseHammerStrike')&&script.includes("kind:'hammerSwing'"),'melee hammer timing or impact arc is missing');
assert(!script.includes('bullets.push(')&&script.includes('nearestEnemy(MELEE.reach+32)'),'safe player ranged damage still exists');
assert(css.includes('@keyframes pappaHammerFrames')&&css.includes("background-image:url('assets/pappa-hammer-idle-v2.png')"),'live Gear Locker animation is missing');
assert(script.includes('THE FIRST LOCK')&&script.includes('A FORMAL BOW')&&script.includes('source:e.bossKind||e.type'),'distinct boss personalities are not wired');
assert(script.includes('function combatViewContains')&&script.includes('function enemyCanAttack')&&script.includes('combatViewContains(b.x,b.y,b.r,0,bulletCam)'),'offscreen enemy projectile safety is missing');
assert(script.includes('ARENA_OBSTACLE_LAYOUT')&&script.includes('function moveAroundCover')&&script.includes('projectileHitsCover(b.x,b.y,b.r)')&&script.includes('lineBlockedByCover'),'physical arena cover is missing');
assert(script.includes('function guildWaveSpawnAnchors')&&script.includes('function guildRoutePosition')&&script.includes("guildTerrainApi.generate(currentMapSeed,mapId)")&&script.includes('bossAnchor=guildTerrain?guildTerrain.bossAnchor:null')&&html.includes('id="mapSeedDebug"'),'procedural biome integration is missing');
assert(script.includes('CAMERA_ZOOM={mobile:.72,desktop:.8}')&&script.includes('ctx.scale(cam.zoom,cam.zoom)'),'zoomed-out combat camera is missing');
assert(script.includes('function updateEnemyEntity')&&script.includes('spawnGrace:spawnDuration')&&script.includes('e.stepFx<=0'),'living enemy movement or deterministic arrival animation is missing');
assert(script.includes('TANK_RUSH_RANGE=440')&&script.includes('TANK_RUSH_OVERSHOOT=72')&&script.includes('function prepareEnemyDash')&&script.includes('function finishEnemyDash')&&script.includes('function drawTankTelegraph')&&script.includes("kind:'tankImpact'"),'Shield Guard long rush, recovery, or danger-lane feedback is missing');
assert(script.includes('LANCER_THRUST_RANGE=430')&&script.includes('RUSHER_POUNCE_SPEED=455')&&script.includes('function drawLancerTelegraph'),'Lancer thrust or Rusher pounce identity is missing');
assert(script.includes('ENEMY_SPAWN_GRACE=.42')&&script.includes('overlapRatio:.58')&&script.includes('clearBreather:.24')&&script.includes('attackDuration:.24'),'Anime Rush combat pacing is missing');
assert(script.includes('REGULAR_ENEMY_DAMAGE_SCALE=.82')&&script.includes('map.enemyDamage*.45*REGULAR_ENEMY_DAMAGE_SCALE'),'regular-enemy forgiveness scaling is missing');
assert(script.includes("damage:((isTyrant?20:isLagoon?18:18)+riskTier*1.5)*levelScale.damage*map.bossDamage"),'Champion damage must remain independent from regular-enemy scaling');
assert(script.includes('fan=(e.elite||depth>=3)'),'Gunner fan-volley variation is missing');
assert(!/v0\.[23456]\.\d/.test(html+css+script),'stale release version found');
assert(script.includes('DEPTH_THRESHOLDS=[0,32,68,108,150]')&&script.includes('function enemySpawningLocked()')&&script.includes('function lockEnemySpawning()'),'boss pacing or spawn locking is missing');
assert(script.includes('BOSS_SCHEMATICS')&&script.includes('pendingWardenReward'),'permanent boss rewards are missing');
assert(script.includes('burstVolleyBonus')&&script.includes('platingProtection'),'meaningful fractional Blueprint mastery is missing');
assert(html.includes('id="resultTime"')&&html.includes('id="routeProgressFill"')&&html.includes('id="wardenTechGrid"'),'playtest readout, route progress, or schematic bench is missing');
assert(html.includes('id="routeOverlay"')&&html.includes('id="routeFurnace"')&&html.includes('id="routeDynamo"'),'branching route choice is missing');
assert(script.includes('ROUTES')&&script.includes('routeDecision')&&script.includes('chooseRoute'),'branching route logic is missing');
assert(script.includes('tyrantVolley')&&script.includes('thermalBlast'),'Furnace boss or Thermal Capacitor is missing');
assert(script.includes("boss:'leviathan'")&&script.includes('function leviathanVolley')&&script.includes('function drawLagoonBossArt')&&script.includes("type:'lagoonPool'"),'Skyglass Leviathan identity, attacks, or animation is missing');
assert(script.includes('function spawnWardenLock')&&script.includes("type:'vaultSeal'")&&script.includes("type:'wardenLock'"),'Vault Warden arena locks are missing');
assert(script.includes("spawnBossLane(e,'crimsonCleave'")&&script.includes("spawnBossLane(e,'tidalLane'"),'Champion cleaves or Leviathan tide lanes are missing');
assert(script.includes('function drawBossLaneHazard')&&script.includes('function drawVaultSealHazard')&&script.includes('function pointSegmentDistance'),'Champion telegraphs or lane collision are missing');
assert(script.includes('e.stagger=.58')&&script.includes('if(e.stagger>0)'),'Champion phase stagger is missing');
assert(html.includes('id="miniMapCanvas"')&&html.includes('id="miniMapCacheCount"')&&script.includes('function drawMiniMap')&&script.includes('rareCaches=caches.filter'),'rare-cache minimap is missing');
assert(html.includes('id="xpHud"')&&html.includes('id="xpFill"')&&html.includes('id="xpSpark"')&&html.includes('id="xpGain"')&&html.includes('id="xpLevelNotice"')&&script.includes('function syncXpHud')&&script.includes('function updateXpPresentation')&&script.includes('function pulseXpLevel'),'live expedition XP rail or level feedback is missing');
assert(script.includes('LOOT_ITEMS')&&script.includes('lootDrops')&&script.includes('collectLoot')&&script.includes('drawAdventureItemShape'),'physical loot item system is missing');
assert(script.includes("SAVE_VERSION=12")&&script.includes('if(raw.version!==SAVE_VERSION)raw={}')&&script.includes('materials:0,legendaryCores:0')&&script.includes('gear:[]')&&script.includes('level:1,xp:0')&&script.includes('equipped:{hat:null,scarf:null,coat:null,hammer:null,boots:null}'),'Level 100 save reset, unique gear, or progression model is missing');
assert(html.includes('id="mapOverlay"')&&html.includes('id="mapGrid"')&&script.includes('const EXPEDITION_MAPS=')&&script.includes('MAP_UNLOCK_LEVELS.summit')&&script.includes('function renderMapAtlas'),'level-gated Adventure Atlas is missing');
assert(script.includes('activeMap().spawnRate')&&script.includes('map.enemyHp')&&script.includes('map.bossHp')&&script.includes('map.rarityBonus'),'map-specific combat and reward profiles are missing');
assert(script.includes('DREAMWORLD_DECOR_LAYOUT')&&script.includes('function drawDreamworldGround')&&script.includes('function drawDreamworldDecor')&&script.includes('function drawDreamworldCover'),'Dreamworld environment rendering is missing');
assert(css.includes("assets/environment/dreamworld/dreamworld-ground-tile.png")&&css.includes("assets/environment/dreamworld/props/crescent-arch.png"),'Moonfall map preview is not using the Dreamworld assets');
assert(script.includes('SKYGLASS_DECOR_LAYOUT')&&script.includes('function drawSkyglassGround')&&script.includes('function drawSkyglassDecor')&&script.includes('function drawSkyglassCover'),'Skyglass environment rendering is missing');
assert(css.includes("assets/environment/skyglass/skyglass-ground-tile.png")&&css.includes("assets/environment/skyglass/props/celestial-koi-statue.png"),'Skyglass map preview is not using the imported assets');
assert(script.includes('const SET_DEFINITIONS=[')&&script.includes('const SET_ITEMS=SET_DEFINITIONS.flatMap')&&script.includes('activeSetBonuses'),'set item catalog or fixed set bonuses are missing');
assert(script.includes('const GEAR_SIGNATURES=')&&script.includes('function gearSignatureProfile'),'Gear 2.0 signature registry is missing');
for(const signature of ['trailwarden','ironGuild','redBanner','moonlitScout','coinseeker','towerBulwark','stormrunner','hammerChoir','lanternGuard','grandWayfarer','crimsonOath','moonbreaker','kingsRoad','phantomCourt','starforge','grandVoyager','lavaSet','natureSet','riskreaver','grandVault','crownlessKing','fatebound','blackHole'])assert(script.includes(signature+':{role:'),'Gear 2.0 signature is missing: '+signature);
assert(script.includes('function triggerGravityWell')&&script.includes("kind:'blackHoleVfx'")&&script.includes("mode:'vortex'"),'Black Hole gravity combat identity is incomplete');
assert(script.includes('function releaseStormDash')&&script.includes('function triggerCritEcho')&&script.includes('function triggerMoonArc')&&script.includes('function triggerFloorSignatures')&&script.includes('player.guardCd')&&script.includes('player.fateSaved'),'Gear 2.0 combat effects are incomplete');
assert(script.includes('maxDashesPerSecond:10')&&script.includes('damageMultiplier:2.75')&&script.includes('overchargeDuration:10')&&script.includes('damageReduction:.35'),'Stormcaller power, achievable tap cap, opening overcharge, or protection is missing');
assert(script.includes('function lightningChainTargets')&&script.includes('function strikeWithLightning')&&script.includes("kind:'lightningChain'")&&script.includes("sound('lightningImpact'"),'Stormcaller pack chaining, launch impact, visuals, or layered audio is missing');
assert(css.includes('.gearSignature')&&css.includes('.gearDeltaGrid')&&css.includes('.signatureAwaken'),'Gear 2.0 inventory or equip feedback is missing');
assert(script.includes('function rollBossGear')&&script.includes('function awardEnemyXp')&&script.includes('function applyPlayerXpReward')&&script.includes('getEnemyXpReward({enemyType:enemy.type')&&script.includes('function showBossLootRitual')&&script.includes('function drawBossLootChest')&&script.includes('function openBossLootChest')&&script.includes('function resolveBossLoot')&&script.includes('registerRunGear(gear,false,player.x,player.y)'),'boss-only equipment, physical champion cache, loot decision ritual, or immediate Pappa XP is missing');
assert(script.includes('routeRare*.2')&&script.includes('routeRare*.55')&&script.includes('routeRare*.45'),'Moonlit Path does not improve boss set rarity');
assert(script.includes('bossScaleForLevel(save.level)')&&script.includes('enemyScaleForLevel(save.level)'),'enemy or boss scaling is not using the Level 100 progression model');
assert(/function destroyEnemy\(e\)[\s\S]*?runScrap\+=coins;/.test(script)&&!/function destroyEnemy\(e\)[^}]*spawnLoot\(/.test(script),'ordinary enemies must award coins instead of gear');
assert(script.includes("const GEAR_SLOTS=['hat','scarf','coat','hammer','boots']")&&script.includes('gearStats')&&script.includes('gearArtMarkup'),'gear slots, stats, or visual equipment are missing');
assert(script.includes('paperDollMasks')&&script.includes('composePaperDollPose')&&script.includes('paperDollAtlases[pose]'),'animated equipped gear is not wired into Pappa Hammer');
assert(script.includes('PAPER_DOLL_CELL=512')&&script.includes('PAPER_DOLL_MASK_CELL=256'),'paper-doll output is not Retina sharp or mobile optimized');
assert(!script.includes('drawPaperDollSilhouette'),'equipped gear must stay inside the painted hero instead of adding rarity-colored outlines');
assert(html.includes('id="pappaHammerBaseSprite"')&&css.includes('.pappaHammerBaseMotion')&&css.includes('.pappaHammerBaseVisual'),'layered workshop Pappa motion rig is missing');
assert(/\.pappaHammerBaseSprite\{[\s\S]*?image-rendering:auto;[\s\S]*?filter:none;[\s\S]*?\}/.test(css),'iPhone-softening hero filter is active');
assert(css.includes('@keyframes pappaMenuWeightShift')&&css.includes('@keyframes pappaMenuBreath')&&css.includes('@keyframes pappaMenuFollowThrough'),'premium workshop motion is incomplete');
assert(!/\.pappaHammerBase\{[^}]*background(?:-image)?:/.test(css),'obsolete default Pappa background still renders beneath Gear 2.0');
assert(!html.includes('id="baseGearPreview"')&&!html.includes('id="gearCharacterPreview"')&&!script.includes('renderGearLayers'),'obsolete paper-doll overlay hierarchy is still present');
assert(html.includes('id="gearLockerButton"')&&html.includes('id="gearGrid"')&&html.includes('class="gearCharacterHero"'),'Gear Locker or live character preview is missing');
assert(html.includes('id="gearTurnLeft"')&&html.includes('id="gearTurnRight"')&&html.includes('id="gearSetSummary"')&&script.includes('updateGearTurntable'),'rotating preview or set summary is missing');
assert(html.includes('id="gearRarityFilters"')&&html.includes('id="sellFilteredGear"')&&script.includes('filteredGearSaleSummary')&&script.includes('sellFilteredGear'),'protected filtered gear sale is missing');
assert(html.includes('id="gearInventorySummary"')&&html.includes('id="gearRaritySummary"')&&html.includes('id="gearSortButton"')&&html.includes('id="gearDetail"'),'inventory count, rarity summary, sorting, or item details are missing');
assert(html.includes('id="gearHoverPreview"')&&script.includes('function showGearHover')&&script.includes('function bindGearHover')&&css.includes('.gearHoverPreview.show'),'per-item hover and focus preview is missing');
assert(html.includes('id="helpTooltip"')&&script.includes('function bindContextHelp')&&script.includes('HELP_COPY')&&css.includes('.helpTooltip.show'),'universal contextual help is missing');
assert(script.includes('function beginTouchHelp')&&script.includes('function queueHelp')&&script.includes('suppressedHelpTarget'),'deliberate mobile hold-help or restrained desktop hover timing is missing');
assert(html.includes('id="bossLootCompare"')&&html.includes('data-help-title="Risk or Extract"')&&html.includes('data-help-title="Destination Progress"')&&script.includes('data-help-title="Hammer Damage"'),'important progression, loot and loadout explanations are missing');
assert(script.includes("ui.game.classList.toggle('runMode'")&&css.includes('#game.runMode .topbar')&&css.includes('grid-template-rows:36px'),'compact expedition HUD is missing');
assert(html.includes('ADVENTURE BAG')&&html.includes('animeBagShell')&&html.includes('unifiedEquipmentWorkspace')&&html.includes('equipmentOrbitSlots')&&html.includes('mobileGearSelection')&&html.includes('gearToolbar')&&css.includes('Armory interaction and hierarchy redesign'),'focused Adventure Bag presentation is missing');
assert(!html.includes('class="gearCategoryPanel"')&&!html.includes('class="gearCharacterHeading"'),'obsolete Armory navigation or character heading remains');
assert(!html.includes('class="adventureBagHeader"')&&!html.includes('PAPPA HAMMER\'S</span>')&&!html.includes('SECURED LOOT</span>')&&html.includes('id="closeGear" class="panelClose"'),'obsolete Adventure Bag masthead remains or the close control is missing');
assert(css.includes("assets/anime-adventure-bag-v2.webp")&&script.includes('function setGearView')&&script.includes("gearView='unified'"),'illustrated bag or unified Pappa loadout view is missing');
assert(script.includes('const GEAR_SORTS=')&&script.includes('function renderGearDetail')&&script.includes('function drawEquippedRarityAura'),'inventory sorting, item comparison, or high-rarity presentation is missing');
assert(script.includes('gear-items-atlas.png')&&script.includes('gear-drops-atlas.png')&&script.includes('set-gear-atlas.png')&&script.includes('set-gear-drops.png')&&script.includes('legendary-gear-atlas.png')&&script.includes('legendary-gear-drops.png')&&script.includes('SET_GEAR_ROW')&&script.includes('LEGENDARY_SET_ROW')&&script.includes('drawAdventureLootSprite')&&css.includes("background-image:url('assets/gear-items-atlas.png')")&&css.includes("background-image:url('assets/set-gear-atlas.png')")&&css.includes("background-image:url('assets/legendary-gear-atlas.png')"),'sprite-atlas item identities are missing');
assert(!script.includes('createPreviewGear')&&!css.includes('.previewGear.hammer'),'obsolete geometric equipment overlays are still active');
assert(!html.includes('id="upgradeChassis"')&&!html.includes('id="upgradeWeapon"')&&!html.includes('id="upgradeSalvage"'),'obsolete direct stat upgrades are still visible');
assert(script.includes('RELIC_POWER_CAP')&&script.includes('prepareRelic')&&script.includes('FUSED'),'relic fusion system is missing');
assert(html.includes('id="resultLoot"')&&html.includes('id="lootToast"')&&html.includes('id="lootBest"'),'loot feedback UI is missing');
assert(html.includes('id="bossLootOverlay"')&&html.includes('id="bossLootEquip"')&&html.includes('id="bossLootSalvage"')&&html.includes('id="materialCount"')&&html.includes('id="bossLootExtract"')&&html.includes('id="bossLootPush"')&&script.includes('function continueAfterBoss')&&script.includes('function spawnExtractionAmbush'),'post-boss loot decision and risk loop is missing');
assert(script.includes("common:{materials:1,cores:0}")&&script.includes("uncommon:{materials:2,cores:0}")&&script.includes("rare:{materials:5,cores:0}")&&script.includes("epic:{materials:15,cores:0}")&&script.includes("legendary:{materials:25,cores:1}"),'salvage reward table is incomplete');
assert(!html.includes('id="riskOverlay"')&&!script.includes('showRiskDecision'),'obsolete pre-boss Risk It interruption is still present');
assert(script.includes('bossGearOdds(nextLevel,riskTier+2)')&&html.includes('EPIC+ ODDS'),'loot odds are not explained with concrete values');
assert(html.includes('id="resultLootSummary"')&&script.includes('resultLootGroup')&&script.includes('gearQualityLabel(drop)'),'sorted post-run gear report is missing');
assert(html.includes('id="devGear"')&&html.includes('id="devGearSelect"')&&html.includes('id="devGearSpawn"')&&html.includes('id="devGearEquip"')&&script.includes('function devGrantGear')&&script.includes('SET_DEFINITIONS')&&script.includes('LOOT_ITEMS'),'unified gear test tool is missing');
assert(!html.includes('id="devRig"')&&!html.includes('id="devBlackHole"')&&!html.includes('id="devLoot"'),'obsolete gear-specific dev tools are still visible');
assert(html.includes('id="devButton"')&&html.includes('id="devWarden"')&&html.includes('id="devTyrant"')&&script.includes('devFightWarden')&&script.includes('devFightTyrant'),'playtest dev tools are missing');
assert(html.includes('viewport-fit=cover'),'mobile safe-area viewport support is missing');
assert(css.includes('env(safe-area-inset-bottom)')&&css.includes('@media(max-width:420px){.resultStats'),'mobile safe areas or narrow result layout is missing');
assert(css.includes('.routeProgress')&&css.includes('.routeOverlay')&&css.includes('.touchControls{display:block}'),'route choice, route progress, or touch controls are missing');

child.execFileSync(process.execPath,['--check','progression.js'],{stdio:'inherit'});
child.execFileSync(process.execPath,['--check','infinite-world.js'],{stdio:'inherit'});
child.execFileSync(process.execPath,['--check','script.js'],{stdio:'inherit'});
console.log('Static audit passed: unique ids -> DOM bindings -> CSS balance -> JS syntax');
