const fs=require('fs'),assert=require('assert'),child=require('child_process');

const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('style.css','utf8');
const script=fs.readFileSync('script.js','utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);
const unique=new Set(ids);

assert.equal(ids.length,unique.size,'duplicate HTML ids found');
for(const match of script.matchAll(/\$\('([^']+)'\)/g)){
  assert(unique.has(match[1]),'script references missing element #'+match[1]);
}

const openBraces=(css.match(/{/g)||[]).length;
const closeBraces=(css.match(/}/g)||[]).length;
assert.equal(openBraces,closeBraces,'CSS braces are unbalanced');
assert(html.includes('style.css?v=0.25.0')&&html.includes('script.js?v=0.25.0'),'release assets are not versioned');
for(const asset of ['pappa-hammer-player.png','pappa-hammer-idle-v2.png','pappa-hammer-run-v2.png','pappa-hammer-attack-v2.png','pappa-hammer-workshop.png','pappa-hammer-enemies.png','pappa-hammer-bosses.png','gear-items-atlas.png','gear-drops-atlas.png','gear-atlas.json','set-gear-atlas.png','set-gear-drops.png','set-gear-atlas.json','legendary-gear-atlas.png','legendary-gear-drops.png','legendary-gear-atlas.json','anime-adventure-bag-v2.webp'])assert(fs.existsSync('assets/'+asset),'Pappa Hammer asset is missing: '+asset);
const gearAtlas=JSON.parse(fs.readFileSync('assets/gear-atlas.json','utf8'));
assert.equal(gearAtlas.items.length,40,'gear atlas must map all 40 items');
assert.equal(new Set(gearAtlas.items.map(item=>item.id)).size,40,'gear atlas item ids must be unique');
assert.deepEqual(gearAtlas.slotOrder,['hat','scarf','coat','hammer','boots'],'gear atlas slot rows are out of order');
for(const item of gearAtlas.items)assert(script.includes("gearDef('"+item.id+"'"),'gear atlas references unknown item: '+item.id);
function pngSize(path){const data=fs.readFileSync(path);return [data.readUInt32BE(16),data.readUInt32BE(20)]}
assert.deepEqual(pngSize('assets/gear-items-atlas.png'),[2560,1280],'full gear atlas dimensions are wrong');
assert.deepEqual(pngSize('assets/gear-drops-atlas.png'),[800,400],'drop gear atlas dimensions are wrong');
const setGearAtlas=JSON.parse(fs.readFileSync('assets/set-gear-atlas.json','utf8'));
assert.equal(setGearAtlas.items.length,80,'set gear atlas must map all 80 non-legendary set pieces');
assert.equal(new Set(setGearAtlas.items.map(item=>item.id)).size,80,'set gear atlas item ids must be unique');
assert.deepEqual(setGearAtlas.slotOrder,['hat','scarf','coat','hammer','boots'],'set gear atlas slot columns are out of order');
assert.deepEqual(pngSize('assets/set-gear-atlas.png'),[1280,4096],'set gear atlas dimensions are wrong');
assert.deepEqual(pngSize('assets/set-gear-drops.png'),[400,1280],'set gear drop atlas dimensions are wrong');
const legendaryAtlas=JSON.parse(fs.readFileSync('assets/legendary-gear-atlas.json','utf8'));
assert.equal(legendaryAtlas.items.length,22,'legendary atlas must map all 20 set pieces and 2 legacy rewards');
assert.equal(new Set(legendaryAtlas.items.map(item=>item.id)).size,22,'legendary atlas item ids must be unique');
assert.deepEqual(legendaryAtlas.slotOrder,['hat','scarf','coat','hammer','boots'],'legendary atlas slot columns are out of order');
assert.deepEqual(pngSize('assets/legendary-gear-atlas.png'),[2560,2560],'legendary gear atlas dimensions are wrong');
assert.deepEqual(pngSize('assets/legendary-gear-drops.png'),[800,800],'legendary drop atlas dimensions are wrong');
for(const pose of ['idle','run','attack'])for(const slot of ['hat','scarf','coat','hammer','boots']){const path='assets/paper-doll/'+pose+'-'+slot+'.png';assert(fs.existsSync(path),'paper-doll mask is missing: '+path);assert.deepEqual(pngSize(path),[1024,512],'paper-doll mask dimensions are wrong: '+path)}
for(const pose of ['idle','run','attack'])assert.deepEqual(pngSize('assets/pappa-hammer-'+pose+'-v2.png'),[2048,1024],'restored original hammer '+pose+' sheet dimensions are wrong');
assert(script.includes("assets/pappa-hammer-idle-v2.png")&&script.includes("assets/pappa-hammer-run-v2.png")&&script.includes("assets/pappa-hammer-attack-v2.png")&&script.includes("assets/pappa-hammer-enemies.png")&&script.includes("assets/pappa-hammer-bosses.png"),'Pappa Hammer animation or combat assets are not wired');
assert(script.includes('pendingStrikes')&&script.includes('releaseHammerStrike')&&script.includes("kind:'hammerSwing'"),'ranged melee hammer timing or impact arc is missing');
assert(css.includes('@keyframes pappaHammerFrames')&&css.includes("background-image:url('assets/pappa-hammer-idle-v2.png')"),'live Gear Locker animation is missing');
assert(script.includes('THE FIRST LOCK')&&script.includes('A FORMAL BOW')&&script.includes('source:e.bossKind||e.type'),'distinct boss personalities are not wired');
assert(script.includes('function combatViewContains')&&script.includes('function enemyCanAttack')&&script.includes('combatViewContains(b.x,b.y,b.r,0,bulletCam)'),'offscreen enemy projectile safety is missing');
assert(script.includes('function updateEnemyEntity')&&script.includes('spawnGrace:spawnDuration')&&script.includes('e.stepFx<=0'),'living enemy movement or deterministic arrival animation is missing');
assert(script.includes('TANK_RUSH_WINDUP')&&script.includes('function drawTankTelegraph')&&script.includes("kind:'tankImpact'"),'Shield Guard rush or danger-lane feedback is missing');
assert(!/v0\.[23456]\.\d/.test(html+css+script),'stale release version found');
assert(script.includes('DEPTH_THRESHOLDS=[0,55,120,195,280]'),'expedition pacing is missing');
assert(script.includes('BOSS_SCHEMATICS')&&script.includes('pendingWardenReward'),'permanent boss rewards are missing');
assert(script.includes('burstVolleyBonus')&&script.includes('platingProtection'),'meaningful fractional Blueprint mastery is missing');
assert(html.includes('id="resultTime"')&&html.includes('id="routeProgressFill"')&&html.includes('id="wardenTechGrid"'),'playtest readout, route progress, or schematic bench is missing');
assert(html.includes('id="routeOverlay"')&&html.includes('id="routeFurnace"')&&html.includes('id="routeDynamo"'),'branching route choice is missing');
assert(script.includes('ROUTES')&&script.includes('routeDecision')&&script.includes('chooseRoute'),'branching route logic is missing');
assert(script.includes('tyrantVolley')&&script.includes('thermalBlast'),'Furnace boss or Thermal Capacitor is missing');
assert(script.includes('LOOT_ITEMS')&&script.includes('lootDrops')&&script.includes('collectLoot')&&script.includes('drawAdventureItemShape'),'physical loot item system is missing');
assert(script.includes("SAVE_VERSION=10")&&script.includes('gear:[]')&&script.includes('level:1,xp:0')&&script.includes('equipped:{hat:null,scarf:null,coat:null,hammer:null,boots:null}'),'unique gear save, Pappa level, or migration model is missing');
assert(html.includes('id="mapOverlay"')&&html.includes('id="mapGrid"')&&script.includes('const EXPEDITION_MAPS=')&&script.includes("minLevel:16")&&script.includes('function renderMapAtlas'),'level-gated Adventure Atlas is missing');
assert(script.includes('activeMap().spawnRate')&&script.includes('map.enemyHp')&&script.includes('map.bossHp')&&script.includes('map.rarityBonus'),'map-specific combat and reward profiles are missing');
assert(script.includes('const SET_DEFINITIONS=[')&&script.includes('const SET_ITEMS=SET_DEFINITIONS.flatMap')&&script.includes('activeSetBonuses'),'set item catalog or fixed set bonuses are missing');
assert(script.includes('function rollBossGear')&&script.includes('function grantBossXp')&&script.includes("spawnLoot(player.x+(i-(drops-1)/2)*28,player.y,rollBossGear(save.level),true)"),'boss-only equipment or Pappa XP is missing');
assert(script.includes('routeRare*.2')&&script.includes('routeRare*.55')&&script.includes('routeRare*.45'),'Moonlit Path does not improve boss set rarity');
assert(script.includes("(save.level-1)*.11")&&script.includes("(save.level-1)*.035"),'boss health and damage do not scale with Pappa level');
assert(/function destroyEnemy\(e\)[\s\S]*?runScrap\+=coins;/.test(script)&&!/function destroyEnemy\(e\)[^}]*spawnLoot\(/.test(script),'ordinary enemies must award coins instead of gear');
assert(script.includes("const GEAR_SLOTS=['hat','scarf','coat','hammer','boots']")&&script.includes('gearStats')&&script.includes('gearArtMarkup'),'gear slots, stats, or visual equipment are missing');
assert(script.includes('paperDollMasks')&&script.includes('composePaperDollPose')&&script.includes('paperDollAtlases[pose]'),'animated equipped gear is not wired into Pappa Hammer');
assert(script.includes('PAPER_DOLL_CELL=512')&&script.includes('PAPER_DOLL_MASK_CELL=256'),'paper-doll output is not Retina sharp or mobile optimized');
assert(/\.pappaHammerBase\{[\s\S]*?image-rendering:auto;[\s\S]*?filter:none;[\s\S]*?\}/.test(css),'iPhone-softening hero filter is active');
assert(html.includes('id="gearLockerButton"')&&html.includes('id="gearGrid"')&&html.includes('id="gearCharacterPreview"'),'Gear Locker or live character preview is missing');
assert(html.includes('id="gearTurnLeft"')&&html.includes('id="gearTurnRight"')&&html.includes('id="gearSetSummary"')&&script.includes('updateGearTurntable'),'rotating preview or set summary is missing');
assert(html.includes('id="gearRarityFilters"')&&html.includes('id="sellFilteredGear"')&&script.includes('gearSellableCount')&&script.includes('sellFilteredGear'),'protected filtered gear sale is missing');
assert(html.includes('id="gearBagCount"')&&html.includes('id="gearRaritySummary"')&&html.includes('id="gearSortButton"')&&html.includes('id="gearDetail"'),'Vault Bag count, rarity summary, sorting, or item details are missing');
assert(html.includes('id="gearHoverPreview"')&&script.includes('function showGearHover')&&script.includes('function bindGearHover')&&css.includes('.gearHoverPreview.show'),'per-item hover and focus preview is missing');
assert(html.includes('id="helpTooltip"')&&script.includes('function bindContextHelp')&&script.includes('HELP_COPY')&&css.includes('.helpTooltip.show'),'universal contextual help is missing');
assert(script.includes("ui.game.classList.toggle('runMode'")&&css.includes('#game.runMode .topbar')&&css.includes('grid-template-rows:36px'),'compact expedition HUD is missing');
assert(html.includes('ADVENTURE BAG')&&html.includes('animeBagShell')&&html.includes('gearCategoryRail')&&html.includes('id="gearBagTab"')&&html.includes('id="gearLoadoutTab"')&&css.includes('v0.19 release Adventure Bag and Legendary Forge'),'release Adventure Bag presentation is missing');
assert(css.includes("assets/anime-adventure-bag-v2.webp")&&script.includes('function setGearView')&&script.includes("setGearView('loadout')"),'illustrated bag or separate Pappa loadout view is missing');
assert(script.includes('const GEAR_SORTS=')&&script.includes('function renderGearDetail')&&script.includes('function drawEquippedRarityAura'),'inventory sorting, item comparison, or high-rarity presentation is missing');
assert(script.includes('gear-items-atlas.png')&&script.includes('gear-drops-atlas.png')&&script.includes('set-gear-atlas.png')&&script.includes('set-gear-drops.png')&&script.includes('legendary-gear-atlas.png')&&script.includes('legendary-gear-drops.png')&&script.includes('SET_GEAR_ROW')&&script.includes('LEGENDARY_SET_ROW')&&script.includes('drawAdventureLootSprite')&&css.includes("background-image:url('assets/gear-items-atlas.png')")&&css.includes("background-image:url('assets/set-gear-atlas.png')")&&css.includes("background-image:url('assets/legendary-gear-atlas.png')"),'sprite-atlas item identities are missing');
assert(!script.includes('createPreviewGear')&&!css.includes('.previewGear.hammer'),'obsolete geometric equipment overlays are still active');
assert(!html.includes('id="upgradeChassis"')&&!html.includes('id="upgradeWeapon"')&&!html.includes('id="upgradeSalvage"'),'obsolete direct stat upgrades are still visible');
assert(script.includes('RELIC_POWER_CAP')&&script.includes('prepareRelic')&&script.includes('FUSED'),'relic fusion system is missing');
assert(html.includes('id="resultLoot"')&&html.includes('id="lootToast"')&&html.includes('id="lootBest"'),'loot feedback UI is missing');
assert(html.includes('id="resultLootSummary"')&&script.includes('resultLootGroup')&&script.includes('gearQualityLabel(drop)'),'sorted post-run gear report is missing');
assert(html.includes('id="devLoot"')&&script.includes('devDropLegendary'),'legendary loot test tool is missing');
assert(html.includes('id="devButton"')&&html.includes('id="devWarden"')&&html.includes('id="devTyrant"')&&script.includes('devFightWarden')&&script.includes('devFightTyrant'),'playtest dev tools are missing');
assert(html.includes('viewport-fit=cover'),'mobile safe-area viewport support is missing');
assert(css.includes('env(safe-area-inset-bottom)')&&css.includes('@media(max-width:420px){.resultStats'),'mobile safe areas or narrow result layout is missing');
assert(css.includes('.routeProgress')&&css.includes('.routeOverlay')&&css.includes('.touchControls{display:block}'),'route choice, route progress, or touch controls are missing');

child.execFileSync(process.execPath,['--check','script.js'],{stdio:'inherit'});
console.log('Static audit passed: unique ids -> DOM bindings -> CSS balance -> JS syntax');
